/-
# Chapter 3: Cones and Cosmic Closure

Formalization of the first part of Chapter 3 of Rockafellar & Wets,
"Variational Analysis".
-/

import RockafellarWets.Chapter3.Defs
import RockafellarWets.Chapter3.CosmicSpace
import RockafellarWets.Chapter3.HorizonCones
import RockafellarWets.Chapter3.LinearImages
import RockafellarWets.Chapter3.NonlinearImages
import RockafellarWets.Chapter3.SetOperations
import RockafellarWets.Chapter3.Cones
import RockafellarWets.Chapter3.PointedCones
import RockafellarWets.Chapter3.FiniteConeSetOperations
import RockafellarWets.Chapter3.GeneratedCones
import RockafellarWets.Chapter3.PositiveHomogeneity
import RockafellarWets.Chapter3.HomogeneousOperations
import RockafellarWets.Chapter3.HomogeneousCompletion
import RockafellarWets.Chapter3.HomogeneousSublinearCompletion
import RockafellarWets.Chapter3.PositiveHulls
import RockafellarWets.Chapter3.PositiveHullExactCompletion
import RockafellarWets.Chapter3.Entropy
import RockafellarWets.Chapter3.CosmicClosure
import RockafellarWets.Chapter3.GeneratedSets
import RockafellarWets.Chapter3.MinkowskiWeyl
import RockafellarWets.Chapter3.MinkowskiWeylExamples
import RockafellarWets.Chapter3.PolyhedralFunctions
import RockafellarWets.Chapter3.PolyhedralGeneration
import RockafellarWets.Chapter3.HorizonFunctions
import RockafellarWets.Chapter3.HorizonFunctionFormulas
import RockafellarWets.Chapter3.Coercivity
import RockafellarWets.Chapter3.CoercivityCompletion
import RockafellarWets.Chapter3.CoercivityLimit
import RockafellarWets.Chapter3.CoercivityHorizonEquivalence
import RockafellarWets.Chapter3.ParametricCoercivity
import RockafellarWets.Chapter3.ConvexHullFunctions
import RockafellarWets.Chapter3.ConvexHullFunctionSharp
import RockafellarWets.Chapter3.Pointwise
import RockafellarWets.Chapter3.Parametric
import RockafellarWets.Chapter3.ConstraintHorizons
import RockafellarWets.Chapter3.EpiAddition
import RockafellarWets.Chapter3.HorizonAddition
import RockafellarWets.Chapter3.EpiAdditionCompletion
import RockafellarWets.Chapter3.EpiAdditionBookCompletion
import RockafellarWets.Chapter3.Cancellation
import RockafellarWets.Chapter3.ExtendedCancellationCompletion
import RockafellarWets.Chapter3.ProximalCancellationCompletion
import RockafellarWets.Chapter3.SetCancellation
import RockafellarWets.Chapter3.PolyhedralOperations
import RockafellarWets.Chapter3.PolyhedralOperationExamples
import RockafellarWets.Chapter3.Orderings
import RockafellarWets.Chapter3.MatrixOrderings
