/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Chapter 4: Set Convergence
-/

import RockafellarWets.Chapter4.SetLimits
import RockafellarWets.Chapter4.SetLimitCharacterizations
import RockafellarWets.Chapter4.SetLimitDistances
import RockafellarWets.Chapter4.HitAndMiss
import RockafellarWets.Chapter4.RationalHitAndMiss
import RockafellarWets.Chapter4.DistanceConvergence
import RockafellarWets.Chapter4.UniformApproximation
import RockafellarWets.Chapter4.ProjectionConvergence
import RockafellarWets.Chapter4.ConnectedLimits
import RockafellarWets.Chapter4.EscapeToHorizon
import RockafellarWets.Chapter4.SetLimitExamples
import RockafellarWets.Chapter4.HausdorffConvergence
import RockafellarWets.Chapter4.ConeLimits
import RockafellarWets.Chapter4.ConvexLimits
import RockafellarWets.Chapter4.ConvexInternalApproximation
import RockafellarWets.Chapter4.ConvexTruncations
import RockafellarWets.Chapter4.StarShapedLimits
import RockafellarWets.Chapter4.SetConvergenceCompactness
import RockafellarWets.Chapter4.ClusterLimits
import RockafellarWets.Chapter4.HorizonLimits
import RockafellarWets.Chapter4.HorizonConeLimits
import RockafellarWets.Chapter4.HorizonLimitSubsequences
import RockafellarWets.Chapter4.MixedCosmicLimits
import RockafellarWets.Chapter4.EventuallyBounded
import RockafellarWets.Chapter4.TotalConvergence
import RockafellarWets.Chapter4.TotalConvergenceAutomatic
import RockafellarWets.Chapter4.TotalConvergenceAutomaticCompletion
import RockafellarWets.Chapter4.ImageLimits
import RockafellarWets.Chapter4.TotalImageEventuallyBounded
import RockafellarWets.Chapter4.TotalLinearImages
import RockafellarWets.Chapter4.OrthogonalProjections
import RockafellarWets.Chapter4.Products
import RockafellarWets.Chapter4.TotalProducts
import RockafellarWets.Chapter4.FiniteSums
import RockafellarWets.Chapter4.FiniteSumConvergence
import RockafellarWets.Chapter4.ConvexHullConvergence
import RockafellarWets.Chapter4.ConvexHullTotalConvergence
import RockafellarWets.Chapter4.FiniteUnions
import RockafellarWets.Chapter4.UnionConvergence
import RockafellarWets.Chapter4.ConvexSystems
import RockafellarWets.Chapter4.ConvexSystemConvergence
import RockafellarWets.Chapter4.ConvexIntersections
import RockafellarWets.Chapter4.OperationExamples
import RockafellarWets.Chapter4.DistanceFunctionRelations
import RockafellarWets.Chapter4.LocalSetDistances
import RockafellarWets.Chapter4.ConvexTruncationDistances
import RockafellarWets.Chapter4.PompeiuHausdorffProperties
import RockafellarWets.Chapter4.FiniteSetApproximation
import RockafellarWets.Chapter4.CosmicPointMetric
import RockafellarWets.Chapter4.CosmicSetMetric
import RockafellarWets.Chapter4.CosmicMetricCompletion
import RockafellarWets.Chapter4.TotalSetMetric
import RockafellarWets.Chapter4.TotalSetMetricCompletion
