/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Chapter 6: Polars of Polyhedral Cones and Farkas' Lemma

Lemma 6.45.  For a finite family `a : Fin m → E` the polar of the cone

  `K = {x | ⟪a i, x⟫ ≤ 0 for i = 1, …, m}`

is `con(pos{a 1, …, a m})`, the cone of all nonnegative combinations
`y 1 • a 1 + ⋯ + y m • a m`.  The sign convention for `polarCone` is the
nonpositive convention of Chapter 6.

Following the book's proof, the elementary half `J* = K` for
`J = conicHull (range a)` is checked on the generators, and the polar identity
itself then follows from closedness of a finitely generated cone (Theorem 3.52)
together with the bipolar theorem 6.20/6.21.  No separation argument is
reproved here.

The membership form is the usual Farkas alternative with ordinary finite
nonnegative multipliers: a vector pairs nonpositively with every solution of
the inequality system exactly when it is a nonnegative linear combination of
the normals `a i`.  No hypothesis of nonzero, distinct, or nonempty generators
is needed anywhere; the book discards zero vectors only as a proof convenience.
-/

import RockafellarWets.Chapter3.MinkowskiWeyl
import RockafellarWets.Chapter6.Polarity

open Set
open scoped InnerProductSpace

namespace RW

section Farkas

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
variable {m : ℕ}

/-! ## The elementary half of Lemma 6.45 -/

/-- The polar of a finite family of vectors is exactly the homogeneous
inequality system built from those vectors. -/
theorem polarCone_range (a : Fin m → E) :
    polarCone (Set.range a) = {x : E | ∀ i, ⟪a i, x⟫_ℝ ≤ 0} := by
  ext x
  simp only [mem_polarCone, Set.forall_mem_range, Set.mem_setOf_eq]
  exact forall_congr' fun i => by rw [real_inner_comm]

/-- `J* = K` for `J = con(pos{a 1, …, a m})`: the elementary inclusion checked
on generators in the proof of Lemma 6.45.  This is also the polar description
of an arbitrary finitely generated cone. -/
theorem polarCone_conicHull_range (a : Fin m → E) :
    polarCone (conicHull (Set.range a)) = {x : E | ∀ i, ⟪a i, x⟫_ℝ ≤ 0} := by
  rw [polarCone_conicHull, polarCone_range]

/-! ## Finite nonnegative multipliers -/

private theorem sum_smul_mem_conicHull {ι : Type*} {C : Set E} (s : Finset ι)
    {y : ι → ℝ} {v : ι → E} (hy : ∀ i, 0 ≤ y i) (hv : ∀ i, v i ∈ C) :
    (∑ i ∈ s, y i • v i) ∈ conicHull C :=
  Finset.sum_induction (fun i => y i • v i) (fun z => z ∈ conicHull C)
    (fun _ _ hz hw =>
      add_mem_of_convex_isCone (convex_conicHull C) (isCone_conicHull C) hz hw)
    (zero_mem_conicHull C)
    (fun i _ => (isCone_conicHull C).smul_mem (subset_conicHull (hv i)) (hy i))

/-- The cone generated by a finite family is the set of nonnegative
combinations of that family, with multipliers indexed by `Fin m`.  Zero
generators and repeated generators are allowed. -/
theorem conicHull_range_eq (a : Fin m → E) :
    conicHull (Set.range a) =
      {x : E | ∃ y : Fin m → ℝ, (∀ i, 0 ≤ y i) ∧ (∑ i, y i • a i) = x} := by
  apply Set.Subset.antisymm
  · refine conicHull_minimal ?_ ?_ ?_
    · rintro x ⟨y, hy, rfl⟩ z ⟨w, hw, rfl⟩ s t hs ht _
      refine ⟨fun i => s * y i + t * w i,
        fun i => add_nonneg (mul_nonneg hs (hy i)) (mul_nonneg ht (hw i)), ?_⟩
      rw [Finset.smul_sum, Finset.smul_sum, ← Finset.sum_add_distrib]
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [add_smul, smul_smul, smul_smul]
    · refine ⟨⟨fun _ => 0, fun _ => le_rfl, by simp⟩, ?_⟩
      rintro x ⟨y, hy, rfl⟩ c hc
      refine ⟨fun i => c * y i, fun i => mul_nonneg hc.le (hy i), ?_⟩
      rw [Finset.smul_sum]
      exact Finset.sum_congr rfl fun i _ => by rw [smul_smul]
    · rintro _ ⟨i, rfl⟩
      refine ⟨fun j => if j = i then 1 else 0, fun j => ?_, ?_⟩
      · by_cases h : j = i <;> simp [h]
      · simp
  · rintro x ⟨y, hy, rfl⟩
    exact sum_smul_mem_conicHull _ hy fun i => Set.mem_range_self i

/-- Membership in the generated cone through ordinary finite nonnegative
multipliers. -/
theorem mem_conicHull_range_iff {a : Fin m → E} {x : E} :
    x ∈ conicHull (Set.range a) ↔
      ∃ y : Fin m → ℝ, (∀ i, 0 ≤ y i) ∧ (∑ i, y i • a i) = x := by
  rw [conicHull_range_eq]
  exact Iff.rfl

/-! ## Finite generation and closedness of the generated cone -/

omit [NormedAddCommGroup E] [InnerProductSpace ℝ E] in
theorem coe_finset_image_univ_eq_range [DecidableEq E] (a : Fin m → E) :
    (↑(Finset.univ.image a) : Set E) = Set.range a := by
  simp

theorem isFinitelyGeneratedCone_conicHull_range (a : Fin m → E) :
    IsFinitelyGeneratedCone (conicHull (Set.range a)) := by
  classical
  exact ⟨Finset.univ.image a, by rw [coe_finset_image_univ_eq_range]⟩

/-- A cone generated by finitely many vectors is closed (Theorem 3.52); this is
the fact that makes the bipolar step of Lemma 6.45 legitimate. -/
theorem isClosed_conicHull_range [FiniteDimensional ℝ E] (a : Fin m → E) :
    IsClosed (conicHull (Set.range a)) := by
  classical
  rw [← coe_finset_image_univ_eq_range a]
  exact isClosed_conicHull_finset _

/-! ## Lemma 6.45 -/

/-- **Lemma 6.45** (polars of polyhedral cones; Farkas).  The polar of a cone
of the form `K = {x | ⟪a i, x⟫ ≤ 0 for i = 1, …, m}` is `con(pos{a 1, …, a m})`.

There are no hypotheses on the family `a`: the index set may be empty and the
vectors may vanish or repeat. -/
theorem polarCone_setOf_inner_nonpos_eq_conicHull_range [FiniteDimensional ℝ E]
    (a : Fin m → E) :
    polarCone {x : E | ∀ i, ⟪a i, x⟫_ℝ ≤ 0} = conicHull (Set.range a) := by
  rw [← polarCone_conicHull_range a]
  exact polarCone_bipolar_eq_self (isClosed_conicHull_range a)
    (convex_conicHull _) (isCone_conicHull _)

/-- Lemma 6.45 with the generators presented as a finite set. -/
theorem polarCone_setOf_inner_nonpos_eq_conicHull_image [FiniteDimensional ℝ E]
    [DecidableEq E] (a : Fin m → E) :
    polarCone {x : E | ∀ i, ⟪a i, x⟫_ℝ ≤ 0} =
      conicHull (↑(Finset.univ.image a) : Set E) := by
  rw [coe_finset_image_univ_eq_range,
    polarCone_setOf_inner_nonpos_eq_conicHull_range]

/-- **Lemma 6.45**, membership form: `v` belongs to the polar of the
inequality cone exactly when `v = y 1 • a 1 + ⋯ + y m • a m` for some
multipliers `y i ≥ 0`. -/
theorem mem_polarCone_setOf_inner_nonpos_iff [FiniteDimensional ℝ E]
    {a : Fin m → E} {v : E} :
    v ∈ polarCone {x : E | ∀ i, ⟪a i, x⟫_ℝ ≤ 0} ↔
      ∃ y : Fin m → ℝ, (∀ i, 0 ≤ y i) ∧ (∑ i, y i • a i) = v := by
  rw [polarCone_setOf_inner_nonpos_eq_conicHull_range, mem_conicHull_range_iff]

/-- **Farkas' lemma**, stated without reference to polarity: `v` pairs
nonpositively with every solution of the homogeneous system `⟪a i, x⟫ ≤ 0`
if and only if `v` is a nonnegative linear combination of the normals `a i`. -/
theorem forall_inner_nonpos_iff_exists_nonneg_multipliers [FiniteDimensional ℝ E]
    {a : Fin m → E} {v : E} :
    (∀ x : E, (∀ i, ⟪a i, x⟫_ℝ ≤ 0) → ⟪v, x⟫_ℝ ≤ 0) ↔
      ∃ y : Fin m → ℝ, (∀ i, 0 ≤ y i) ∧ (∑ i, y i • a i) = v :=
  mem_polarCone_setOf_inner_nonpos_iff

/-! ## Structural corollaries

The two sides of Lemma 6.45 are the `H` and `V` descriptions of Chapter 3, so
polarity exchanges them. -/

/-- The inequality cone of Lemma 6.45 written as a Chapter 3 homogeneous
linear inequality system, through the continuous functionals `innerSL ℝ (a i)`. -/
theorem homogeneousLinearInequalitySet_innerSL (a : Fin m → E) :
    homogeneousLinearInequalitySet (fun i => innerSL ℝ (a i)) =
      {x : E | ∀ i, ⟪a i, x⟫_ℝ ≤ 0} := by
  ext x
  simp [mem_homogeneousLinearInequalitySet]

/-- The cone `K` of Lemma 6.45 is `H`-polyhedral. -/
theorem isHPolyhedralCone_setOf_inner_nonpos (a : Fin m → E) :
    IsHPolyhedralCone {x : E | ∀ i, ⟪a i, x⟫_ℝ ≤ 0} := by
  rw [← homogeneousLinearInequalitySet_innerSL a]
  exact IsHPolyhedralCone.homogeneousLinearInequalitySet _

/-- The polar of the `H`-polyhedral cone of Lemma 6.45 is finitely
generated. -/
theorem isFinitelyGeneratedCone_polarCone_setOf_inner_nonpos
    [FiniteDimensional ℝ E] (a : Fin m → E) :
    IsFinitelyGeneratedCone (polarCone {x : E | ∀ i, ⟪a i, x⟫_ℝ ≤ 0}) := by
  rw [polarCone_setOf_inner_nonpos_eq_conicHull_range]
  exact isFinitelyGeneratedCone_conicHull_range a

/-- The polar of the `H`-polyhedral cone of Lemma 6.45 is closed. -/
theorem isClosed_polarCone_setOf_inner_nonpos [FiniteDimensional ℝ E]
    (a : Fin m → E) :
    IsClosed (polarCone {x : E | ∀ i, ⟪a i, x⟫_ℝ ≤ 0}) := by
  rw [polarCone_setOf_inner_nonpos_eq_conicHull_range]
  exact isClosed_conicHull_range a

/-- A finitely generated cone is generated by a family indexed by some
`Fin n`. -/
theorem IsFinitelyGeneratedCone.exists_range_generators {K : Set E}
    (hK : IsFinitelyGeneratedCone K) :
    ∃ (n : ℕ) (a : Fin n → E), K = conicHull (Set.range a) := by
  obtain ⟨s, hs⟩ := hK
  obtain ⟨n, f, _, hf⟩ := s.finite_toSet.fin_param
  exact ⟨n, f, by rw [hs, hf]⟩

/-- Conversely to Lemma 6.45: the polar of a finitely generated cone is
described by the displayed homogeneous finite inequality system in its
generators. -/
theorem IsFinitelyGeneratedCone.exists_polarCone_setOf_inner_nonpos {K : Set E}
    (hK : IsFinitelyGeneratedCone K) :
    ∃ (n : ℕ) (a : Fin n → E),
      K = conicHull (Set.range a) ∧
        polarCone K = {x : E | ∀ i, ⟪a i, x⟫_ℝ ≤ 0} := by
  obtain ⟨n, a, hKa⟩ := hK.exists_range_generators
  exact ⟨n, a, hKa, by rw [hKa, polarCone_conicHull_range]⟩

/-- The polar of a finitely generated cone is `H`-polyhedral. -/
theorem IsFinitelyGeneratedCone.isHPolyhedralCone_polarCone {K : Set E}
    (hK : IsFinitelyGeneratedCone K) : IsHPolyhedralCone (polarCone K) := by
  obtain ⟨n, a, _, hpolar⟩ := hK.exists_polarCone_setOf_inner_nonpos
  rw [hpolar]
  exact isHPolyhedralCone_setOf_inner_nonpos a

/-- The polar of a finitely generated cone is again finitely generated. -/
theorem IsFinitelyGeneratedCone.isFinitelyGeneratedCone_polarCone
    [FiniteDimensional ℝ E] {K : Set E} (hK : IsFinitelyGeneratedCone K) :
    IsFinitelyGeneratedCone (polarCone K) :=
  hK.isHPolyhedralCone_polarCone.isFinitelyGeneratedCone

/-- The polar of an `H`-polyhedral cone is finitely generated: this is
Lemma 6.45 stated for an arbitrary `H`-description. -/
theorem IsHPolyhedralCone.isFinitelyGeneratedCone_polarCone
    [FiniteDimensional ℝ E] {K : Set E} (hK : IsHPolyhedralCone K) :
    IsFinitelyGeneratedCone (polarCone K) :=
  hK.isFinitelyGeneratedCone.isFinitelyGeneratedCone_polarCone

/-- The polar of an `H`-polyhedral cone is again `H`-polyhedral. -/
theorem IsHPolyhedralCone.isHPolyhedralCone_polarCone [FiniteDimensional ℝ E]
    {K : Set E} (hK : IsHPolyhedralCone K) :
    IsHPolyhedralCone (polarCone K) :=
  hK.isFinitelyGeneratedCone.isHPolyhedralCone_polarCone

section Complete

variable [CompleteSpace E]

/-- In an inner product space every `H`-polyhedral cone has exactly the form
displayed in Lemma 6.45, by the Riesz representation of the defining
functionals. -/
theorem IsHPolyhedralCone.exists_inner_representation {K : Set E}
    (hK : IsHPolyhedralCone K) :
    ∃ (n : ℕ) (a : Fin n → E), K = {x : E | ∀ i, ⟪a i, x⟫_ℝ ≤ 0} := by
  obtain ⟨n, A, rfl⟩ := hK
  refine ⟨n, fun i => (InnerProductSpace.toDual ℝ E).symm (A i), ?_⟩
  ext x
  simp [mem_homogeneousLinearInequalitySet]

/-- Lemma 6.45 for an arbitrary `H`-polyhedral cone: it is the solution set of
a finite system `⟪a i, x⟫ ≤ 0` and its polar is the cone generated by the
`a i`. -/
theorem IsHPolyhedralCone.exists_polarCone_eq_conicHull_range
    [FiniteDimensional ℝ E] {K : Set E} (hK : IsHPolyhedralCone K) :
    ∃ (n : ℕ) (a : Fin n → E),
      K = {x : E | ∀ i, ⟪a i, x⟫_ℝ ≤ 0} ∧
        polarCone K = conicHull (Set.range a) := by
  obtain ⟨n, a, hKa⟩ := hK.exists_inner_representation
  exact ⟨n, a, hKa, by
    rw [hKa, polarCone_setOf_inner_nonpos_eq_conicHull_range]⟩

end Complete

end Farkas

end RW
