/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Chapter 5: The Introductory Examples of Section A

Examples 5.1, 5.2 and 5.3 open the chapter.  None of them states a theorem:
each sets up a class of set-valued mappings and identifies the sets that the
rest of the chapter will study.  What is formalized here is exactly those
identifications, so that the objects the book names informally have a
definition and the equalities it asserts in passing are proved.

The file comes last in the import order rather than first, because the
identifications are stated with machinery that later sections introduce --
`svRestrict` and `svSingleton` from the paragraphs around 5.20 and 5.21, and
`svComp` from 5.52.  That is the point: the book's `S(x) = {F(x)}` for
`x ∈ X` and `∅` elsewhere is `svRestrict (svSingleton F) X`, and no new
definition is needed for it.

* **5.1** is about that mapping.  Its domain is `X`, its values are never
  multivalued, its inverse is the solution set `{x ∈ X | F(x) = u}` of the
  book's equation system, and its set-valued preimage is `X ∩ F⁻¹(D)`, which
  at a box `D = D₁ × ⋯ × Dₘ` is the constraint system
  `{x ∈ X | fᵢ(x) ∈ Dᵢ}`.  The book's "hopes rise that `F⁻¹` might be
  single-valued" is settled exactly: the inverse is everywhere subsingleton
  iff `F` is injective on `X`.  Coordinates are carried by an arbitrary index
  type and a dependent family, so `m = n` plays no role.
* **5.2** introduces the implicit mapping `T(w) = {x | S(x, w) ∋ ū}`, defined
  here as `svImplicit`, together with the special case
  `T(w) = {x | -F(x, w) ∈ N(x)}` that comes from `S(x, w) = F(x, w) + N(x)`.
  The operations paragraph that follows 5.2 is covered too, in the two parts
  not already in `MappingOperations.lean`: the union and inverse-image
  descriptions of `T ∘ S`, the identity `(T ∘ S)⁻¹ = S⁻¹ ∘ T⁻¹`, and the
  reduction of the composition to the ordinary one on single-valued mappings.
* **5.3** defines fixed points and the iterates `S ∘ ⋯ ∘ S`, and proves the
  inclusion the book displays: a sequence generated by `xν ∈ S(xν₋₁)` from
  `x⁰` has `xν ∈ (S ∘ ⋯ ∘ S)(x⁰)`.  Two convergence statements are added, as
  the point the example is making -- the book says immediately afterwards
  that this framework is what makes the continuity notions, *and* the
  convergence of a sequence of mappings, matter.  A limit of an iteration is
  a fixed point as soon as `S` is osc there; and for a sequence of
  algorithmic mappings `Tν` the limit is a fixed point of any `S` dominating
  their graphical outer limit, which is the hypothesis 5.37(a) runs on.
-/

import RockafellarWets.Chapter5.MappingOperations
import RockafellarWets.Chapter5.GraphicalLimits

open Filter Set Topology

open scoped Pointwise

namespace RW

section ConstraintSystems

variable {E G : Type*}

/-- **Example 5.1**: the mapping `S(x) = {F(x)}` on `X` and `∅` elsewhere,
introduced in the paragraph preceding the example, has `dom S = X`. -/
theorem svDom_svRestrict_svSingleton (F : E → G) (X : Set E) :
    svDom (svRestrict (svSingleton F) X) = X := by
  ext x
  simp only [svDom, mem_setOf_eq]
  exact ⟨fun ⟨_, _, hx⟩ ↦ hx, fun hx ↦ ⟨F x, rfl, hx⟩⟩

/-- The book's remark that this `S` "isn't multivalued anywhere", even though
it is not single-valued either, being empty off `X`. -/
theorem subsingleton_svRestrict_svSingleton (F : E → G) (X : Set E) (x : E) :
    (svRestrict (svSingleton F) X x).Subsingleton := by
  rintro u ⟨hu, -⟩ v ⟨hv, -⟩
  rw [mem_svSingleton.1 hu, mem_svSingleton.1 hv]

/-- **Example 5.1**: `F⁻¹(u)` is the solution set of the book's equation
system `fᵢ(x) = uᵢ` with `x ∈ X`. -/
theorem svInv_svRestrict_svSingleton (F : E → G) (X : Set E) (u : G) :
    svInv (svRestrict (svSingleton F) X) u = {x ∈ X | F x = u} := by
  ext x
  simp only [svInv, mem_setOf_eq, mem_svRestrict, mem_svSingleton]
  exact ⟨fun ⟨h1, h2⟩ ↦ ⟨h2, h1.symm⟩, fun ⟨h1, h2⟩ ↦ ⟨h2.symm, h1⟩⟩

/-- The set-valued preimage of this `S` is the ordinary preimage cut down to
`X`.  The book's constraint system is the case of a box. -/
theorem svPreimage_svRestrict_svSingleton (F : E → G) (X : Set E) (D : Set G) :
    svPreimage (svRestrict (svSingleton F) X) D = X ∩ F ⁻¹' D := by
  ext x
  simp only [mem_svPreimage, mem_inter_iff, mem_preimage]
  constructor
  · rintro ⟨v, ⟨hv, hxX⟩, hvD⟩
    exact ⟨hxX, mem_svSingleton.1 hv ▸ hvD⟩
  · rintro ⟨hxX, hxD⟩
    exact ⟨F x, ⟨rfl, hxX⟩, hxD⟩

/-- **Example 5.1**, the closing sentence of the preceding paragraph: the
range of the inverse is `X`. -/
theorem svRange_svInv_svRestrict_svSingleton (F : E → G) (X : Set E) :
    svRange (svInv (svRestrict (svSingleton F) X)) = X :=
  svDom_svRestrict_svSingleton F X

/-- **Example 5.1**, the question raised when the number of equations matches
the number of unknowns: `F⁻¹` is single-valued wherever it is defined exactly
when `F` is injective on `X`.  Equality of the two dimensions is neither
sufficient nor necessary for this, and plays no role. -/
theorem subsingleton_svInv_svRestrict_svSingleton_iff (F : E → G) (X : Set E) :
    (∀ u, (svInv (svRestrict (svSingleton F) X) u).Subsingleton) ↔ InjOn F X := by
  simp only [svInv_svRestrict_svSingleton]
  constructor
  · intro h x hx y hy hxy
    exact h (F x) ⟨hx, rfl⟩ ⟨hy, hxy.symm⟩
  · rintro h u x ⟨hx, hxu⟩ y ⟨hy, hyu⟩
    exact h hx hy (hxu.trans hyu.symm)

end ConstraintSystems

section Coordinates

variable {E ι : Type*} {G : ι → Type*}

/-- **Example 5.1** in coordinates: the equation system
`fᵢ(x₁, …, xₙ) = uᵢ` for `i = 1, …, m` with `x ∈ X`. -/
theorem svInv_svRestrict_svSingleton_pi (f : ∀ i, E → G i) (X : Set E)
    (u : ∀ i, G i) :
    svInv (svRestrict (svSingleton fun x i ↦ f i x) X) u
      = {x ∈ X | ∀ i, f i x = u i} := by
  rw [svInv_svRestrict_svSingleton]
  ext x
  simp only [mem_sep_iff, funext_iff]

/-- **Example 5.1** in coordinates: at a box `D = D₁ × ⋯ × Dₘ` the set-valued
preimage is the constraint system `fᵢ(x₁, …, xₙ) ∈ Dᵢ` with `x ∈ X`. -/
theorem svPreimage_svRestrict_svSingleton_pi (f : ∀ i, E → G i) (X : Set E)
    (D : ∀ i, Set (G i)) :
    svPreimage (svRestrict (svSingleton fun x i ↦ f i x) X) (univ.pi D)
      = {x ∈ X | ∀ i, f i x ∈ D i} := by
  rw [svPreimage_svRestrict_svSingleton]
  ext x
  simp only [mem_inter_iff, mem_preimage, mem_univ_pi, mem_sep_iff]

end Coordinates

section ImplicitMappings

variable {E W G : Type*}

/-- **Example 5.2**: the implicit mapping `T(w) = {x | S(x, w) ∋ ū}` of a
parameterized generalized equation. -/
def svImplicit (S : E × W → Set G) (u : G) : W → Set E :=
  fun w ↦ {x | u ∈ S (x, w)}

@[simp]
theorem mem_svImplicit {S : E × W → Set G} {u : G} {w : W} {x : E} :
    x ∈ svImplicit S u w ↔ u ∈ S (x, w) := Iff.rfl

/-- **Example 5.2**, the unparameterized case read inside the parameterized
one: at a fixed `w` the solution set of `S(x, w) ∋ ū` is the inverse image of
`ū` under the fibre of `S`.  With no parameter at all this is the example's
first sentence, that the solution set of `S(x̄) ∋ ū` is `S⁻¹(ū)`. -/
theorem svImplicit_eq_svInv (S : E × W → Set G) (u : G) (w : W) :
    svImplicit S u w = svInv (fun x ↦ S (x, w)) u := rfl

/-- The graph of the implicit mapping is the `ū`-level set of `S`, with the
two coordinates exchanged. -/
theorem svGraph_svImplicit (S : E × W → Set G) (u : G) :
    svGraph (svImplicit S u) = {q : W × E | u ∈ S (q.2, q.1)} := rfl

/-- **Example 5.2**, the special case it singles out: for `S(x, w)` of the
form `F(x, w) + N(x)`, the generalized equation `S(x, w) ∋ 0` is
`-F(x, w) ∈ N(x)`. -/
theorem svImplicit_singleton_add [AddGroup G] (Φ : E × W → G) (N : E → Set G)
    (w : W) :
    svImplicit (fun p ↦ {Φ p} + N p.1) 0 w = {x | -Φ (x, w) ∈ N x} := by
  ext x
  simp only [mem_svImplicit, mem_setOf_eq, Set.mem_add, mem_singleton_iff]
  constructor
  · rintro ⟨a, rfl, b, hb, hab⟩
    rwa [neg_eq_of_add_eq_zero_right hab]
  · intro h
    exact ⟨Φ (x, w), rfl, -Φ (x, w), h, add_neg_cancel _⟩

end ImplicitMappings

section CompositionIdentities

variable {E F G : Type*}

/-- The first of the two descriptions of `T ∘ S` in the operations paragraph
following 5.2. -/
theorem svComp_eq_iUnion (T : F → Set G) (S : E → Set F) (x : E) :
    svComp T S x = ⋃ w ∈ S x, T w := by
  ext u
  simp only [mem_svComp, mem_iUnion₂, exists_prop]

/-- The second description in that paragraph, `(T ∘ S)(x) = {w | S(x) ∩
T⁻¹(w) ≠ ∅}`.  It is the auxiliary mapping of 5.52(b) read at a point. -/
theorem svComp_eq_setOf_inter_nonempty (T : F → Set G) (S : E → Set F) (x : E) :
    svComp T S x = {v | (S x ∩ svInv T v).Nonempty} := by
  ext v
  simp only [mem_svComp, mem_setOf_eq, Set.inter_nonempty]
  exact ⟨fun ⟨w, hw, hv⟩ ↦ ⟨w, hw, hv⟩, fun ⟨w, hw, hv⟩ ↦ ⟨w, hw, hv⟩⟩

/-- The paragraph's closing identity `(T ∘ S)⁻¹ = S⁻¹ ∘ T⁻¹`. -/
theorem svInv_svComp (T : F → Set G) (S : E → Set F) :
    svInv (svComp T S) = svComp (svInv S) (svInv T) := by
  ext v x
  simp only [svInv, mem_setOf_eq, mem_svComp]
  exact ⟨fun ⟨w, hw, hv⟩ ↦ ⟨w, hv, hw⟩, fun ⟨w, hv, hw⟩ ↦ ⟨w, hw, hv⟩⟩

/-- The paragraph's remark that on single-valued mappings the composition
reduces to the usual one. -/
theorem svComp_svSingleton (g : F → G) (f : E → F) :
    svComp (svSingleton g) (svSingleton f) = svSingleton (g ∘ f) := by
  ext x u
  simp only [mem_svComp, mem_svSingleton, Function.comp_apply]
  exact ⟨fun ⟨w, hw, hu⟩ ↦ by rw [hu, hw], fun hu ↦ ⟨f x, rfl, hu⟩⟩

end CompositionIdentities

section AlgorithmicMappings

variable {E : Type*}

/-- **Example 5.3**: a *fixed point* of `S` is a point with `x̄ ∈ S(x̄)`. -/
def svFixedPoints (S : E → Set E) : Set E := {x | x ∈ S x}

@[simp]
theorem mem_svFixedPoints {S : E → Set E} {x : E} :
    x ∈ svFixedPoints S ↔ x ∈ S x := Iff.rfl

/-- **Example 5.3**: the `ν`-fold composition `S ∘ ⋯ ∘ S`, with `S⁰(x) = {x}`
so that `S¹ = S`. -/
def svIterate (S : E → Set E) : ℕ → E → Set E
  | 0 => svSingleton id
  | n + 1 => svComp S (svIterate S n)

@[simp]
theorem svIterate_zero (S : E → Set E) : svIterate S 0 = svSingleton id := rfl

@[simp]
theorem svIterate_succ (S : E → Set E) (n : ℕ) :
    svIterate S (n + 1) = svComp S (svIterate S n) := rfl

theorem svIterate_one (S : E → Set E) : svIterate S 1 = S := by
  ext x u
  simp only [svIterate_succ, svIterate_zero, mem_svComp, mem_svSingleton, id_eq]
  exact ⟨fun ⟨w, hw, hu⟩ ↦ hw ▸ hu, fun hu ↦ ⟨x, rfl, hu⟩⟩

/-- **Example 5.3**, the displayed inclusion: a sequence generated from `x⁰`
by the rule `xν ∈ S(xν₋₁)` has `xν ∈ (S ∘ ⋯ ∘ S)(x⁰)` with `ν` copies of
`S`. -/
theorem mem_svIterate_of_forall_mem {S : E → Set E} {x : ℕ → E}
    (h : ∀ n, x (n + 1) ∈ S (x n)) (n : ℕ) : x n ∈ svIterate S n (x 0) := by
  induction n with
  | zero => exact rfl
  | succ k ih => exact mem_svComp.2 ⟨x k, ih, h k⟩

/-- A fixed point is a stationary point of the iteration: it lies in every
iterate of itself, being the value of the constant generated sequence. -/
theorem mem_svIterate_of_mem_svFixedPoints {S : E → Set E} {x : E}
    (hx : x ∈ svFixedPoints S) (n : ℕ) : x ∈ svIterate S n x :=
  mem_svIterate_of_forall_mem (x := fun _ ↦ x) (fun _ ↦ hx) n

end AlgorithmicMappings

section AlgorithmicLimits

variable {E : Type*} [TopologicalSpace E]

/-- **Example 5.3**, why continuity is the concern it announces: if a
sequence generated by `xν ∈ S(xν₋₁)` converges, and `S` is osc at the limit,
the limit is a fixed point.

The pairs `(xν, xν₊₁)` put the limit in its own outer limit `5(1)`: any
neighborhood of the limit contains some `xν`, and the *next* term, which
lies in `S(xν)`, is in any prescribed neighborhood as well. -/
theorem mem_svFixedPoints_of_tendsto {S : E → Set E} {x : ℕ → E} {z : E}
    (h : ∀ n, x (n + 1) ∈ S (x n)) (hx : Tendsto x atTop (nhds z))
    (hosc : SvOscAt S z) : z ∈ svFixedPoints S := by
  refine hosc fun V hV ↦ ?_
  rw [Filter.frequently_iff]
  intro U hU
  have h1 : ∀ᶠ n in atTop, x n ∈ U := hx hU
  have h2 : ∀ᶠ n in atTop, x (n + 1) ∈ V := hx.comp (tendsto_add_atTop_nat 1) hV
  obtain ⟨n, hnU, hnV⟩ := (h1.and h2).exists
  exact ⟨x n, hnU, x (n + 1), h n, hnV⟩

end AlgorithmicLimits

section AlgorithmicGraphicalLimits

variable {E : Type*} [PseudoMetricSpace E]

/-- **Example 5.3** with algorithmic mappings: a convergent sequence
generated by `xν ∈ Tν(xν₋₁)` puts its limit in the graphical outer limit of
the `Tν` at that limit.

The witnessing data of 5.32 is the shifted index `ν ↦ ν + 1` with the pairs
`(xν, xν₊₁)`, both coordinates converging to the same point. -/
theorem mem_graphicalOuterLimit_of_tendsto {Sseq : ℕ → E → Set E} {x : ℕ → E}
    {z : E} (h : ∀ n, x (n + 1) ∈ Sseq (n + 1) (x n))
    (hx : Tendsto x atTop (nhds z)) : z ∈ graphicalOuterLimit Sseq z :=
  mem_graphicalOuterLimit_iff.2
    ⟨fun n ↦ n + 1, x, fun n ↦ x (n + 1), fun _ _ hab ↦ Nat.succ_lt_succ hab, h,
      hx, hx.comp (tendsto_add_atTop_nat 1)⟩

/-- **Example 5.3**, why the convergence of a *sequence* of mappings is the
other concern it announces: the limit of a sequence generated by algorithmic
mappings `Tν` is a fixed point of any `S` that contains their graphical outer
limit -- the hypothesis 5.37(a) is stated with. -/
theorem mem_svFixedPoints_of_graphicalOuterLimit {Sseq : ℕ → E → Set E}
    {S : E → Set E} (hlim : ∀ y, graphicalOuterLimit Sseq y ⊆ S y) {x : ℕ → E}
    {z : E} (h : ∀ n, x (n + 1) ∈ Sseq (n + 1) (x n))
    (hx : Tendsto x atTop (nhds z)) : z ∈ svFixedPoints S :=
  hlim z (mem_graphicalOuterLimit_of_tendsto h hx)

end AlgorithmicGraphicalLimits

end RW
