/- 
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Chapter 3A/F*: Cosmic Closure in the Ray-Space Model

This file formalizes the ray-space representation used throughout Chapter 3:
- Exercise 3.4: the cosmic closedness criterion in ray-space form
- Definition 3.41 / Exercise 3.42: cosmic convexity via the corresponding cone
- Exercise 3.44: the convex hull of a cosmic set in ray-space form
- Proposition 3.45 and Corollary 3.46
-/

import RockafellarWets.Chapter3.PointedCones
import RockafellarWets.Chapter3.SetOperations
import RockafellarWets.Chapter2.Separation
import Mathlib.Order.OrderIsoNat
import Mathlib.Topology.MetricSpace.Sequences

open Set Filter Topology
open scoped Pointwise

namespace RW

section RaySpace

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- The ordinary-point part of the ray-space model: the cone generated by the
slice `(x, -1)` with `x ∈ C`. -/
def ordinaryRayCone (C : Set E) : Set (E × ℝ) :=
  {p | ∃ x ∈ C, ∃ a : ℝ, 0 < a ∧ p = (a • x, -a)}

/-- The cone in the ray-space model corresponding to the cosmic set
`C ∪ dir K`. -/
def raySpaceCone (C K : Set E) : Set (E × ℝ) :=
  ordinaryRayCone C ∪ (K ×ˢ ({0} : Set ℝ))

@[simp] theorem ordinaryRayCone_empty :
    ordinaryRayCone (∅ : Set E) = ∅ := by
  ext p
  simp [ordinaryRayCone]

@[simp] theorem raySpaceCone_empty_empty :
    raySpaceCone (∅ : Set E) (∅ : Set E) = ∅ := by
  simp [raySpaceCone]

theorem mem_ordinaryRayCone {C : Set E} {p : E × ℝ} :
    p ∈ ordinaryRayCone C ↔ ∃ x ∈ C, ∃ a : ℝ, 0 < a ∧ p = (a • x, -a) := by
  rfl

theorem ordinaryRayCone_mono {C D : Set E} (hCD : C ⊆ D) :
    ordinaryRayCone C ⊆ ordinaryRayCone D := by
  rintro p ⟨x, hx, a, ha, rfl⟩
  exact ⟨x, hCD hx, a, ha, rfl⟩

theorem snd_lt_zero_of_mem_ordinaryRayCone {C : Set E} {p : E × ℝ}
    (hp : p ∈ ordinaryRayCone C) :
    p.2 < 0 := by
  rcases hp with ⟨x, hx, a, ha, hEq⟩
  have hneg : (-(a : ℝ)) < 0 := by
    linarith
  simpa [hEq] using hneg

theorem mem_ordinaryRayCone_neg_one_iff {C : Set E} {x : E} :
    (x, -1) ∈ ordinaryRayCone C ↔ x ∈ C := by
  constructor
  · rintro ⟨y, hy, a, ha, hEq⟩
    have ha1 : a = 1 := by
      have hsnd : (-1 : ℝ) = -a := by
        simpa using congrArg Prod.snd hEq
      linarith
    have hxy : x = y := by
      simpa [ha1] using congrArg Prod.fst hEq
    simpa [hxy] using hy
  · intro hx
    exact ⟨x, hx, 1, by norm_num, by simp⟩

theorem mem_ordinaryRayCone_zero_iff {C : Set E} {x : E} :
    (x, 0) ∈ ordinaryRayCone C ↔ False := by
  constructor
  · intro hx
    have hlt := snd_lt_zero_of_mem_ordinaryRayCone hx
    simp at hlt
  · intro h
    exact False.elim h

theorem ordinaryRayCone_eq_empty_iff {C : Set E} :
    ordinaryRayCone C = ∅ ↔ C = ∅ := by
  constructor
  · intro h
    ext x
    constructor
    · intro hx
      have hxOrd : (x, -1) ∈ ordinaryRayCone C :=
        (mem_ordinaryRayCone_neg_one_iff).2 hx
      simp [h] at hxOrd
    · intro hx
      simp at hx
  · intro h
    simp [h]

theorem ordinaryRayCone_nonempty_iff {C : Set E} :
    (ordinaryRayCone C).Nonempty ↔ C.Nonempty := by
  constructor
  · rintro ⟨p, hp⟩
    rcases hp with ⟨x, hx, a, ha, hEq⟩
    exact ⟨x, hx⟩
  · rintro ⟨x, hx⟩
    exact ⟨(x, -1), (mem_ordinaryRayCone_neg_one_iff).2 hx⟩

theorem ordinaryRayCone_inter {C D : Set E} :
    ordinaryRayCone (C ∩ D) = ordinaryRayCone C ∩ ordinaryRayCone D := by
  ext p
  constructor
  · rintro ⟨x, hx, a, ha, rfl⟩
    exact ⟨⟨x, hx.1, a, ha, rfl⟩, ⟨x, hx.2, a, ha, rfl⟩⟩
  · rintro ⟨hpC, hpD⟩
    rcases hpC with ⟨x, hx, a, ha, hEq⟩
    rcases hpD with ⟨y, hy, b, hb, hEq'⟩
    have hpEq : (a • x, -a) = (b • y, -b) := by
      calc
        (a • x, -a) = p := hEq.symm
        _ = (b • y, -b) := hEq'
    have hab : a = b := by
      have hsnd : (-a : ℝ) = -b := by
        simpa using congrArg Prod.snd hpEq
      linarith
    have hxy : x = y := by
      have hfst : a • x = b • y := by
        simpa using congrArg Prod.fst hpEq
      subst hab
      have hsmul : a⁻¹ • (a • x) = a⁻¹ • (a • y) := by
        simpa using congrArg (fun z : E => a⁻¹ • z) hfst
      simpa [smul_smul, ha.ne', inv_mul_cancel₀, one_smul] using hsmul
    refine ⟨x, ⟨hx, hxy ▸ hy⟩, a, ha, hEq⟩

theorem raySpaceCone_inter {C D K L : Set E} :
    raySpaceCone C K ∩ raySpaceCone D L = raySpaceCone (C ∩ D) (K ∩ L) := by
  ext p
  constructor
  · rintro ⟨hp, hq⟩
    rcases hp with hpOrd | hpHor
    · rcases hq with hqOrd | hqHor
      · left
        rw [ordinaryRayCone_inter]
        exact ⟨hpOrd, hqOrd⟩
      · exfalso
        have hlt : p.2 < 0 := snd_lt_zero_of_mem_ordinaryRayCone hpOrd
        have hzero : p.2 = 0 := by
          simpa using hqHor.2
        linarith
    · rcases hq with hqOrd | hqHor
      · exfalso
        have hzero : p.2 = 0 := by
          simpa using hpHor.2
        have hlt : p.2 < 0 := snd_lt_zero_of_mem_ordinaryRayCone hqOrd
        linarith
      · exact Or.inr ⟨⟨hpHor.1, hqHor.1⟩, by simpa using hpHor.2⟩
  · rintro (hpOrd | hpHor)
    · refine ⟨Or.inl ?_, Or.inl ?_⟩
      · exact ordinaryRayCone_mono inter_subset_left hpOrd
      · exact ordinaryRayCone_mono inter_subset_right hpOrd
    · exact ⟨Or.inr ⟨hpHor.1.1, hpHor.2⟩, Or.inr ⟨hpHor.1.2, hpHor.2⟩⟩

/-- Ordinary ray points are included in the corresponding ray-space cone. -/
theorem ordinaryRayCone_subset_raySpaceCone (C K : Set E) :
    ordinaryRayCone C ⊆ raySpaceCone C K := by
  intro p hp
  exact Or.inl hp

/-- Direction-slice points are included in the corresponding ray-space cone. -/
theorem directionSlice_subset_raySpaceCone (C K : Set E) :
    K ×ˢ ({0} : Set ℝ) ⊆ raySpaceCone C K := by
  intro p hp
  exact Or.inr hp

/-- Ray-space cones are monotone in both ordinary and direction parts. -/
theorem raySpaceCone_mono {C D K L : Set E} (hCD : C ⊆ D) (hKL : K ⊆ L) :
    raySpaceCone C K ⊆ raySpaceCone D L := by
  intro p hp
  rcases hp with hpOrd | hpHor
  · exact Or.inl (ordinaryRayCone_mono hCD hpOrd)
  · exact Or.inr ⟨hKL hpHor.1, hpHor.2⟩

/-- A point of a ray-space cone has nonpositive height. -/
theorem snd_nonpos_of_mem_raySpaceCone {C K : Set E} {p : E × ℝ}
    (hp : p ∈ raySpaceCone C K) :
    p.2 ≤ 0 := by
  rcases hp with hpOrd | hpHor
  · exact le_of_lt (snd_lt_zero_of_mem_ordinaryRayCone hpOrd)
  · have hzero : p.2 = 0 := by simpa using hpHor.2
    exact le_of_eq hzero

theorem mem_raySpaceCone_zero_iff {C K : Set E} {x : E} :
    (x, 0) ∈ raySpaceCone C K ↔ x ∈ K := by
  constructor
  · rintro (hOrd | hHor)
    · rcases hOrd with ⟨y, hy, a, ha, hEq⟩
      have : a = 0 := by
        have hneg : -(a : ℝ) = 0 := by simpa using congrArg Prod.snd hEq
        linarith
      exact (ha.ne' this).elim
    · simpa using hHor.1
  · intro hx
    exact Or.inr ⟨hx, rfl⟩

theorem mem_raySpaceCone_neg_one_iff {C K : Set E} {x : E} :
    (x, -1) ∈ raySpaceCone C K ↔ x ∈ C := by
  constructor
  · rintro (hOrd | hHor)
    · rcases hOrd with ⟨y, hy, a, ha, hEq⟩
      have h1a : (1 : ℝ) = a := by
        simpa using congrArg Prod.snd hEq
      have ha1 : a = 1 := by
        linarith
      have hxy : x = y := by
        simpa [ha1] using congrArg Prod.fst hEq
      simpa [hxy] using hy
    · have : (0 : ℝ) = -1 := by simpa using hHor.2
      linarith
  · intro hx
    exact Or.inl ⟨x, hx, 1, by norm_num, by simp⟩

/-- A ray-space cone is empty exactly when both its ordinary and direction
parts are empty. -/
theorem raySpaceCone_eq_empty_iff {C K : Set E} :
    raySpaceCone C K = ∅ ↔ C = ∅ ∧ K = ∅ := by
  constructor
  · intro h
    refine ⟨?_, ?_⟩
    · ext x
      constructor
      · intro hx
        have hxRay : (x, -1) ∈ raySpaceCone C K :=
          (mem_raySpaceCone_neg_one_iff).2 hx
        simp [h] at hxRay
      · intro hx
        simp at hx
    · ext x
      constructor
      · intro hx
        have hxRay : (x, 0) ∈ raySpaceCone C K :=
          (mem_raySpaceCone_zero_iff).2 hx
        simp [h] at hxRay
      · intro hx
        simp at hx
  · rintro ⟨hC, hK⟩
    simp [hC, hK]

/-- A ray-space cone is nonempty exactly when either its ordinary or direction
part is nonempty. -/
theorem raySpaceCone_nonempty_iff {C K : Set E} :
    (raySpaceCone C K).Nonempty ↔ C.Nonempty ∨ K.Nonempty := by
  constructor
  · rintro ⟨p, hp⟩
    rcases hp with hpOrd | hpHor
    · rcases hpOrd with ⟨x, hx, a, ha, hEq⟩
      exact Or.inl ⟨x, hx⟩
    · exact Or.inr ⟨p.1, hpHor.1⟩
  · rintro (⟨x, hx⟩ | ⟨x, hx⟩)
    · exact ⟨(x, -1), (mem_raySpaceCone_neg_one_iff).2 hx⟩
    · exact ⟨(x, 0), (mem_raySpaceCone_zero_iff).2 hx⟩

/-- Negative-height ray-space points are exactly ordinary-ray points. -/
theorem mem_ordinaryRayCone_of_mem_raySpaceCone_of_snd_lt_zero
    {C K : Set E} {p : E × ℝ} (hp : p ∈ raySpaceCone C K)
    (hneg : p.2 < 0) :
    p ∈ ordinaryRayCone C := by
  rcases hp with hpOrd | hpHor
  · exact hpOrd
  · have hzero : p.2 = 0 := by simpa using hpHor.2
    linarith

/-- Negative-height membership in a ray-space cone is equivalent to membership
in the ordinary-ray part. -/
theorem mem_raySpaceCone_iff_of_snd_lt_zero
    {C K : Set E} {p : E × ℝ} (hneg : p.2 < 0) :
    p ∈ raySpaceCone C K ↔ p ∈ ordinaryRayCone C := by
  constructor
  · intro hp
    exact mem_ordinaryRayCone_of_mem_raySpaceCone_of_snd_lt_zero hp hneg
  · intro hp
    exact ordinaryRayCone_subset_raySpaceCone C K hp

/-- Zero-height ray-space points are exactly direction-slice points. -/
theorem fst_mem_of_mem_raySpaceCone_of_snd_eq_zero
    {C K : Set E} {p : E × ℝ} (hp : p ∈ raySpaceCone C K)
    (hzero : p.2 = 0) :
    p.1 ∈ K := by
  rcases p with ⟨x, t⟩
  change t = 0 at hzero
  subst hzero
  exact (mem_raySpaceCone_zero_iff).1 hp

/-- A zero-height point whose first coordinate is a direction belongs to the
ray-space cone. -/
theorem mem_raySpaceCone_of_fst_mem_of_snd_eq_zero
    {C K : Set E} {p : E × ℝ} (hpK : p.1 ∈ K) (hzero : p.2 = 0) :
    p ∈ raySpaceCone C K := by
  rcases p with ⟨x, t⟩
  change t = 0 at hzero
  subst hzero
  exact (mem_raySpaceCone_zero_iff).2 hpK

/-- Zero-height membership in a ray-space cone is equivalent to membership of
the first coordinate in the direction part. -/
theorem mem_raySpaceCone_iff_of_snd_eq_zero
    {C K : Set E} {p : E × ℝ} (hzero : p.2 = 0) :
    p ∈ raySpaceCone C K ↔ p.1 ∈ K := by
  constructor
  · intro hp
    exact fst_mem_of_mem_raySpaceCone_of_snd_eq_zero hp hzero
  · intro hp
    exact mem_raySpaceCone_of_fst_mem_of_snd_eq_zero hp hzero

theorem isCone_raySpaceCone {C K : Set E} (hK : IsCone K) :
    IsCone (raySpaceCone C K) := by
  refine ⟨Or.inr ⟨hK.1, rfl⟩, ?_⟩
  intro p hp c hc
  rcases hp with hOrd | hHor
  · rcases hOrd with ⟨x, hx, a, ha, rfl⟩
    left
    refine ⟨x, hx, c * a, mul_pos hc ha, ?_⟩
    simp [Prod.smul_mk, smul_smul]
  · right
    rcases hHor with ⟨hx, hzero⟩
    have hp0 : p.2 = 0 := by simpa using hzero
    refine ⟨hK.2 hx hc, ?_⟩
    simp [hp0]

theorem isPointed_raySpaceCone {C K : Set E} (hK : IsCone K) (hpointed : IsPointed K) :
    IsPointed (raySpaceCone C K) := by
  intro n z hz hsum i
  have hsnd_nonpos : ∀ j, (z j).2 ≤ 0 := by
    intro j
    rcases hz j with hOrd | hHor
    · rcases hOrd with ⟨x, hx, a, ha, hEq⟩
      have : -(a : ℝ) ≤ 0 := by linarith
      simpa [hEq] using this
    · have : (z j).2 = 0 := by simpa using hHor.2
      linarith
  have hsnd_zero : ∀ j, (z j).2 = 0 := by
    intro j
    have hle :
        (∑ k, (z k).2) ≤ 0 := by
      exact Finset.sum_nonpos fun k _ => hsnd_nonpos k
    have hsum_snd : (∑ k, (z k).2) = 0 := by
      simpa [Prod.snd_sum] using congrArg Prod.snd hsum
    exact le_antisymm (hsnd_nonpos j) <| by
      by_contra hj
      have hjlt : (z j).2 < 0 := lt_of_not_ge hj
      have hlt :
          (∑ k, (z k).2) < 0 := by
        have hlt' : (∑ k, (z k).2) < ∑ k : Fin n, (0 : ℝ) := by
          refine Finset.sum_lt_sum ?_ ?_
          · intro k hk
            exact hsnd_nonpos k
          · exact ⟨j, Finset.mem_univ j, hjlt⟩
        simpa using hlt'
      linarith
  have hzK : ∀ j, (z j).1 ∈ K := by
    intro j
    have hj0 : (z j).2 = 0 := hsnd_zero j
    have hzj : (((z j).1, (z j).2) : E × ℝ) ∈ raySpaceCone C K := by
      simpa using hz j
    have hjmem : (((z j).1, 0) : E × ℝ) ∈ raySpaceCone C K := by
      simpa [hj0] using hzj
    exact (mem_raySpaceCone_zero_iff).1 hjmem
  have hfst_sum : ∑ j, (z j).1 = 0 := by
    simpa [Prod.fst_sum] using congrArg Prod.fst hsum
  have hfst_zero := hpointed.fintype (z := fun j => (z j).1) hzK hfst_sum
  have hzEq : ∀ j, z j = 0 := by
    intro j
    ext <;> simp [hfst_zero j, hsnd_zero j]
  simpa using hzEq i

end RaySpace

section CosmicConvexity

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- **Definition 3.41**: the cosmic set corresponding to `C ∪ dir K` is convex
when its ordinary part and direction part are convex and the ordinary part is
stable under translation by directions from `K`. -/
def CosmicConvex (C K : Set E) : Prop :=
  Convex ℝ C ∧ Convex ℝ K ∧ C + K ⊆ C

/-- **Exercise 3.42**: for a cone `K`, cosmic convexity of `C ∪ dir K` is
equivalent to convexity of the corresponding ray-space cone. -/
theorem cosmicConvex_iff_convex_raySpaceCone {C K : Set E} (hKcone : IsCone K) :
    CosmicConvex C K ↔ Convex ℝ (raySpaceCone C K) := by
  constructor
  · rintro ⟨hC, hK, hCK⟩
    rw [(isCone_raySpaceCone hKcone).convex_iff_add_mem]
    intro p q hp hq
    rcases hp with hp | hp <;> rcases hq with hq | hq
    · rcases hp with ⟨x, hx, a, ha, rfl⟩
      rcases hq with ⟨y, hy, b, hb, rfl⟩
      left
      have hs : 0 < a + b := add_pos ha hb
      let z : E := (a / (a + b)) • x + (b / (a + b)) • y
      have hz : z ∈ C := by
        dsimp [z]
        exact hC hx hy
          (div_nonneg ha.le hs.le)
          (div_nonneg hb.le hs.le)
          (by field_simp [hs.ne'])
      refine ⟨z, hz, a + b, hs, ?_⟩
      ext
      · rw [smul_add, smul_smul, smul_smul]
        have hcoef_a : (a + b) * (a / (a + b)) = a := by
          field_simp [hs.ne']
        have hcoef_b : (a + b) * (b / (a + b)) = b := by
          field_simp [hs.ne']
        simp [hcoef_a, hcoef_b]
      · change (-a + -b) = -(a + b)
        ring
    · rcases hp with ⟨x, hx, a, ha, rfl⟩
      rcases q with ⟨w, β⟩
      rcases hq with ⟨hw, hβ⟩
      simp at hβ
      subst hβ
      left
      have hw' : a⁻¹ • w ∈ K := hKcone.smul_mem hw (inv_nonneg.2 ha.le)
      have hz : x + a⁻¹ • w ∈ C := hCK ⟨x, hx, a⁻¹ • w, hw', rfl⟩
      refine ⟨x + a⁻¹ • w, hz, a, ha, ?_⟩
      ext
      · rw [smul_add, smul_smul, mul_inv_cancel₀ ha.ne', one_smul]
        simp
      · simp
    · rcases p with ⟨w, β⟩
      rcases hp with ⟨hw, hβ⟩
      simp at hβ
      subst hβ
      rcases hq with ⟨x, hx, a, ha, rfl⟩
      left
      have hw' : a⁻¹ • w ∈ K := hKcone.smul_mem hw (inv_nonneg.2 ha.le)
      have hz : x + a⁻¹ • w ∈ C := hCK ⟨x, hx, a⁻¹ • w, hw', rfl⟩
      refine ⟨x + a⁻¹ • w, hz, a, ha, ?_⟩
      ext
      · rw [smul_add, smul_smul, mul_inv_cancel₀ ha.ne', one_smul]
        ac_rfl
      · simp
    · rcases p with ⟨u, α⟩
      rcases hp with ⟨hu, hα⟩
      simp at hα
      subst hα
      rcases q with ⟨v, β⟩
      rcases hq with ⟨hv, hβ⟩
      simp at hβ
      subst hβ
      right
      refine ⟨add_mem_of_convex_isCone hK hKcone hu hv, by simp⟩
  · intro hconv
    have hadd :
        ∀ ⦃p q : E × ℝ⦄, p ∈ raySpaceCone C K → q ∈ raySpaceCone C K → p + q ∈ raySpaceCone C K :=
      ((isCone_raySpaceCone hKcone).convex_iff_add_mem).1 hconv
    refine ⟨?_, ?_, ?_⟩
    · intro x hx y hy a b ha hb hab
      have hx' : ((x, (-1 : ℝ)) : E × ℝ) ∈ raySpaceCone C K :=
        (mem_raySpaceCone_neg_one_iff).2 hx
      have hy' : ((y, (-1 : ℝ)) : E × ℝ) ∈ raySpaceCone C K :=
        (mem_raySpaceCone_neg_one_iff).2 hy
      have hxy : a • ((x, (-1 : ℝ)) : E × ℝ) + b • ((y, (-1 : ℝ)) : E × ℝ) ∈ raySpaceCone C K :=
        hconv hx' hy' ha hb hab
      have hsnd : -a + -b = (-1 : ℝ) := by
        linarith
      have hxy' : ((a • x + b • y, (-1 : ℝ)) : E × ℝ) ∈ raySpaceCone C K := by
        simpa [Prod.smul_mk, hsnd, add_assoc, add_left_comm, add_comm] using hxy
      exact (mem_raySpaceCone_neg_one_iff).1 hxy'
    · intro x hx y hy a b ha hb hab
      have hx' : ((x, (0 : ℝ)) : E × ℝ) ∈ raySpaceCone C K :=
        (mem_raySpaceCone_zero_iff).2 hx
      have hy' : ((y, (0 : ℝ)) : E × ℝ) ∈ raySpaceCone C K :=
        (mem_raySpaceCone_zero_iff).2 hy
      have hxy : a • ((x, (0 : ℝ)) : E × ℝ) + b • ((y, (0 : ℝ)) : E × ℝ) ∈ raySpaceCone C K :=
        hconv hx' hy' ha hb hab
      have hxy' : ((a • x + b • y, (0 : ℝ)) : E × ℝ) ∈ raySpaceCone C K := by
        simpa [Prod.smul_mk, add_assoc, add_left_comm, add_comm] using hxy
      exact (mem_raySpaceCone_zero_iff).1 hxy'
    · rintro z ⟨x, hx, w, hw, rfl⟩
      have hsum : ((x, (-1 : ℝ)) : E × ℝ) + ((w, (0 : ℝ)) : E × ℝ) ∈ raySpaceCone C K :=
        hadd (mem_raySpaceCone_neg_one_iff.2 hx) (mem_raySpaceCone_zero_iff.2 hw)
      exact (mem_raySpaceCone_neg_one_iff).1 <| by simpa using hsum

/-- **Exercise 3.43**: interior points remain interior along every ray in a
direction from the cosmic part `K`. -/
theorem add_smul_mem_interior_of_cosmicConvex {C K : Set E}
    (hcosmic : CosmicConvex C K) (hKcone : IsCone K)
    {x : E} (hx : x ∈ interior C) {w : E} (hw : w ∈ K) {τ : ℝ} (hτ : 0 < τ) :
    x + τ • w ∈ interior C := by
  rcases hcosmic with ⟨hC, _hK, hCK⟩
  have hxC : x ∈ C := interior_subset hx
  have h2w : (2 * τ) • w ∈ K := hKcone.smul_mem hw (by positivity)
  have hy : x + (2 * τ) • w ∈ C := hCK ⟨x, hxC, (2 * τ) • w, h2w, rfl⟩
  have hmid :
      (1 - (1 / 2 : ℝ)) • x + (1 / 2 : ℝ) • (x + (2 * τ) • w) ∈ interior C :=
    line_segment_interior hC hx (subset_closure hy) (by norm_num) (by norm_num)
  simpa [smul_add, smul_smul, midpoint_eq_smul_add, add_assoc, add_left_comm,
    add_comm, two_smul] using hmid

end CosmicConvexity

section Closure

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]

theorem mem_closure_raySpaceCone_of_mem_ordinaryRayCone_closure {C K : Set E}
    {p : E × ℝ} (hp : p ∈ ordinaryRayCone (closure C)) :
    p ∈ closure (raySpaceCone C K) := by
  rcases hp with ⟨x, hx, a, ha, rfl⟩
  rcases mem_closure_iff_seq_limit.mp hx with ⟨u, hu, hu_tendsto⟩
  refine mem_closure_iff_seq_limit.mpr ?_
  refine ⟨fun n => (a • u n, -a), ?_, ?_⟩
  · intro n
    exact Or.inl ⟨u n, hu n, a, ha, rfl⟩
  · have hfst : Tendsto (fun n => a • u n) atTop (𝓝 (a • x)) :=
      (tendsto_const_nhds : Tendsto (fun _ : ℕ => a) atTop (𝓝 a)).smul hu_tendsto
    have hsnd : Tendsto (fun _ : ℕ => (-a : ℝ)) atTop (𝓝 (-a)) :=
      tendsto_const_nhds
    simpa [nhds_prod_eq] using hfst.prodMk hsnd

theorem mem_closure_raySpaceCone_of_mem_closure_horizon {C K : Set E}
    {w : E} (hw : w ∈ closure K) :
    ((w, (0 : ℝ)) : E × ℝ) ∈ closure (raySpaceCone C K) := by
  rcases mem_closure_iff_seq_limit.mp hw with ⟨u, hu, hu_tendsto⟩
  refine mem_closure_iff_seq_limit.mpr ?_
  refine ⟨fun n => ((u n, (0 : ℝ)) : E × ℝ), ?_, ?_⟩
  · intro n
    exact Or.inr ⟨hu n, rfl⟩
  · have hsnd : Tendsto (fun _ : ℕ => (0 : ℝ)) atTop (𝓝 0) := tendsto_const_nhds
    simpa [nhds_prod_eq] using hu_tendsto.prodMk hsnd

theorem mem_closure_raySpaceCone_of_mem_horizonCone {C K : Set E}
    (hK : IsCone K) {w : E} (hw : w ∈ horizonCone C) :
    ((w, (0 : ℝ)) : E × ℝ) ∈ closure (raySpaceCone C K) := by
  by_cases hw0 : w = 0
  · subst hw0
    exact subset_closure <| Or.inr ⟨hK.1, rfl⟩
  · have hwasy : w ∈ asymptoticCone ℝ C := by
      simpa [horizonCone, hw0] using hw
    rcases exists_seq_pos_smul_of_mem_asymptoticCone (C := C) hwasy with
      ⟨c, u, hc, hu, hcpos, hmem⟩
    refine mem_closure_iff_seq_limit.mpr ?_
    refine ⟨fun n => (u n, -(c n)⁻¹), ?_, ?_⟩
    · intro n
      left
      refine ⟨c n • u n, hmem n, (c n)⁻¹, inv_pos.mpr (hcpos n), ?_⟩
      ext <;> simp [Prod.smul_mk, smul_smul, inv_mul_cancel₀ (hcpos n).ne']
    · have hsnd : Tendsto (fun n => -(c n)⁻¹) atTop (𝓝 (0 : ℝ)) := by
        simpa using hc.inv_tendsto_atTop.neg
      simpa [nhds_prod_eq] using hu.prodMk hsnd

/-- Exercise 3.4 in the ray-space model: the closure of the cone corresponding
to `C ∪ dir K` is obtained by closing `C` and adjoining the horizon cone of
`C` to the direction part. -/
theorem closure_raySpaceCone {C K : Set E} (hK : IsCone K) :
    closure (raySpaceCone C K) =
      raySpaceCone (closure C) (horizonCone C ∪ closure K) := by
  classical
  apply le_antisymm
  · intro p hp
    rcases mem_closure_iff_seq_limit.mp hp with ⟨u, hu, hu_tendsto⟩
    have hsnd : Tendsto (fun n => (u n).2) atTop (𝓝 p.2) := by
      exact (continuous_snd.continuousAt.tendsto).comp hu_tendsto
    have hu_nonpos : ∀ n, (u n).2 ≤ 0 := by
      intro n
      rcases hu n with hOrd | hHor
      · rcases hOrd with ⟨x, hx, a, ha, hEq⟩
        have : -(a : ℝ) ≤ 0 := by linarith
        simpa [hEq] using this
      · have : (u n).2 = 0 := by simpa using hHor.2
        linarith
    have hp_nonpos : p.2 ≤ 0 := by
      exact isClosed_Iic.mem_of_tendsto hsnd (Eventually.of_forall hu_nonpos)
    rcases eq_or_lt_of_le hp_nonpos with hp0 | hpneg
    · rcases Nat.exists_subseq_of_forall_mem_union u hu with ⟨g, hgOrd | hgHor⟩
      · have hfst : Tendsto (fun n => (u (g n)).1) atTop (𝓝 p.1) := by
          exact (continuous_fst.continuousAt.tendsto).comp
            (hu_tendsto.comp (OrderEmbedding.strictMono g).tendsto_atTop)
        have hsndg : Tendsto (fun n => (u (g n)).2) atTop (𝓝 p.2) := by
          exact (continuous_snd.continuousAt.tendsto).comp
            (hu_tendsto.comp (OrderEmbedding.strictMono g).tendsto_atTop)
        have hgOrd' :
            ∀ n, ∃ x ∈ C, ∃ lam : ℝ, 0 < lam ∧ u (g n) = (lam • x, -lam) := by
          intro n
          exact (mem_ordinaryRayCone).1 (hgOrd n)
        choose x hx lam hlam hEq using hgOrd'
        have hlam0 : Tendsto lam atTop (𝓝 (0 : ℝ)) := by
          have hnegLam : Tendsto (fun n => -lam n) atTop (𝓝 (0 : ℝ)) := by
            have hEqsnd : (fun n => (u (g n)).2) = fun n => -lam n := by
              funext n
              simpa using congrArg Prod.snd (hEq n)
            simpa [hp0, hEqsnd] using hsndg
          simpa using hnegLam.neg
        have hlam0gt : Tendsto lam atTop (𝓝[>] (0 : ℝ)) :=
          tendsto_nhdsWithin_iff.mpr ⟨hlam0, Eventually.of_forall hlam⟩
        have hc : Tendsto (fun n => (lam n)⁻¹) atTop atTop :=
          hlam0gt.inv_tendsto_nhdsGT_zero
        have hmemC : ∀ n, (lam n)⁻¹ • (u (g n)).1 ∈ C := by
          intro n
          have hfstEq : (u (g n)).1 = lam n • x n := by
            simpa using congrArg Prod.fst (hEq n)
          have hxEq : (lam n)⁻¹ • (u (g n)).1 = x n := by
            calc
              (lam n)⁻¹ • (u (g n)).1 = (lam n)⁻¹ • (lam n • x n) := by rw [hfstEq]
              _ = x n := by rw [smul_smul, inv_mul_cancel₀ (hlam n).ne', one_smul]
          simpa [hxEq] using hx n
        have hpasy : p.1 ∈ asymptoticCone ℝ C :=
          mem_asymptoticCone_of_seq_smul hc hfst hmemC
        exact Or.inr ⟨Or.inl (Set.mem_insert_of_mem 0 hpasy), by simpa [hp0]⟩
      · have hfst : Tendsto (fun n => (u (g n)).1) atTop (𝓝 p.1) := by
          exact (continuous_fst.continuousAt.tendsto).comp
            (hu_tendsto.comp (OrderEmbedding.strictMono g).tendsto_atTop)
        have hpcl : p.1 ∈ closure K := by
          exact isClosed_closure.mem_of_tendsto hfst <|
            Eventually.of_forall fun n => subset_closure (hgHor n).1
        exact Or.inr ⟨Or.inr hpcl, by simpa [hp0]⟩
    · have hneg_event : ∀ᶠ n in atTop, (u n).2 < 0 :=
        hsnd.eventually (isOpen_Iio.mem_nhds hpneg)
      obtain ⟨φ, hφmono, hφneg⟩ := extraction_of_eventually_atTop hneg_event
      have hOrd : ∀ n, u (φ n) ∈ ordinaryRayCone C := by
        intro n
        rcases hu (φ n) with hOrd | hHor
        · exact hOrd
        · have hzero : (u (φ n)).2 = 0 := by simpa using hHor.2
          exact False.elim <| by
            have : ¬ (u (φ n)).2 < 0 := by simpa [hzero]
            exact this (hφneg n)
      have hOrd' :
          ∀ n, ∃ x ∈ C, ∃ lam : ℝ, 0 < lam ∧ u (φ n) = (lam • x, -lam) := by
        intro n
        exact (mem_ordinaryRayCone).1 (hOrd n)
      choose x hx lam hlam_pos hEq using hOrd'
      have hfst : Tendsto (fun n => (u (φ n)).1) atTop (𝓝 p.1) := by
        exact (continuous_fst.continuousAt.tendsto).comp (hu_tendsto.comp hφmono.tendsto_atTop)
      have hsndφ : Tendsto (fun n => (u (φ n)).2) atTop (𝓝 p.2) := by
        exact (continuous_snd.continuousAt.tendsto).comp (hu_tendsto.comp hφmono.tendsto_atTop)
      have hlam_lim : Tendsto lam atTop (𝓝 (-p.2)) := by
        have hnegLam : Tendsto (fun n => -lam n) atTop (𝓝 p.2) := by
          have hEqsnd : (fun n => (u (φ n)).2) = fun n => -lam n := by
            funext n
            simpa using congrArg Prod.snd (hEq n)
          simpa [hEqsnd] using hsndφ
        simpa using hnegLam.neg
      have hlamInv : Tendsto (fun n => (lam n)⁻¹) atTop (𝓝 ((-p.2)⁻¹)) := by
        have hp2ne : -p.2 ≠ 0 := by linarith
        exact (continuousAt_inv₀ hp2ne).tendsto.comp hlam_lim
      have hxlim :
          Tendsto (fun n => (lam n)⁻¹ • (u (φ n)).1) atTop (𝓝 (((-p.2)⁻¹) • p.1)) :=
        hlamInv.smul hfst
      have hmemC : ∀ n, (lam n)⁻¹ • (u (φ n)).1 ∈ C := by
        intro n
        have hfstEq : (u (φ n)).1 = lam n • x n := by
          simpa using congrArg Prod.fst (hEq n)
        have hxEq : (lam n)⁻¹ • (u (φ n)).1 = x n := by
          calc
            (lam n)⁻¹ • (u (φ n)).1 = (lam n)⁻¹ • (lam n • x n) := by rw [hfstEq]
            _ = x n := by rw [smul_smul, inv_mul_cancel₀ (hlam_pos n).ne', one_smul]
        simpa [hxEq] using hx n
      have hxcl : (((-p.2)⁻¹) • p.1) ∈ closure C :=
        isClosed_closure.mem_of_tendsto hxlim <|
          Eventually.of_forall fun n => subset_closure (hmemC n)
      left
      refine ⟨((-p.2)⁻¹) • p.1, hxcl, -p.2, by linarith, ?_⟩
      have hp2ne : -p.2 ≠ 0 := by linarith
      ext
      · rw [smul_smul, mul_inv_cancel₀ hp2ne, one_smul]
      · simp
  · intro p hp
    rcases hp with hOrd | hHor
    · exact mem_closure_raySpaceCone_of_mem_ordinaryRayCone_closure hOrd
    · rcases p with ⟨w, a⟩
      rcases hHor with ⟨hHor, hzero⟩
      simp at hzero
      subst hzero
      rcases hHor with hC | hKcl
      · exact mem_closure_raySpaceCone_of_mem_horizonCone hK hC
      · exact mem_closure_raySpaceCone_of_mem_closure_horizon hKcl

/-- Exercise 3.4: the ray-space cone is closed exactly when the ordinary part
and direction part are closed and the horizon cone of the ordinary part is
contained in the given direction cone. -/
theorem isClosed_raySpaceCone_iff {C K : Set E} (hK : IsCone K) :
    IsClosed (raySpaceCone C K) ↔
      IsClosed C ∧ IsClosed K ∧ horizonCone C ⊆ K := by
  constructor
  · intro hclosed
    have hEq :
        raySpaceCone C K = raySpaceCone (closure C) (horizonCone C ∪ closure K) := by
      rw [← hclosed.closure_eq, closure_raySpaceCone hK]
    have hCeq : closure C = C := by
      ext x
      have hx := congrArg (fun s : Set (E × ℝ) => ((x, (-1 : ℝ)) : E × ℝ) ∈ s) hEq
      simpa [mem_raySpaceCone_neg_one_iff] using hx.symm
    have hKeq : horizonCone C ∪ closure K = K := by
      ext x
      have hx := congrArg (fun s : Set (E × ℝ) => ((x, (0 : ℝ)) : E × ℝ) ∈ s) hEq
      simpa [mem_raySpaceCone_zero_iff] using hx.symm
    refine ⟨?_, ?_, ?_⟩
    · rwa [← closure_eq_iff_isClosed]
    · have hclK : closure K = K := by
        apply le_antisymm
        · intro x hx
          have : x ∈ horizonCone C ∪ closure K := Or.inr hx
          simpa [hKeq] using this
        · exact subset_closure
      rwa [← closure_eq_iff_isClosed]
    · intro x hx
      have : x ∈ horizonCone C ∪ closure K := Or.inl hx
      simpa [hKeq] using this
  · rintro ⟨hC, hKclosed, hCK⟩
    have hUnion : horizonCone C ∪ K = K := Set.union_eq_right.mpr hCK
    rw [← closure_eq_iff_isClosed, closure_raySpaceCone hK]
    rw [hC.closure_eq, hKclosed.closure_eq, hUnion]

end Closure

section ConvexHulls

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

private def ordinarySliceAffine (a : ℝ) : E →ᵃ[ℝ] E × ℝ where
  toFun x := (a • x, -a)
  linear := ((a • (LinearMap.id : E →ₗ[ℝ] E)).prod (0 : E →ₗ[ℝ] ℝ))
  map_vadd' p v := by
    ext <;> simp [smul_add]

@[simp] private theorem ordinarySliceAffine_apply (a : ℝ) (x : E) :
    ordinarySliceAffine (E := E) a x = (a • x, -a) :=
  rfl

private def horizontalSliceLinear (a : ℝ) : E →ₗ[ℝ] E × ℝ :=
  ((a • (LinearMap.id : E →ₗ[ℝ] E)).prod (0 : E →ₗ[ℝ] ℝ))

@[simp] private theorem horizontalSliceLinear_apply (a : ℝ) (x : E) :
    horizontalSliceLinear (E := E) a x = (a • x, 0) :=
  rfl

private theorem ordinarySliceAffine_image_subset_raySpaceCone {C K : Set E} {a : ℝ}
    (ha : 0 < a) :
    ordinarySliceAffine (E := E) a '' C ⊆ raySpaceCone C K := by
  rintro p ⟨x, hx, rfl⟩
  exact Or.inl ⟨x, hx, a, ha, rfl⟩

private theorem horizontalSliceLinear_image_subset_raySpaceCone {C K : Set E} {a : ℝ}
    (ha : 0 ≤ a) (hKcone : IsCone K) :
    horizontalSliceLinear (E := E) a '' K ⊆ raySpaceCone C K := by
  rintro p ⟨x, hx, rfl⟩
  exact Or.inr ⟨hKcone.smul_mem hx ha, rfl⟩

private theorem mem_convexHull_raySpaceCone_of_mem_ordinarySlice {C K : Set E}
    {x : E} {a : ℝ} (hx : x ∈ convexHull ℝ C) (ha : 0 < a) :
    ((a • x, -a) : E × ℝ) ∈ convexHull ℝ (raySpaceCone C K) := by
  let A := ordinarySliceAffine (E := E) a
  have hmem : A x ∈ A '' convexHull ℝ C := ⟨x, hx, rfl⟩
  have hsub : A '' C ⊆ convexHull ℝ (raySpaceCone C K) := by
    intro p hp
    exact subset_convexHull ℝ _ <|
      ordinarySliceAffine_image_subset_raySpaceCone (C := C) (K := K) ha hp
  rw [A.image_convexHull (𝕜 := ℝ) C] at hmem
  exact convexHull_min hsub (convex_convexHull ℝ _) hmem

private theorem mem_convexHull_raySpaceCone_of_mem_convexHull_horizontal {C K : Set E}
    {x : E} {a : ℝ} (hx : x ∈ convexHull ℝ K) (ha : 0 ≤ a) (hKcone : IsCone K) :
    ((a • x, 0) : E × ℝ) ∈ convexHull ℝ (raySpaceCone C K) := by
  let L := horizontalSliceLinear (E := E) a
  have hmem : L x ∈ L '' convexHull ℝ K := ⟨x, hx, rfl⟩
  have hsub : L '' K ⊆ convexHull ℝ (raySpaceCone C K) := by
    intro p hp
    exact subset_convexHull ℝ _ <|
      horizontalSliceLinear_image_subset_raySpaceCone (C := C) (K := K) ha hKcone hp
  rw [L.image_convexHull (𝕜 := ℝ) K] at hmem
  exact convexHull_min hsub (convex_convexHull ℝ _) hmem

/-- **Exercise 3.44**: the convex hull of a cosmic set corresponds in ray space
to taking convex hulls of the ordinary and direction parts. -/
theorem convexHull_raySpaceCone {C K : Set E} (hKcone : IsCone K) :
    convexHull ℝ (raySpaceCone C K) =
      raySpaceCone (convexHull ℝ C + convexHull ℝ K) (convexHull ℝ K) := by
  have hconvK : Convex ℝ (convexHull ℝ K) := convex_convexHull ℝ K
  have hconeK : IsCone (convexHull ℝ K) := isCone_convexHull hKcone
  have hcosmic :
      CosmicConvex (convexHull ℝ C + convexHull ℝ K) (convexHull ℝ K) := by
    refine ⟨(convex_convexHull ℝ C).add hconvK, hconvK, ?_⟩
    rintro z ⟨u, hu, v, hv, rfl⟩
    rcases hu with ⟨x, hx, y, hy, rfl⟩
    refine ⟨x, hx, y + v, add_mem_of_convex_isCone hconvK hconeK hy hv, ?_⟩
    ac_rfl
  have hRconv :
      Convex ℝ (raySpaceCone (convexHull ℝ C + convexHull ℝ K) (convexHull ℝ K)) :=
    (cosmicConvex_iff_convex_raySpaceCone
      (C := convexHull ℝ C + convexHull ℝ K) (K := convexHull ℝ K) hconeK).1 hcosmic
  apply le_antisymm
  · refine convexHull_min ?_ hRconv
    intro p hp
    rcases hp with hOrd | hHor
    · rcases hOrd with ⟨x, hx, a, ha, rfl⟩
      left
      refine ⟨x, ?_, a, ha, rfl⟩
      exact ⟨x, subset_convexHull ℝ C hx, 0, subset_convexHull ℝ K hKcone.1, by simp⟩
    · rcases p with ⟨w, β⟩
      rcases hHor with ⟨hw, hβ⟩
      simp at hβ
      subst hβ
      right
      exact ⟨subset_convexHull ℝ K hw, rfl⟩
  · intro p hp
    rcases hp with hOrd | hHor
    · rcases hOrd with ⟨x, hx, a, ha, rfl⟩
      rcases hx with ⟨c, hc, w, hw, rfl⟩
      have hc' :
          ((a • c, -a) : E × ℝ) ∈ convexHull ℝ (raySpaceCone C K) :=
        mem_convexHull_raySpaceCone_of_mem_ordinarySlice (C := C) (K := K) hc ha
      have hw' :
          ((a • w, 0) : E × ℝ) ∈ convexHull ℝ (raySpaceCone C K) :=
        mem_convexHull_raySpaceCone_of_mem_convexHull_horizontal
          (C := C) (K := K) hw ha.le hKcone
      have hsum :
          ((a • c, -a) : E × ℝ) + ((a • w, 0) : E × ℝ) ∈
            convexHull ℝ (raySpaceCone C K) :=
        add_mem_of_convex_isCone (convex_convexHull ℝ _)
          (isCone_convexHull (isCone_raySpaceCone hKcone)) hc' hw'
      simpa [Prod.mk_add_mk, smul_add] using hsum
    · rcases p with ⟨w, β⟩
      rcases hHor with ⟨hw, hβ⟩
      simp at hβ
      subst hβ
      simpa using
        mem_convexHull_raySpaceCone_of_mem_convexHull_horizontal
          (C := C) (K := K) (x := w) (a := 1) hw (by norm_num) hKcone

/-- If `D` is closed and convex, contains `C`, and its horizon cone contains
`K`, then it also contains `convexHull C + convexHull K`. -/
theorem convexHull_add_convexHull_minimal_of_closed_convex_horizon
    {C K D : Set E} (hDclosed : IsClosed D) (hDconv : Convex ℝ D)
    (hCD : C ⊆ D) (hKD : K ⊆ horizonCone D) :
    convexHull ℝ C + convexHull ℝ K ⊆ D := by
  rintro z ⟨x, hx, w, hw, rfl⟩
  have hxD : x ∈ D := convexHull_min hCD hDconv hx
  have hwD : w ∈ horizonCone D := convexHull_min hKD (convex_horizonCone hDconv) hw
  simpa [add_comm] using
    smul_add_mem_of_mem_horizonCone (C := D) hDconv hDclosed hxD hwD (τ := 1) (by norm_num)

end ConvexHulls

section ClosedConvexHulls

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]

/-- **Proposition 3.45**: for a closed set `C` and a closed pointed cone `K`
containing the horizon cone of `C`, the set `convexHull C + convexHull K` is
closed and has horizon cone `convexHull K`. -/
theorem isClosed_horizonCone_eq_convexHull_of_isClosed_isPointed
    {C K : Set E} (hCclosed : IsClosed C) (hCne : C.Nonempty)
    (hKclosed : IsClosed K) (hKcone : IsCone K) (hKpointed : IsPointed K)
    (hCK : horizonCone C ⊆ K) :
    IsClosed (convexHull ℝ C + convexHull ℝ K) ∧
      horizonCone (convexHull ℝ C + convexHull ℝ K) = convexHull ℝ K := by
  have hrayClosed : IsClosed (raySpaceCone C K) :=
    (isClosed_raySpaceCone_iff hKcone).2 ⟨hCclosed, hKclosed, hCK⟩
  have hrayPointed : IsPointed (raySpaceCone C K) :=
    isPointed_raySpaceCone hKcone hKpointed
  have hconvHullClosed : IsClosed (convexHull ℝ (raySpaceCone C K)) :=
    isClosed_convexHull_of_isClosed_isPointed
      hrayClosed (isCone_raySpaceCone hKcone) hrayPointed
  have hEq :
      convexHull ℝ (raySpaceCone C K) =
        raySpaceCone (convexHull ℝ C + convexHull ℝ K) (convexHull ℝ K) :=
    convexHull_raySpaceCone hKcone
  have hclosedRay :
      IsClosed (raySpaceCone (convexHull ℝ C + convexHull ℝ K) (convexHull ℝ K)) := by
    rw [← hEq]
    exact hconvHullClosed
  rcases (isClosed_raySpaceCone_iff (C := convexHull ℝ C + convexHull ℝ K)
      (K := convexHull ℝ K) (isCone_convexHull hKcone)).1 hclosedRay with
    ⟨hclosedD, _, hsubset⟩
  have hsupset :
      convexHull ℝ K ⊆ horizonCone (convexHull ℝ C + convexHull ℝ K) := by
    rcases hCne with ⟨x, hx⟩
    intro w hw
    refine mem_horizonCone_of_forall_smul_add_mem
      (C := convexHull ℝ C + convexHull ℝ K)
      (x := x) (w := w) ?_
    intro τ hτ
    refine ⟨x, subset_convexHull ℝ C hx, τ • w, ?_, ?_⟩
    · exact (isCone_convexHull hKcone).smul_mem hw hτ
    · simpa [add_comm]
  exact ⟨hclosedD, le_antisymm hsubset hsupset⟩

/-- **Proposition 3.45**: `convexHull C + convexHull K` is the smallest closed
convex set containing `C` whose horizon cone contains `K`. -/
theorem convexHull_add_convexHull_minimal_of_isClosed_isPointed
    {C K D : Set E} (hDclosed : IsClosed D) (hDconv : Convex ℝ D)
    (hCD : C ⊆ D) (hKD : K ⊆ horizonCone D) :
    convexHull ℝ C + convexHull ℝ K ⊆ D :=
  convexHull_add_convexHull_minimal_of_closed_convex_horizon hDclosed hDconv hCD hKD

/-- **Corollary 3.46**: if `C` is closed and `horizonCone C` is pointed, then
the closure of `convexHull C` is obtained by adjoining the convex hull of the
horizon cone. -/
theorem closure_convexHull_eq_add_convexHull_horizonCone
    {C : Set E} (hCclosed : IsClosed C) (hCpointed : IsPointed (horizonCone C)) :
    closure (convexHull ℝ C) = convexHull ℝ C + convexHull ℝ (horizonCone C) := by
  by_cases hCne : C.Nonempty
  · obtain ⟨hclosedD, _⟩ :=
      isClosed_horizonCone_eq_convexHull_of_isClosed_isPointed
        (C := C) (K := horizonCone C) hCclosed hCne
        (isClosed_horizonCone C) (isCone_horizonCone C) hCpointed subset_rfl
    apply le_antisymm
    · refine closure_minimal ?_ hclosedD
      intro x hx
      exact ⟨x, hx, 0, subset_convexHull ℝ (horizonCone C) (zero_mem_horizonCone C), by simp⟩
    · have hsubsetC : C ⊆ closure (convexHull ℝ C) := by
        intro x hx
        exact subset_closure (subset_convexHull ℝ C hx)
      have hsubsetK : horizonCone C ⊆ horizonCone (closure (convexHull ℝ C)) := by
        exact horizonCone_mono hsubsetC
      exact convexHull_add_convexHull_minimal_of_closed_convex_horizon
        (C := C) (K := horizonCone C) (D := closure (convexHull ℝ C))
        isClosed_closure (convex_convexHull ℝ _).closure hsubsetC hsubsetK
  · have hCempty : C = ∅ := Set.not_nonempty_iff_eq_empty.mp hCne
    simp [hCempty]

/-- **Corollary 3.46**: the horizon cone of `closure (convexHull C)` is the
convex hull of the original horizon cone. -/
theorem horizonCone_closure_convexHull_eq_convexHull_horizonCone
    {C : Set E} (hCclosed : IsClosed C) (hCpointed : IsPointed (horizonCone C)) :
    horizonCone (closure (convexHull ℝ C)) = convexHull ℝ (horizonCone C) := by
  by_cases hCne : C.Nonempty
  · obtain ⟨_, hhor⟩ :=
      isClosed_horizonCone_eq_convexHull_of_isClosed_isPointed
        (C := C) (K := horizonCone C) hCclosed hCne
        (isClosed_horizonCone C) (isCone_horizonCone C) hCpointed subset_rfl
    rw [closure_convexHull_eq_add_convexHull_horizonCone hCclosed hCpointed]
    exact hhor
  · have hCempty : C = ∅ := Set.not_nonempty_iff_eq_empty.mp hCne
    simp [hCempty]

end ClosedConvexHulls

end RW
