/- 
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Chapter 3G*: Generated Sets

This file packages the ordinary-points-plus-directions representation from the
polyhedral tail of Chapter 3:
- the extended convex hull generated by ordinary points and direction points;
- its ray-space description;
- finite-generation closure under addition and linear images.
-/

import RockafellarWets.Chapter3.GeneratedCones
import RockafellarWets.Chapter3.CosmicClosure

open Set
open scoped Pointwise

namespace RW

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- The extended convex hull generated by ordinary points `A` and direction
points `B`. This is the representation that appears in Corollary 3.53. -/
def extendedConvexHull (A B : Set E) : Set E :=
  convexHull ℝ A + conicHull B

theorem convex_extendedConvexHull (A B : Set E) :
    Convex ℝ (extendedConvexHull A B) := by
  exact (convex_convexHull ℝ A).add (convex_conicHull B)

/-- Ray-space convexification of finitely generated direction data gives the
extended convex hull on the ordinary slice. -/
theorem convexHull_raySpaceCone_eq_raySpaceCone_extendedConvexHull
    (A B : Set E) :
    convexHull ℝ (raySpaceCone A (conicHull B)) =
      raySpaceCone (extendedConvexHull A B) (conicHull B) := by
  have hcone : IsCone (conicHull B) := isCone_conicHull B
  have hconv :
      (convexHull ℝ (conicHull B) : Set E) = conicHull B :=
    (convex_iff_eq_convexHull (conicHull B)).mp (convex_conicHull B)
  simpa [extendedConvexHull, hconv] using
    convexHull_raySpaceCone (C := A) (K := conicHull B) hcone

/-- For a cone, the ordinary ray slice is exactly the negative-height strip
over the cone. -/
theorem ordinaryRayCone_eq_prod_Iio_zero_of_isCone {K : Set E} (hK : IsCone K) :
    ordinaryRayCone K = K ×ˢ Set.Iio (0 : ℝ) := by
  ext p
  constructor
  · rintro ⟨x, hx, a, ha, rfl⟩
    refine ⟨hK.2 hx ha, ?_⟩
    show (-a : ℝ) < 0
    linarith
  · rintro ⟨hpK, hp2⟩
    have hp2lt : p.2 < 0 := hp2
    have hp2' : 0 < -p.2 := by linarith
    refine ⟨((-p.2)⁻¹ • p.1), hK.2 hpK (inv_pos.mpr hp2'), -p.2, hp2', ?_⟩
    ext
    · symm
      calc
        (-p.2 : ℝ) • (((-p.2)⁻¹ : ℝ) • p.1)
            = (((-p.2 : ℝ) * (-p.2)⁻¹) : ℝ) • p.1 := by rw [smul_smul]
        _ = p.1 := by
              have hp20 : p.2 ≠ 0 := by linarith
              simp [hp20]
    · ring

/-- For a cone, the full ray-space cone is the product with the nonpositive
real ray. -/
theorem raySpaceCone_eq_prod_Iic_zero_of_isCone {K : Set E} (hK : IsCone K) :
    raySpaceCone K K = K ×ˢ Set.Iic (0 : ℝ) := by
  rw [raySpaceCone, ordinaryRayCone_eq_prod_Iio_zero_of_isCone hK]
  ext p
  constructor
  · rintro (hp | hp)
    · change p.1 ∈ K ∧ p.2 ≤ 0
      exact ⟨hp.1, le_of_lt (show p.2 < 0 from hp.2)⟩
    · rcases hp with ⟨hpK, hpZero⟩
      have hp20 : p.2 = 0 := by simpa using hpZero
      change p.1 ∈ K ∧ p.2 ≤ 0
      exact ⟨hpK, by simpa [hp20]⟩
  · rintro ⟨hpK, hp2⟩
    rcases lt_or_eq_of_le (show p.2 ≤ 0 from hp2) with hp2' | hp2'
    · exact Or.inl ⟨hpK, hp2'⟩
    · exact Or.inr ⟨hpK, by simpa [hp2']⟩

/-- A set is finitely generated in the extended-convex-hull sense if it is the
sum of the convex hull of finitely many ordinary points and the conic hull of
finitely many directions. -/
def IsExtendedFinitelyGenerated (C : Set E) : Prop :=
  ∃ s t : Finset E, C = extendedConvexHull (↑s : Set E) (↑t : Set E)

theorem IsExtendedFinitelyGenerated.convex {C : Set E}
    (hC : IsExtendedFinitelyGenerated C) :
    Convex ℝ C := by
  rcases hC with ⟨s, t, rfl⟩
  exact convex_extendedConvexHull (↑s : Set E) (↑t : Set E)

theorem IsFinitelyGeneratedCone.isExtendedFinitelyGenerated {K : Set E}
    (hK : IsFinitelyGeneratedCone K) :
    IsExtendedFinitelyGenerated K := by
  classical
  rcases hK with ⟨t, rfl⟩
  refine ⟨{0}, t, ?_⟩
  simp [extendedConvexHull, conicHull]

theorem IsFinitelyGeneratedCone.raySpaceCone_of_isCone {K : Set E}
    (hK : IsFinitelyGeneratedCone K) (hKcone : IsCone K) :
    IsFinitelyGeneratedCone (raySpaceCone K K) := by
  rw [raySpaceCone_eq_prod_Iic_zero_of_isCone hKcone]
  exact hK.prod (show IsFinitelyGeneratedCone (Set.Iic (0 : ℝ)) from by
    refine ⟨{-1}, ?_⟩
    simpa using conicHull_singleton_neg_one_eq_Iic_zero.symm)

open Classical in
private noncomputable def finsetAdd (s t : Finset E) : Finset E :=
  (s.product t).image fun p => p.1 + p.2

private theorem prod_add_prod {F : Type*}
    [NormedAddCommGroup F] [NormedSpace ℝ F]
    (A B : Set E) (C D : Set F) :
    (A + B) ×ˢ (C + D) = (A ×ˢ C) + (B ×ˢ D) := by
  ext p
  constructor
  · rintro ⟨hp₁, hp₂⟩
    rcases hp₁ with ⟨a, ha, b, hb, hab⟩
    rcases hp₂ with ⟨c, hc, d, hd, hcd⟩
    refine Set.mem_add.2 ⟨(a, c), ⟨ha, hc⟩, (b, d), ⟨hb, hd⟩, ?_⟩
    ext <;> simp [hab, hcd]
  · rintro ⟨x, hx, y, hy, rfl⟩
    rcases x with ⟨a, c⟩
    rcases y with ⟨b, d⟩
    rcases hx with ⟨ha, hc⟩
    rcases hy with ⟨hb, hd⟩
    exact ⟨Set.mem_add.2 ⟨a, ha, b, hb, rfl⟩, Set.mem_add.2 ⟨c, hc, d, hd, rfl⟩⟩

private theorem coe_finsetAdd (s t : Finset E) :
    ((finsetAdd s t : Finset E) : Set E) = (↑s : Set E) + ↑t := by
  classical
  ext x
  constructor
  · intro hx
    rw [finsetAdd] at hx
    rcases Finset.mem_image.mp hx with ⟨p, hp, rfl⟩
    rcases Finset.mem_product.mp hp with ⟨hp1, hp2⟩
    exact Set.mem_add.2 ⟨p.1, hp1, p.2, hp2, rfl⟩
  · rintro ⟨a, ha, b, hb, rfl⟩
    exact show a + b ∈ (finsetAdd s t : Finset E) by
      exact Finset.mem_image.mpr ⟨(a, b), Finset.mem_product.mpr ⟨ha, hb⟩, rfl⟩

theorem IsExtendedFinitelyGenerated.add {C D : Set E}
    (hC : IsExtendedFinitelyGenerated C) (hD : IsExtendedFinitelyGenerated D) :
    IsExtendedFinitelyGenerated (C + D) := by
  classical
  rcases hC with ⟨s₁, t₁, rfl⟩
  rcases hD with ⟨s₂, t₂, rfl⟩
  refine ⟨finsetAdd s₁ s₂, t₁ ∪ t₂, ?_⟩
  change
    (convexHull ℝ (↑s₁ : Set E) + conicHull (↑t₁ : Set E)) +
        (convexHull ℝ (↑s₂ : Set E) + conicHull (↑t₂ : Set E)) =
      convexHull ℝ (↑(finsetAdd s₁ s₂ : Finset E) : Set E) +
        conicHull (↑(t₁ ∪ t₂) : Set E)
  calc
    (convexHull ℝ (↑s₁ : Set E) + conicHull (↑t₁ : Set E)) +
        (convexHull ℝ (↑s₂ : Set E) + conicHull (↑t₂ : Set E))
        = (convexHull ℝ (↑s₁ : Set E) + convexHull ℝ (↑s₂ : Set E)) +
            (conicHull (↑t₁ : Set E) + conicHull (↑t₂ : Set E)) := by
              ext x
              simp [Set.mem_add, add_assoc, add_left_comm, add_comm]
    _ = convexHull ℝ ((↑s₁ : Set E) + ↑s₂) +
          conicHull ((↑t₁ : Set E) ∪ (↑t₂ : Set E)) := by
            rw [← convexHull_add, ← conicHull_union_eq_add]
    _ = convexHull ℝ (↑(finsetAdd s₁ s₂ : Finset E) : Set E) +
          conicHull (↑(t₁ ∪ t₂) : Set E) := by
            simp [coe_finsetAdd]

section Products

variable {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]

theorem IsExtendedFinitelyGenerated.prod {C : Set E} {D : Set F}
    (hC : IsExtendedFinitelyGenerated C) (hD : IsExtendedFinitelyGenerated D) :
    IsExtendedFinitelyGenerated (C ×ˢ D) := by
  classical
  rcases hC with ⟨s, t, rfl⟩
  rcases hD with ⟨u, v, rfl⟩
  refine
    ⟨s.product u,
      (t.image (LinearMap.inl ℝ E F)) ∪ (v.image (LinearMap.inr ℝ E F)),
      ?_⟩
  calc
    (convexHull ℝ (↑s : Set E) + conicHull (↑t : Set E)) ×ˢ
        (convexHull ℝ (↑u : Set F) + conicHull (↑v : Set F))
        = (convexHull ℝ (↑s : Set E) ×ˢ convexHull ℝ (↑u : Set F)) +
            (conicHull (↑t : Set E) ×ˢ conicHull (↑v : Set F)) := by
              simpa using
                (prod_add_prod
                  (convexHull ℝ (↑s : Set E)) (conicHull (↑t : Set E))
                  (convexHull ℝ (↑u : Set F)) (conicHull (↑v : Set F)))
    _ = convexHull ℝ ((↑s : Set E) ×ˢ (↑u : Set F)) +
          conicHull
            (((LinearMap.inl ℝ E F) '' (↑t : Set E)) ∪
              ((LinearMap.inr ℝ E F) '' (↑v : Set F))) := by
            rw [convexHull_prod, conicHull_prod_eq_conicHull_inl_union_inr]
    _ = convexHull ℝ (↑(s.product u) : Set (E × F)) +
          conicHull
            (↑((t.image (LinearMap.inl ℝ E F)) ∪ (v.image (LinearMap.inr ℝ E F))) :
              Set (E × F)) := by
            simp

end Products

theorem closure_extendedConvexHull_finset
    (s t : Finset E) :
    closure (extendedConvexHull (↑s : Set E) (↑t : Set E)) =
      convexHull ℝ (↑s : Set E) + closure (conicHull (↑t : Set E)) := by
  have hscomp : IsCompact (convexHull ℝ (↑s : Set E)) := by
    exact s.finite_toSet.isCompact_convexHull
  apply le_antisymm
  · refine closure_minimal ?_ ?_
    · simpa [extendedConvexHull] using
        (add_subset_add (Subset.refl (convexHull ℝ (↑s : Set E))) subset_closure)
    · exact isClosed_closure.add_left_of_isCompact hscomp
  · intro x hx
    rcases hx with ⟨a, ha, b, hb, rfl⟩
    refine
      map_mem_closure₂
        (s := convexHull ℝ (↑s : Set E))
        (t := conicHull (↑t : Set E))
        (u := extendedConvexHull (↑s : Set E) (↑t : Set E))
        (f := fun u v : E => u + v) continuous_add ?_ hb ?_
    · simpa [hscomp.isClosed.closure_eq] using ha
    · intro u hu v hv
      exact Set.mem_add.2 ⟨u, hu, v, hv, rfl⟩

theorem IsExtendedFinitelyGenerated.exists_closure_generators
    {C : Set E} (hC : IsExtendedFinitelyGenerated C) :
    ∃ s t : Finset E,
      closure C = convexHull ℝ (↑s : Set E) + closure (conicHull (↑t : Set E)) := by
  rcases hC with ⟨s, t, rfl⟩
  exact ⟨s, t, closure_extendedConvexHull_finset s t⟩

/-- A closed polyhedral set in the generated-set sense is the sum of the convex
hull of finitely many ordinary points and the closure of the conic hull of
finitely many directions. -/
def IsClosedPolyhedral (C : Set E) : Prop :=
  ∃ s t : Finset E, C = convexHull ℝ (↑s : Set E) + closure (conicHull (↑t : Set E))

theorem IsClosedPolyhedral.isClosed {C : Set E} (hC : IsClosedPolyhedral C) :
    IsClosed C := by
  rcases hC with ⟨s, t, rfl⟩
  have hscomp : IsCompact (convexHull ℝ (↑s : Set E)) := by
    exact s.finite_toSet.isCompact_convexHull
  exact isClosed_closure.add_left_of_isCompact hscomp

theorem IsClosedPolyhedral.convex {C : Set E} (hC : IsClosedPolyhedral C) :
    Convex ℝ C := by
  rcases hC with ⟨s, t, rfl⟩
  exact (convex_convexHull ℝ (↑s : Set E)).add (convex_conicHull (↑t : Set E)).closure

theorem IsClosedPolyhedral.exists_nonempty_generators_of_nonempty
    {C : Set E} (hC : IsClosedPolyhedral C) (hCne : C.Nonempty) :
    ∃ s t : Finset E, s.Nonempty ∧
      C = convexHull ℝ (↑s : Set E) + closure (conicHull (↑t : Set E)) := by
  rcases hC with ⟨s, t, rfl⟩
  obtain rfl | hs := s.eq_empty_or_nonempty
  · simpa using hCne
  · exact ⟨s, t, hs, rfl⟩

theorem IsClosedPolyhedral.exists_closure_conicHull_generators_of_isCone
    {K : Set E} (hK : IsClosedPolyhedral K) (hKcone : IsCone K) :
    ∃ s : Finset E, K = closure (conicHull (↑s : Set E)) := by
  classical
  rcases hK with ⟨s, t, rfl⟩
  refine ⟨s ∪ t, ?_⟩
  apply le_antisymm
  · intro x hx
    rcases hx with ⟨a, ha, b, hb, rfl⟩
    have hsHull :
        convexHull ℝ (↑s : Set E) ⊆ closure (conicHull (↑(s ∪ t) : Set E)) :=
      convexHull_minimal
        (by
          intro y hy
          exact subset_closure <| subset_conicHull <| by
            simpa using (show y ∈ s ∪ t from Finset.mem_union.mpr (Or.inl hy)))
        ((convex_conicHull _).closure)
    have htHull :
        closure (conicHull (↑t : Set E)) ⊆ closure (conicHull (↑(s ∪ t) : Set E)) :=
      closure_minimal
        (Subset.trans
          (conicHull_mono <| by
            intro y hy
            simpa using (show y ∈ s ∪ t from Finset.mem_union.mpr (Or.inr hy)))
          subset_closure)
        isClosed_closure
    have hconeClosure :
        IsCone (closure (conicHull (↑(s ∪ t) : Set E))) := by
      rw [← horizonCone_conicHull_eq_closure (C := (↑(s ∪ t) : Set E))]
      exact isCone_horizonCone _
    exact add_mem_of_convex_isCone
      ((convex_conicHull _).closure)
      hconeClosure
      (hsHull ha)
      (htHull hb)
  · have hzero :
        (0 : E) ∈ convexHull ℝ (↑s : Set E) + closure (conicHull (↑t : Set E)) := by
        simpa using hKcone.1
    rcases hzero with ⟨a₀, ha₀, b₀, hb₀, hab₀⟩
    have hconeT : IsCone (closure (conicHull (↑t : Set E))) := by
      rw [← horizonCone_conicHull_eq_closure (C := (↑t : Set E))]
      exact isCone_horizonCone _
    refine closure_minimal ?_ ?_
    · refine conicHull_minimal
        (K := convexHull ℝ (↑s : Set E) + closure (conicHull (↑t : Set E)))
        ((convex_convexHull ℝ _).add ((convex_conicHull _).closure))
        hKcone
        ?_
      intro y hy
      rcases Finset.mem_union.mp hy with hy | hy
      · exact Set.mem_add.2
          ⟨y,
            subset_convexHull (𝕜 := ℝ) (s := (↑s : Set E)) <| by simpa using hy,
            0,
            subset_closure (zero_mem_conicHull (↑t : Set E)),
            by simp⟩
      · have hb₀y : b₀ + y ∈ closure (conicHull (↑t : Set E)) :=
          add_mem_of_convex_isCone
            ((convex_conicHull _).closure)
            hconeT
            hb₀
            (subset_closure <| subset_conicHull <| by simpa using hy)
        exact Set.mem_add.2
          ⟨a₀, ha₀, b₀ + y, hb₀y, by
            calc
              a₀ + (b₀ + y) = (a₀ + b₀) + y := by simp [add_assoc]
              _ = y := by simpa [hab₀]⟩
    · exact IsClosedPolyhedral.isClosed ⟨s, t, rfl⟩

theorem IsClosedPolyhedral.isFinitelyGeneratedCone_of_isCone
    [FiniteDimensional ℝ E]
    {K : Set E} (hK : IsClosedPolyhedral K) (hKcone : IsCone K) :
    IsFinitelyGeneratedCone K := by
  obtain ⟨s, hs⟩ := hK.exists_closure_conicHull_generators_of_isCone hKcone
  refine ⟨s, ?_⟩
  have hsclosed : IsClosed (conicHull (↑s : Set E)) :=
    isClosed_conicHull_finset (E := E) s
  simpa [hsclosed.closure_eq] using hs

theorem IsClosedPolyhedral.horizonCone_isClosedPolyhedral
    [FiniteDimensional ℝ E]
    {C : Set E} (hC : IsClosedPolyhedral C) (hCne : C.Nonempty) :
    IsClosedPolyhedral (RW.horizonCone C) := by
  obtain ⟨s, t, hs, rfl⟩ := hC.exists_nonempty_generators_of_nonempty hCne
  have hsne : (convexHull ℝ (↑s : Set E)).Nonempty := by
    rcases hs with ⟨x, hx⟩
    refine ⟨x, ?_⟩
    exact subset_convexHull (𝕜 := ℝ) (s := (↑s : Set E)) (by simpa using hx)
  have hsbdd : Bornology.IsBounded (convexHull ℝ (↑s : Set E)) := by
    refine (isBounded_convexHull).2 ?_
    simpa using s.finite_toSet.isBounded
  refine ⟨{0}, t, ?_⟩
  calc
    RW.horizonCone
        (convexHull ℝ (↑s : Set E) + closure (conicHull (↑t : Set E)))
        = RW.horizonCone (closure (conicHull (↑t : Set E))) := by
            simpa [add_comm] using
              (horizonCone_add_eq_of_bounded_right
                (C := closure (conicHull (↑t : Set E)))
                (D := convexHull ℝ (↑s : Set E)) hsne hsbdd)
    _ = closure (conicHull (↑t : Set E)) := by
          rw [horizonCone_closure, horizonCone_conicHull_eq_closure]
    _ = convexHull ℝ (↑({0} : Finset E) : Set E) + closure (conicHull (↑t : Set E)) := by
          simp

theorem IsClosedPolyhedral.exists_horizon_closure_conicHull_generators
    [FiniteDimensional ℝ E]
    {C : Set E} (hC : IsClosedPolyhedral C) (hCne : C.Nonempty) :
    ∃ t : Finset E, RW.horizonCone C = closure (conicHull (↑t : Set E)) := by
  exact
    (hC.horizonCone_isClosedPolyhedral hCne).exists_closure_conicHull_generators_of_isCone
      (isCone_horizonCone C)

theorem IsClosedPolyhedral.horizonCone_isFinitelyGeneratedCone
    [FiniteDimensional ℝ E]
    {C : Set E} (hC : IsClosedPolyhedral C) (hCne : C.Nonempty) :
    IsFinitelyGeneratedCone (RW.horizonCone C) :=
  (hC.horizonCone_isClosedPolyhedral hCne).isFinitelyGeneratedCone_of_isCone
    (isCone_horizonCone C)

section Products

variable {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]

theorem IsClosedPolyhedral.prod {C : Set E} {D : Set F}
    [FiniteDimensional ℝ E] [FiniteDimensional ℝ F]
    (hC : IsClosedPolyhedral C) (hD : IsClosedPolyhedral D) :
    IsClosedPolyhedral (C ×ˢ D) := by
  classical
  rcases hC with ⟨s, t, rfl⟩
  rcases hD with ⟨u, v, rfl⟩
  refine
    ⟨s.product u,
      (t.image (LinearMap.inl ℝ E F)) ∪ (v.image (LinearMap.inr ℝ E F)),
      ?_⟩
  calc
    (convexHull ℝ (↑s : Set E) + closure (conicHull (↑t : Set E))) ×ˢ
        (convexHull ℝ (↑u : Set F) + closure (conicHull (↑v : Set F)))
        = (convexHull ℝ (↑s : Set E) ×ˢ convexHull ℝ (↑u : Set F)) +
            (closure (conicHull (↑t : Set E)) ×ˢ closure (conicHull (↑v : Set F))) := by
              simpa using
                (prod_add_prod
                  (convexHull ℝ (↑s : Set E)) (closure (conicHull (↑t : Set E)))
                  (convexHull ℝ (↑u : Set F)) (closure (conicHull (↑v : Set F))))
    _ = convexHull ℝ ((↑s : Set E) ×ˢ (↑u : Set F)) +
          closure
            (conicHull
              (((LinearMap.inl ℝ E F) '' (↑t : Set E)) ∪
                ((LinearMap.inr ℝ E F) '' (↑v : Set F)))) := by
            rw [convexHull_prod, closure_conicHull_prod_eq_closure_conicHull_inl_union_inr]
    _ = convexHull ℝ (↑(s.product u) : Set (E × F)) +
          closure
            (conicHull
              (↑((t.image (LinearMap.inl ℝ E F)) ∪ (v.image (LinearMap.inr ℝ E F))) :
                Set (E × F))) := by
            simp

end Products

theorem IsExtendedFinitelyGenerated.closure_isClosedPolyhedral
    {C : Set E} (hC : IsExtendedFinitelyGenerated C) :
    IsClosedPolyhedral (closure C) := by
  rcases hC.exists_closure_generators with ⟨s, t, hst⟩
  exact ⟨s, t, hst⟩

theorem horizonCone_extendedConvexHull_finset_eq_horizonCone_conicHull
    [FiniteDimensional ℝ E]
    (s t : Finset E) (hs : s.Nonempty) :
    horizonCone (extendedConvexHull (↑s : Set E) (↑t : Set E)) =
      horizonCone (conicHull (↑t : Set E)) := by
  rcases hs with ⟨x, hx⟩
  have hsne : (convexHull ℝ (↑s : Set E)).Nonempty := by
    have hx' : x ∈ (↑s : Set E) := by
      simpa using hx
    refine ⟨x, ?_⟩
    exact (subset_convexHull (𝕜 := ℝ) (s := (↑s : Set E))) hx'
  have hsbdd : Bornology.IsBounded (convexHull ℝ (↑s : Set E)) := by
    refine (isBounded_convexHull).2 ?_
    simpa using s.finite_toSet.isBounded
  simpa [extendedConvexHull, add_comm] using
    (horizonCone_add_eq_of_bounded_right
      (C := conicHull (↑t : Set E))
      (D := convexHull ℝ (↑s : Set E)) hsne hsbdd)

theorem horizonCone_extendedConvexHull_finset_eq_conicHull
    [FiniteDimensional ℝ E]
    (s t : Finset E) (hs : s.Nonempty)
    (htclosed : IsClosed (conicHull (↑t : Set E))) :
    horizonCone (extendedConvexHull (↑s : Set E) (↑t : Set E)) =
      conicHull (↑t : Set E) := by
  rw [horizonCone_extendedConvexHull_finset_eq_horizonCone_conicHull s t hs,
    horizonCone_eq_self_of_isClosed_isCone htclosed (isCone_conicHull _)]

theorem IsExtendedFinitelyGenerated.exists_nonempty_generators_of_nonempty
    {C : Set E} (hC : IsExtendedFinitelyGenerated C) (hCne : C.Nonempty) :
    ∃ s t : Finset E, s.Nonempty ∧ C = extendedConvexHull (↑s : Set E) (↑t : Set E) := by
  rcases hC with ⟨s, t, rfl⟩
  obtain rfl | hs := s.eq_empty_or_nonempty
  · simpa [extendedConvexHull] using hCne
  · exact ⟨s, t, hs, rfl⟩

theorem IsExtendedFinitelyGenerated.exists_horizon_generators_of_nonempty
    [FiniteDimensional ℝ E]
    {C : Set E} (hC : IsExtendedFinitelyGenerated C) (hCne : C.Nonempty) :
    ∃ t : Finset E, horizonCone C = horizonCone (conicHull (↑t : Set E)) := by
  obtain ⟨s, t, hs, rfl⟩ := hC.exists_nonempty_generators_of_nonempty hCne
  exact ⟨t, horizonCone_extendedConvexHull_finset_eq_horizonCone_conicHull s t hs⟩

section LinearImages

variable {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]

private theorem LinearMap.image_add_set (L : E →ₗ[ℝ] F) (A B : Set E) :
    L '' (A + B) = L '' A + L '' B := by
  ext y
  constructor
  · rintro ⟨x, hx, rfl⟩
    rcases hx with ⟨a, ha, b, hb, rfl⟩
    exact Set.mem_add.2 ⟨L a, ⟨a, ha, rfl⟩, L b, ⟨b, hb, rfl⟩, by simp⟩
  · rintro ⟨u, ⟨a, ha, rfl⟩, v, ⟨b, hb, rfl⟩, rfl⟩
    exact ⟨a + b, Set.mem_add.2 ⟨a, ha, b, hb, rfl⟩, by simp⟩

open Classical in
private theorem LinearMap.image_finset_coe (L : E →ₗ[ℝ] F) (s : Finset E) :
    L '' (↑s : Set E) = (↑(s.image L) : Set F) := by
  classical
  ext y
  constructor
  · rintro ⟨x, hx, rfl⟩
    simpa using (Finset.mem_image.mpr ⟨x, hx, rfl⟩ : L x ∈ s.image L)
  · intro hy
    rcases Finset.mem_image.mp (by simpa using hy) with ⟨x, hx, rfl⟩
    exact ⟨x, hx, rfl⟩

theorem LinearMap.image_extendedConvexHull (L : E →ₗ[ℝ] F) (A B : Set E) :
    L '' extendedConvexHull A B = extendedConvexHull (L '' A) (L '' B) := by
  rw [extendedConvexHull, LinearMap.image_add_set, LinearMap.image_convexHull,
    RW.LinearMap.image_conicHull, extendedConvexHull]

theorem IsExtendedFinitelyGenerated.linear_image {C : Set E}
    (hC : IsExtendedFinitelyGenerated C) (L : E →ₗ[ℝ] F) :
    IsExtendedFinitelyGenerated (L '' C) := by
  classical
  rcases hC with ⟨s, t, rfl⟩
  refine ⟨s.image L, t.image L, ?_⟩
  calc
    L '' extendedConvexHull (↑s : Set E) (↑t : Set E) =
        extendedConvexHull (L '' (↑s : Set E)) (L '' (↑t : Set E)) := by
          simpa using
            (LinearMap.image_extendedConvexHull
              (E := E) (F := F) L (↑s : Set E) (↑t : Set E))
    _ = extendedConvexHull (↑(s.image L) : Set F) (↑(t.image L) : Set F) := by
          rw [LinearMap.image_finset_coe, LinearMap.image_finset_coe]

end LinearImages

section AffineImages

variable {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]

private theorem AffineMap.image_add_conicHull
    (f : E →ᵃ[ℝ] F) (A B : Set E) :
    f '' (A + conicHull B) = f '' A + f.linear '' conicHull B := by
  ext y
  constructor
  · rintro ⟨x, hx, rfl⟩
    rcases hx with ⟨a, ha, b, hb, rfl⟩
    refine Set.mem_add.2 ?_
    refine ⟨f a, ⟨a, ha, rfl⟩, f.linear b, ⟨b, hb, rfl⟩, ?_⟩
    simpa [vadd_eq_add, add_comm, add_left_comm, add_assoc] using (f.map_vadd a b).symm
  · rintro ⟨u, ⟨a, ha, rfl⟩, v, ⟨b, hb, rfl⟩, huv⟩
    refine ⟨a + b, Set.mem_add.2 ⟨a, ha, b, hb, rfl⟩, ?_⟩
    rw [← huv]
    simpa [vadd_eq_add, add_comm, add_left_comm, add_assoc] using f.map_vadd a b

open Classical in
private theorem AffineMap.image_finset_coe (f : E →ᵃ[ℝ] F) (s : Finset E) :
    f '' (↑s : Set E) = (↑(s.image f) : Set F) := by
  classical
  ext y
  constructor
  · rintro ⟨x, hx, rfl⟩
    simpa using (Finset.mem_image.mpr ⟨x, hx, rfl⟩ : f x ∈ s.image f)
  · intro hy
    rcases Finset.mem_image.mp (by simpa using hy) with ⟨x, hx, rfl⟩
    exact ⟨x, hx, rfl⟩

theorem AffineMap.image_extendedConvexHull
    (f : E →ᵃ[ℝ] F) (A B : Set E) :
    f '' extendedConvexHull A B =
      extendedConvexHull (f '' A) (f.linear '' B) := by
  rw [extendedConvexHull, AffineMap.image_add_conicHull, AffineMap.image_convexHull,
    RW.LinearMap.image_conicHull, extendedConvexHull]

theorem IsExtendedFinitelyGenerated.affine_image {C : Set E}
    (hC : IsExtendedFinitelyGenerated C) (f : E →ᵃ[ℝ] F) :
    IsExtendedFinitelyGenerated (f '' C) := by
  classical
  rcases hC with ⟨s, t, rfl⟩
  refine ⟨s.image f, t.image f.linear, ?_⟩
  calc
    f '' extendedConvexHull (↑s : Set E) (↑t : Set E) =
        extendedConvexHull (f '' (↑s : Set E)) (f.linear '' (↑t : Set E)) := by
          simpa using
            (AffineMap.image_extendedConvexHull
              (E := E) (F := F) f (↑s : Set E) (↑t : Set E))
    _ = extendedConvexHull (↑(s.image f) : Set F) (↑(t.image f.linear) : Set F) := by
          rw [AffineMap.image_finset_coe, LinearMap.image_finset_coe]

end AffineImages

/-- A Chapter 3 polyhedral set is one that admits a finite ordinary-points-plus-
directions representation. This is the project-level wrapper for the generated-
set language used in the polyhedral tail of the chapter. -/
abbrev IsPolyhedral (C : Set E) : Prop :=
  IsExtendedFinitelyGenerated C

theorem IsPolyhedral.convex {C : Set E} (hC : IsPolyhedral C) :
    Convex ℝ C :=
  IsExtendedFinitelyGenerated.convex hC

theorem IsFinitelyGeneratedCone.isPolyhedral {K : Set E}
    (hK : IsFinitelyGeneratedCone K) :
    IsPolyhedral K :=
  IsFinitelyGeneratedCone.isExtendedFinitelyGenerated hK

theorem IsClosedPolyhedral.isPolyhedral
    [FiniteDimensional ℝ E]
    {C : Set E} (hC : IsClosedPolyhedral C) :
    IsPolyhedral C := by
  rcases hC with ⟨s, t, rfl⟩
  refine ⟨s, t, ?_⟩
  have htclosed : IsClosed (conicHull (↑t : Set E)) :=
    isClosed_conicHull_finset (E := E) t
  simpa [extendedConvexHull, htclosed.closure_eq]

theorem IsPolyhedral.isFinitelyGeneratedCone {K : Set E}
    (hK : IsPolyhedral K) (hKcone : IsCone K) :
    IsFinitelyGeneratedCone K := by
  classical
  rcases hK with ⟨s, t, rfl⟩
  refine ⟨s ∪ t, ?_⟩
  apply le_antisymm
  · intro x hx
    rcases hx with ⟨a, ha, b, hb, rfl⟩
    have hsHull :
        convexHull ℝ (↑s : Set E) ⊆ conicHull (↑(s ∪ t) : Set E) :=
      convexHull_minimal
        (by
          intro y hy
          exact subset_conicHull <| by
            simpa using (show y ∈ s ∪ t from Finset.mem_union.mpr (Or.inl hy)))
        (convex_conicHull _)
    have htHull :
        conicHull (↑t : Set E) ⊆ conicHull (↑(s ∪ t) : Set E) :=
      conicHull_mono <| by
        intro y hy
        simpa using (show y ∈ s ∪ t from Finset.mem_union.mpr (Or.inr hy))
    exact add_mem_of_convex_isCone
      (convex_conicHull _)
      (isCone_conicHull _)
      (hsHull ha)
      (htHull hb)
  · have hzero :
        (0 : E) ∈ extendedConvexHull (↑s : Set E) (↑t : Set E) := by
        simpa [extendedConvexHull] using hKcone.1
    rcases hzero with ⟨a₀, ha₀, b₀, hb₀, hab₀⟩
    refine conicHull_minimal
      (K := extendedConvexHull (↑s : Set E) (↑t : Set E))
      (convex_extendedConvexHull (↑s : Set E) (↑t : Set E))
      hKcone
      ?_
    intro y hy
    rcases Finset.mem_union.mp hy with hy | hy
    · exact Set.mem_add.2
        ⟨y,
          subset_convexHull (𝕜 := ℝ) (s := (↑s : Set E)) <| by simpa using hy,
          0,
          zero_mem_conicHull _,
          by simp⟩
    · have hbxt : b₀ + y ∈ conicHull (↑t : Set E) := by
        exact add_mem_of_convex_isCone
          (convex_conicHull _)
          (isCone_conicHull _)
          hb₀
          (subset_conicHull <| by simpa using hy)
      have hab₀' : a₀ + b₀ = 0 := hab₀
      exact Set.mem_add.2
        ⟨a₀, ha₀, b₀ + y, hbxt, by
          calc
            a₀ + (b₀ + y) = (a₀ + b₀) + y := by simp [add_assoc]
            _ = y := by simpa [hab₀']⟩

theorem IsPolyhedral.submodule_span_finset (s : Finset E) :
    IsPolyhedral ((Submodule.span ℝ (↑s : Set E) : Set E)) :=
  (IsFinitelyGeneratedCone.submodule_span_finset (E := E) s).isPolyhedral

theorem isPolyhedral_iff_isFinitelyGeneratedCone_of_isCone {K : Set E}
    (hKcone : IsCone K) :
    IsPolyhedral K ↔ IsFinitelyGeneratedCone K := by
  constructor
  · intro hK
    exact hK.isFinitelyGeneratedCone hKcone
  · intro hK
    exact hK.isPolyhedral

theorem IsPolyhedral.add {C D : Set E}
    (hC : IsPolyhedral C) (hD : IsPolyhedral D) :
    IsPolyhedral (C + D) :=
  IsExtendedFinitelyGenerated.add hC hD

theorem IsPolyhedral.prod {F : Type*}
    [NormedAddCommGroup F] [NormedSpace ℝ F]
    {C : Set E} {D : Set F}
    (hC : IsPolyhedral C) (hD : IsPolyhedral D) :
    IsPolyhedral (C ×ˢ D) :=
  IsExtendedFinitelyGenerated.prod hC hD

theorem IsPolyhedral.linear_image {F : Type*}
    [NormedAddCommGroup F] [NormedSpace ℝ F]
    {C : Set E} (hC : IsPolyhedral C) (L : E →ₗ[ℝ] F) :
    IsPolyhedral (L '' C) :=
  IsExtendedFinitelyGenerated.linear_image hC L

theorem IsPolyhedral.affine_image {F : Type*}
    [NormedAddCommGroup F] [NormedSpace ℝ F]
    {C : Set E} (hC : IsPolyhedral C) (f : E →ᵃ[ℝ] F) :
    IsPolyhedral (f '' C) :=
  IsExtendedFinitelyGenerated.affine_image hC f

theorem IsPolyhedral.exists_generators {C : Set E} (hC : IsPolyhedral C) :
    ∃ s t : Finset E, C = extendedConvexHull (↑s : Set E) (↑t : Set E) :=
  hC

theorem IsPolyhedral.exists_closure_generators {C : Set E} (hC : IsPolyhedral C) :
    ∃ s t : Finset E,
      closure C = convexHull ℝ (↑s : Set E) + closure (conicHull (↑t : Set E)) :=
  IsExtendedFinitelyGenerated.exists_closure_generators hC

theorem IsPolyhedral.closure_isClosedPolyhedral {C : Set E} (hC : IsPolyhedral C) :
    IsClosedPolyhedral (closure C) :=
  IsExtendedFinitelyGenerated.closure_isClosedPolyhedral hC

theorem IsPolyhedral.isClosedPolyhedral_of_isClosed {C : Set E}
    (hC : IsPolyhedral C) (hclosed : IsClosed C) :
    IsClosedPolyhedral C := by
  simpa [hclosed.closure_eq] using hC.closure_isClosedPolyhedral

theorem IsFinitelyGeneratedCone.isClosedPolyhedral
    [FiniteDimensional ℝ E] {K : Set E}
    (hK : IsFinitelyGeneratedCone K) :
    IsClosedPolyhedral K :=
  hK.isPolyhedral.isClosedPolyhedral_of_isClosed hK.isClosed

theorem IsPolyhedral.submodule
    [FiniteDimensional ℝ E] (S : Submodule ℝ E) :
    IsPolyhedral (S : Set E) :=
  (IsFinitelyGeneratedCone.submodule S).isPolyhedral

theorem IsClosedPolyhedral.submodule
    [FiniteDimensional ℝ E] (S : Submodule ℝ E) :
    IsClosedPolyhedral (S : Set E) :=
  (IsFinitelyGeneratedCone.submodule S).isClosedPolyhedral

theorem IsPolyhedral.ker_linearMap
    {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]
    [FiniteDimensional ℝ E] [FiniteDimensional ℝ F]
    (L : F →ₗ[ℝ] E) :
    IsPolyhedral (LinearMap.ker L : Set F) :=
  (IsFinitelyGeneratedCone.ker_linearMap (E := E) L).isPolyhedral

theorem IsClosedPolyhedral.ker_linearMap
    {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]
    [FiniteDimensional ℝ E] [FiniteDimensional ℝ F]
    (L : F →ₗ[ℝ] E) :
    IsClosedPolyhedral (LinearMap.ker L : Set F) :=
  (IsFinitelyGeneratedCone.ker_linearMap (E := E) L).isClosedPolyhedral

theorem IsPolyhedral.isClosedPolyhedral_of_isCone
    [FiniteDimensional ℝ E] {K : Set E}
    (hK : IsPolyhedral K) (hcone : IsCone K) :
    IsClosedPolyhedral K :=
  (hK.isFinitelyGeneratedCone hcone).isClosedPolyhedral

theorem IsFinitelyGeneratedCone.isClosedPolyhedral_of_isPointed
    [FiniteDimensional ℝ E] {K : Set E}
    (hK : IsFinitelyGeneratedCone K) (hpointed : IsPointed K) :
    IsClosedPolyhedral K :=
  hK.isPolyhedral.isClosedPolyhedral_of_isClosed <|
    hK.isClosed_of_isPointed hpointed

theorem IsPolyhedral.isClosedPolyhedral_of_isCone_of_isPointed
    [FiniteDimensional ℝ E] {K : Set E}
    (hK : IsPolyhedral K) (hcone : IsCone K) (hpointed : IsPointed K) :
    IsClosedPolyhedral K := by
  exact (hK.isFinitelyGeneratedCone hcone).isClosedPolyhedral_of_isPointed hpointed

theorem IsClosedPolyhedral.submodule_span_finset (s : Finset E) :
    IsClosedPolyhedral ((Submodule.span ℝ (↑s : Set E) : Set E)) := by
  let p : Submodule ℝ E := Submodule.span ℝ (↑s : Set E)
  haveI : FiniteDimensional ℝ p := FiniteDimensional.span_of_finite ℝ s.finite_toSet
  exact
    (IsPolyhedral.submodule_span_finset (E := E) s).isClosedPolyhedral_of_isClosed
      (C := (p : Set E)) p.closed_of_finiteDimensional

theorem IsPolyhedral.Ici_zero : IsPolyhedral (Set.Ici (0 : ℝ)) := by
  simpa [Finset.coe_singleton, conicHull_singleton_one_eq_Ici_zero] using
    (show IsPolyhedral (conicHull (↑({1} : Finset ℝ) : Set ℝ)) from
      (show IsFinitelyGeneratedCone (conicHull (↑({1} : Finset ℝ) : Set ℝ)) from
        ⟨{1}, rfl⟩).isPolyhedral)

theorem IsClosedPolyhedral.Ici_zero : IsClosedPolyhedral (Set.Ici (0 : ℝ)) := by
  exact IsPolyhedral.Ici_zero.isClosedPolyhedral_of_isClosed isClosed_Ici

theorem IsPolyhedral.Iic_zero : IsPolyhedral (Set.Iic (0 : ℝ)) := by
  simpa [Finset.coe_singleton, conicHull_singleton_neg_one_eq_Iic_zero] using
    (show IsPolyhedral (conicHull (↑({-1} : Finset ℝ) : Set ℝ)) from
      (show IsFinitelyGeneratedCone (conicHull (↑({-1} : Finset ℝ) : Set ℝ)) from
        ⟨{-1}, rfl⟩).isPolyhedral)

theorem IsClosedPolyhedral.Iic_zero : IsClosedPolyhedral (Set.Iic (0 : ℝ)) := by
  exact IsPolyhedral.Iic_zero.isClosedPolyhedral_of_isClosed isClosed_Iic

section ClosedImages

variable {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]
variable [FiniteDimensional ℝ E] [FiniteDimensional ℝ F]

theorem IsClosedPolyhedral.linear_image {C : Set E}
    (hC : IsClosedPolyhedral C) (L : E →ₗ[ℝ] F) :
    IsClosedPolyhedral (L '' C) := by
  classical
  rcases hC with ⟨s, t, rfl⟩
  refine ⟨s.image L, t.image L, ?_⟩
  have htclosed : IsClosed (conicHull (↑t : Set E)) :=
    isClosed_conicHull_finset (E := E) t
  have htclosed' : IsClosed (conicHull (↑(t.image L) : Set F)) :=
    isClosed_conicHull_finset (E := F) (t.image L)
  calc
    L '' (convexHull ℝ (↑s : Set E) + closure (conicHull (↑t : Set E)))
        = L '' extendedConvexHull (↑s : Set E) (↑t : Set E) := by
            simp [extendedConvexHull, htclosed.closure_eq]
    _ = extendedConvexHull (L '' (↑s : Set E)) (L '' (↑t : Set E)) := by
          simpa using
            (LinearMap.image_extendedConvexHull
              (L := L) (A := (↑s : Set E)) (B := (↑t : Set E)))
    _ = convexHull ℝ (↑(s.image L) : Set F) + conicHull (↑(t.image L) : Set F) := by
          rw [extendedConvexHull, LinearMap.image_finset_coe, LinearMap.image_finset_coe]
    _ = convexHull ℝ (↑(s.image L) : Set F) + closure (conicHull (↑(t.image L) : Set F)) := by
          rw [htclosed'.closure_eq]

theorem IsClosedPolyhedral.affine_image {C : Set E}
    (hC : IsClosedPolyhedral C) (f : E →ᵃ[ℝ] F) :
    IsClosedPolyhedral (f '' C) := by
  classical
  rcases hC with ⟨s, t, rfl⟩
  refine ⟨s.image f, t.image f.linear, ?_⟩
  have htclosed : IsClosed (conicHull (↑t : Set E)) :=
    isClosed_conicHull_finset (E := E) t
  have htclosed' : IsClosed (conicHull (↑(t.image f.linear) : Set F)) :=
    isClosed_conicHull_finset (E := F) (t.image f.linear)
  calc
    f '' (convexHull ℝ (↑s : Set E) + closure (conicHull (↑t : Set E)))
        = f '' extendedConvexHull (↑s : Set E) (↑t : Set E) := by
            simp [extendedConvexHull, htclosed.closure_eq]
    _ = extendedConvexHull (f '' (↑s : Set E)) (f.linear '' (↑t : Set E)) := by
          simpa using
            (AffineMap.image_extendedConvexHull
              (f := f) (A := (↑s : Set E)) (B := (↑t : Set E)))
    _ = convexHull ℝ (↑(s.image f) : Set F) + conicHull (↑(t.image f.linear) : Set F) := by
          rw [extendedConvexHull, AffineMap.image_finset_coe, LinearMap.image_finset_coe]
    _ = convexHull ℝ (↑(s.image f) : Set F) +
          closure (conicHull (↑(t.image f.linear) : Set F)) := by
            rw [htclosed'.closure_eq]

end ClosedImages

theorem IsClosedPolyhedral.add
    [FiniteDimensional ℝ E] {C D : Set E}
    (hC : IsClosedPolyhedral C) (hD : IsClosedPolyhedral D) :
    IsClosedPolyhedral (C + D) := by
  let L : E × E →ₗ[ℝ] E := LinearMap.fst ℝ E E + LinearMap.snd ℝ E E
  have himage : L '' (C ×ˢ D) = C + D := by
    ext x
    constructor
    · rintro ⟨p, hp, rfl⟩
      exact Set.mem_add.2 ⟨p.1, hp.1, p.2, hp.2, by simp [L]⟩
    · rintro ⟨y, hy, z, hz, rfl⟩
      exact ⟨(y, z), ⟨hy, hz⟩, by simp [L]⟩
  rw [← himage]
  exact (hC.prod hD).linear_image L

section FiniteDimensionalRanges

variable {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F]

theorem IsPolyhedral.range_linearMap (L : F →ₗ[ℝ] E) :
    IsPolyhedral (LinearMap.range L : Set E) := by
  classical
  let b := Module.finBasis ℝ F
  have hgen : (↑(Finset.univ.image b) : Set F) = Set.range b := by
    ext x
    simp
  have htop :
      ((Submodule.span ℝ (↑(Finset.univ.image b) : Set F)) : Set F) =
        (((⊤ : Submodule ℝ F)) : Set F) := by
    calc
      ((Submodule.span ℝ (↑(Finset.univ.image b) : Set F)) : Set F)
          = (Submodule.span ℝ (Set.range b) : Set F) := by rw [hgen]
      _ = (((⊤ : Submodule ℝ F)) : Set F) := by
            simpa using congrArg (fun p : Submodule ℝ F => (p : Set F)) (b.span_eq)
  have himage :
      L '' ((((⊤ : Submodule ℝ F)) : Set F)) = (LinearMap.range L : Set E) := by
    ext y
    constructor
    · rintro ⟨x, hx, rfl⟩
      exact ⟨x, rfl⟩
    · rintro ⟨x, rfl⟩
      exact ⟨x, by simp, rfl⟩
  rw [← himage, ← htop]
  exact IsPolyhedral.linear_image (IsPolyhedral.submodule_span_finset (E := F) (Finset.univ.image b)) L

theorem IsClosedPolyhedral.range_linearMap (L : F →ₗ[ℝ] E) :
    IsClosedPolyhedral (LinearMap.range L : Set E) := by
  exact
    (IsPolyhedral.range_linearMap (E := E) L).isClosedPolyhedral_of_isClosed
      (LinearMap.range L).closed_of_finiteDimensional

end FiniteDimensionalRanges

theorem IsPolyhedral.univ [FiniteDimensional ℝ E] : IsPolyhedral (Set.univ : Set E) := by
  simpa using IsPolyhedral.range_linearMap (E := E) (LinearMap.id : E →ₗ[ℝ] E)

theorem IsClosedPolyhedral.univ [FiniteDimensional ℝ E] :
    IsClosedPolyhedral (Set.univ : Set E) := by
  simpa using IsClosedPolyhedral.range_linearMap (E := E) (LinearMap.id : E →ₗ[ℝ] E)

theorem IsClosedPolyhedral.diagonal [FiniteDimensional ℝ E] :
    IsClosedPolyhedral ({p : E × E | p.1 = p.2} : Set (E × E)) := by
  let Δ : E →ₗ[ℝ] E × E := (LinearMap.id : E →ₗ[ℝ] E).prod (LinearMap.id : E →ₗ[ℝ] E)
  have hdiag : (LinearMap.range Δ : Set (E × E)) = {p : E × E | p.1 = p.2} := by
    ext p
    constructor
    · rintro ⟨x, hx⟩
      cases hx
      simp [Δ]
    · intro hp
      refine ⟨p.1, ?_⟩
      ext <;> simpa [Δ] using hp
  rw [← hdiag]
  exact IsClosedPolyhedral.range_linearMap (E := E × E) Δ

section LinearEquivImages

variable {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]

theorem IsClosedPolyhedral.image_linearEquiv {C : Set E}
    (hC : IsClosedPolyhedral C) (e : E ≃L[ℝ] F) :
    IsClosedPolyhedral (e '' C) := by
  classical
  rcases hC with ⟨s, t, rfl⟩
  refine ⟨s.image e, t.image e, ?_⟩
  calc
    e '' (convexHull ℝ (↑s : Set E) + closure (conicHull (↑t : Set E)))
        = e '' (convexHull ℝ (↑s : Set E)) + e '' closure (conicHull (↑t : Set E)) := by
            simpa using
              (LinearMap.image_add_set
                (L := (e : E →ₗ[ℝ] F))
                (A := convexHull ℝ (↑s : Set E))
                (B := closure (conicHull (↑t : Set E))))
    _ = convexHull ℝ (e '' (↑s : Set E)) + closure (conicHull (e '' (↑t : Set E))) := by
          simp only [e.image_closure]
          congr 1
          · simpa using
              (LinearMap.image_convexHull (𝕜 := ℝ) (f := (e : E →ₗ[ℝ] F)) (s := (↑s : Set E)))
          · simpa using
              congrArg closure
                (RW.LinearMap.image_conicHull (L := (e : E →ₗ[ℝ] F)) (C := (↑t : Set E)))
    _ = convexHull ℝ (↑(s.image e) : Set F) + closure (conicHull (↑(t.image e) : Set F)) := by
          congr 1 <;> ext y <;> simp

end LinearEquivImages

section Translations

private theorem image_add_right_set (A B : Set E) (u : E) :
    (fun x : E => x + u) '' (A + B) = ((fun x : E => x + u) '' A) + B := by
  ext y
  constructor
  · rintro ⟨x, hx, rfl⟩
    rcases hx with ⟨a, ha, b, hb, rfl⟩
    exact Set.mem_add.2 ⟨a + u, ⟨a, ha, rfl⟩, b, hb, by simp [add_assoc, add_left_comm, add_comm]⟩
  · rintro ⟨x, ⟨a, ha, rfl⟩, b, hb, hxb⟩
    refine ⟨a + b, Set.mem_add.2 ⟨a, ha, b, hb, rfl⟩, ?_⟩
    simpa [add_assoc, add_left_comm, add_comm] using hxb

theorem IsClosedPolyhedral.image_add_right {C : Set E}
    (hC : IsClosedPolyhedral C) (u : E) :
    IsClosedPolyhedral ((fun x : E => x + u) '' C) := by
  classical
  rcases hC with ⟨s, t, rfl⟩
  refine ⟨s.image fun x => x + u, t, ?_⟩
  calc
    (fun x : E => x + u) '' (convexHull ℝ (↑s : Set E) + closure (conicHull (↑t : Set E)))
        = (fun x : E => x + u) '' convexHull ℝ (↑s : Set E) + closure (conicHull (↑t : Set E)) := by
            simpa using
              image_add_right_set
                (A := convexHull ℝ (↑s : Set E))
                (B := closure (conicHull (↑t : Set E))) u
    _ = convexHull ℝ ((fun x : E => x + u) '' (↑s : Set E)) + closure (conicHull (↑t : Set E)) := by
          congr 1
          simpa [add_comm] using
            (AffineMap.image_convexHull
              (f := (AffineEquiv.constVAdd ℝ E u : E →ᵃ[ℝ] E))
              (s := (↑s : Set E)))
    _ = convexHull ℝ (↑(s.image fun x => x + u) : Set E) + closure (conicHull (↑t : Set E)) := by
          congr 1
          ext y
          simp

end Translations

section LinearPreimages

variable {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]

theorem IsPolyhedral.preimage_linearMap_of_surjective
    [FiniteDimensional ℝ E] [FiniteDimensional ℝ F]
    {C : Set E} (hC : IsPolyhedral C) (L : F →ₗ[ℝ] E)
    (hL : LinearMap.range L = ⊤) :
    IsPolyhedral (L ⁻¹' C) := by
  let Lc : F →L[ℝ] E := L.toContinuousLinearMap
  obtain ⟨r, hr⟩ := ContinuousLinearMap.exists_right_inverse_of_surjective Lc (by
    simpa using hL)
  have hr' : Function.RightInverse r Lc := by
    intro x
    simpa using congrArg (fun g : E →L[ℝ] E => g x) hr
  let e : F ≃L[ℝ] E × LinearMap.ker L :=
    ContinuousLinearEquiv.equivOfRightInverse Lc r hr'
  have hpre :
      L ⁻¹' C = e ⁻¹' (C ×ˢ (Set.univ : Set (LinearMap.ker L))) := by
    ext x
    constructor
    · intro hx
      change e x ∈ C ×ˢ (Set.univ : Set (LinearMap.ker L))
      exact ⟨by simpa [e, Lc] using hx, by simp⟩
    · intro hx
      change e x ∈ C ×ˢ (Set.univ : Set (LinearMap.ker L)) at hx
      exact by simpa [e, Lc] using hx.1
  rw [hpre, ← e.image_symm_eq_preimage]
  exact (hC.prod (IsPolyhedral.univ (E := LinearMap.ker L))).linear_image (e.symm : _ →ₗ[ℝ] F)

theorem IsClosedPolyhedral.preimage_linearMap_of_surjective
    [FiniteDimensional ℝ E] [FiniteDimensional ℝ F]
    {C : Set E} (hC : IsClosedPolyhedral C) (L : F →ₗ[ℝ] E)
    (hL : LinearMap.range L = ⊤) :
    IsClosedPolyhedral (L ⁻¹' C) := by
  let Lc : F →L[ℝ] E := L.toContinuousLinearMap
  obtain ⟨r, hr⟩ := ContinuousLinearMap.exists_right_inverse_of_surjective Lc (by
    simpa using hL)
  have hr' : Function.RightInverse r Lc := by
    intro x
    simpa using congrArg (fun g : E →L[ℝ] E => g x) hr
  let e : F ≃L[ℝ] E × LinearMap.ker L :=
    ContinuousLinearEquiv.equivOfRightInverse Lc r hr'
  have hpre :
      L ⁻¹' C = e ⁻¹' (C ×ˢ (Set.univ : Set (LinearMap.ker L))) := by
    ext x
    constructor
    · intro hx
      change e x ∈ C ×ˢ (Set.univ : Set (LinearMap.ker L))
      exact ⟨by simpa [e, Lc] using hx, by simp⟩
    · intro hx
      change e x ∈ C ×ˢ (Set.univ : Set (LinearMap.ker L)) at hx
      exact by simpa [e, Lc] using hx.1
  rw [hpre, ← e.image_symm_eq_preimage]
  exact (hC.prod (IsClosedPolyhedral.univ (E := LinearMap.ker L))).image_linearEquiv e.symm

theorem IsFinitelyGeneratedCone.preimage_linearMap_of_surjective
    [FiniteDimensional ℝ E] [FiniteDimensional ℝ F]
    {K : Set E} (hK : IsFinitelyGeneratedCone K) (L : F →ₗ[ℝ] E)
    (hL : LinearMap.range L = ⊤) :
    IsFinitelyGeneratedCone (L ⁻¹' K) := by
  have hpre : IsClosedPolyhedral (L ⁻¹' K) :=
    hK.isClosedPolyhedral.preimage_linearMap_of_surjective L hL
  have hcone : IsCone (L ⁻¹' K) :=
    LinearMap.isCone_preimage L hK.isCone
  exact hpre.isFinitelyGeneratedCone_of_isCone hcone

end LinearPreimages

section LinearInjections

variable {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]

theorem IsPolyhedral.preimage_linearMap_of_injective_of_inter_range
    (L : F →ₗ[ℝ] E) {C : Set E}
    (hinter : IsPolyhedral (C ∩ (LinearMap.range L : Set E)))
    (hL : LinearMap.ker L = ⊥) :
    IsPolyhedral (L ⁻¹' C) := by
  let r : E →ₗ[ℝ] F := L.leftInverse
  have hr : r.comp L = LinearMap.id := L.leftInverse_comp_of_inj hL
  have himage : r '' (C ∩ (LinearMap.range L : Set E)) = L ⁻¹' C := by
    ext x
    constructor
    · rintro ⟨y, ⟨hyC, hyR⟩, rfl⟩
      rcases hyR with ⟨z, rfl⟩
      have hz : r (L z) = z := by
        simpa using LinearMap.congr_fun hr z
      change L (r (L z)) ∈ C
      simpa [hz] using hyC
    · intro hx
      refine ⟨L x, ⟨hx, ⟨x, rfl⟩⟩, ?_⟩
      simpa using LinearMap.congr_fun hr x
  rw [← himage]
  exact hinter.linear_image r

theorem IsClosedPolyhedral.preimage_linearMap_of_injective_of_inter_range
    [FiniteDimensional ℝ E] [FiniteDimensional ℝ F]
    (L : F →ₗ[ℝ] E) {C : Set E}
    (hinter : IsClosedPolyhedral (C ∩ (LinearMap.range L : Set E)))
    (hL : LinearMap.ker L = ⊥) :
    IsClosedPolyhedral (L ⁻¹' C) := by
  let r : E →ₗ[ℝ] F := L.leftInverse
  have hr : r.comp L = LinearMap.id := L.leftInverse_comp_of_inj hL
  have himage : r '' (C ∩ (LinearMap.range L : Set E)) = L ⁻¹' C := by
    ext x
    constructor
    · rintro ⟨y, ⟨hyC, hyR⟩, rfl⟩
      rcases hyR with ⟨z, rfl⟩
      have hz : r (L z) = z := by
        simpa using LinearMap.congr_fun hr z
      change L (r (L z)) ∈ C
      simpa [hz] using hyC
    · intro hx
      refine ⟨L x, ⟨hx, ⟨x, rfl⟩⟩, ?_⟩
      simpa using LinearMap.congr_fun hr x
  rw [← himage]
  exact hinter.linear_image r

theorem IsClosedPolyhedral.inter_of_prod_inter_diagonal
    [FiniteDimensional ℝ E] {C D : Set E}
    (hdiag :
      IsClosedPolyhedral ((C ×ˢ D) ∩ {p : E × E | p.1 = p.2})) :
    IsClosedPolyhedral (C ∩ D) := by
  let Δ : E →ₗ[ℝ] E × E := (LinearMap.id : E →ₗ[ℝ] E).prod (LinearMap.id : E →ₗ[ℝ] E)
  have hdiagRange : (LinearMap.range Δ : Set (E × E)) = {p : E × E | p.1 = p.2} := by
    ext p
    constructor
    · rintro ⟨x, hx⟩
      cases hx
      simp [Δ]
    · intro hp
      refine ⟨p.1, ?_⟩
      ext <;> simpa [Δ] using hp
  have hΔinj : Function.Injective Δ := by
    intro x y hxy
    exact congrArg Prod.fst hxy
  have hΔ : LinearMap.ker Δ = ⊥ := LinearMap.ker_eq_bot.mpr hΔinj
  have hpre : Δ ⁻¹' (C ×ˢ D) = C ∩ D := by
    ext x
    simp [Δ]
  have hinter : IsClosedPolyhedral ((C ×ˢ D) ∩ (LinearMap.range Δ : Set (E × E))) := by
    simpa [hdiagRange] using hdiag
  rw [← hpre]
  exact IsClosedPolyhedral.preimage_linearMap_of_injective_of_inter_range
    (C := C ×ˢ D) Δ hinter hΔ

end LinearInjections

theorem IsPolyhedral.exists_nonempty_generators_of_nonempty
    {C : Set E} (hC : IsPolyhedral C) (hCne : C.Nonempty) :
    ∃ s t : Finset E, s.Nonempty ∧ C = extendedConvexHull (↑s : Set E) (↑t : Set E) :=
  IsExtendedFinitelyGenerated.exists_nonempty_generators_of_nonempty hC hCne

theorem IsPolyhedral.exists_raySpace_generators {C : Set E} (hC : IsPolyhedral C) :
    ∃ s t : Finset E,
      convexHull ℝ (raySpaceCone (↑s : Set E) (conicHull (↑t : Set E))) =
        raySpaceCone C (conicHull (↑t : Set E)) := by
  rcases hC with ⟨s, t, rfl⟩
  exact ⟨s, t, convexHull_raySpaceCone_eq_raySpaceCone_extendedConvexHull
    (A := (↑s : Set E)) (B := (↑t : Set E))⟩

theorem IsPolyhedral.exists_raySpace_generators_of_nonempty
    {C : Set E} (hC : IsPolyhedral C) (hCne : C.Nonempty) :
    ∃ s t : Finset E, s.Nonempty ∧
      convexHull ℝ (raySpaceCone (↑s : Set E) (conicHull (↑t : Set E))) =
        raySpaceCone C (conicHull (↑t : Set E)) := by
  obtain ⟨s, t, hs, rfl⟩ :=
    IsExtendedFinitelyGenerated.exists_nonempty_generators_of_nonempty hC hCne
  exact ⟨s, t, hs, convexHull_raySpaceCone_eq_raySpaceCone_extendedConvexHull
    (A := (↑s : Set E)) (B := (↑t : Set E))⟩

theorem IsPolyhedral.exists_horizon_generators_of_nonempty
    [FiniteDimensional ℝ E]
    {C : Set E} (hC : IsPolyhedral C) (hCne : C.Nonempty) :
    ∃ t : Finset E, horizonCone C = horizonCone (conicHull (↑t : Set E)) :=
  IsExtendedFinitelyGenerated.exists_horizon_generators_of_nonempty hC hCne

open Classical in
/-- The ray-space cone of an extended-convex-hull representation is itself a
finitely generated cone in `E × ℝ`, generated by the ordinary slice at level
`-1` together with the horizontal direction slice at level `0`. -/
theorem raySpaceCone_extendedConvexHull_eq_conicHull_rayGenerators
    (s t : Finset E) :
    raySpaceCone (extendedConvexHull (↑s : Set E) (↑t : Set E)) (conicHull (↑t : Set E)) =
      conicHull
        (↑((s.image fun x => (x, (-1 : ℝ))) ∪ (t.image fun x => (x, (0 : ℝ)))) :
          Set (E × ℝ)) := by
  let G : Set (E × ℝ) :=
    ((↑((s.image fun x => (x, (-1 : ℝ))) ∪ (t.image fun x => (x, (0 : ℝ)))) :
      Set (E × ℝ)))
  have hEq :
      convexHull ℝ (raySpaceCone (↑s : Set E) (conicHull (↑t : Set E))) =
        raySpaceCone (extendedConvexHull (↑s : Set E) (↑t : Set E)) (conicHull (↑t : Set E)) :=
    convexHull_raySpaceCone_eq_raySpaceCone_extendedConvexHull
      (A := (↑s : Set E)) (B := (↑t : Set E))
  rw [← hEq]
  apply le_antisymm
  · refine convexHull_min ?_ (convex_conicHull G)
    intro p hp
    rcases hp with hOrd | hHor
    · rcases hOrd with ⟨x, hx, a, ha, rfl⟩
      have hxG : ((x, (-1 : ℝ)) : E × ℝ) ∈ G := by
        exact Finset.mem_union.mpr <| Or.inl <| Finset.mem_image.mpr ⟨x, hx, rfl⟩
      have hbase : ((x, (-1 : ℝ)) : E × ℝ) ∈ conicHull G :=
        subset_conicHull hxG
      simpa [G] using (isCone_conicHull G).smul_mem hbase ha.le
    · rcases hHor with ⟨hw, hzero⟩
      have hp0 : p.2 = 0 := by simpa using hzero
      have hpEq : p = (p.1, (0 : ℝ)) := by
        ext <;> simp [hp0]
      let L : E →ₗ[ℝ] E × ℝ := LinearMap.inl ℝ E ℝ
      have hw' : ((p.1, (0 : ℝ)) : E × ℝ) ∈ L '' conicHull (↑t : Set E) := by
        exact ⟨p.1, hw, rfl⟩
      rw [RW.LinearMap.image_conicHull (E := E) (F := E × ℝ) L (↑t : Set E)] at hw'
      have hLG : L '' (↑t : Set E) ⊆ G := by
        intro p hp
        rcases hp with ⟨x, hx, rfl⟩
        exact Finset.mem_union.mpr <| Or.inr <| Finset.mem_image.mpr ⟨x, hx, rfl⟩
      rw [hpEq]
      exact conicHull_mono hLG hw'
  · refine conicHull_minimal
      (K := convexHull ℝ (raySpaceCone (↑s : Set E) (conicHull (↑t : Set E))))
      (convex_convexHull ℝ _)
      (isCone_convexHull (isCone_raySpaceCone (isCone_conicHull (↑t : Set E))))
      ?_
    intro p hp
    rcases Finset.mem_union.mp hp with hp | hp
    · rcases Finset.mem_image.mp hp with ⟨x, hx, rfl⟩
      exact subset_convexHull ℝ _ <| (mem_raySpaceCone_neg_one_iff).2 hx
    · rcases Finset.mem_image.mp hp with ⟨x, hx, rfl⟩
      exact subset_convexHull ℝ _ <| Or.inr ⟨subset_conicHull hx, rfl⟩

open Classical in
/-- A nonempty closed polyhedral set has a finitely generated ray-space cone:
its ordinary generators sit at height `-1`, and its horizon generators sit at
height `0`. -/
theorem IsClosedPolyhedral.isFinitelyGeneratedCone_raySpaceCone
    [FiniteDimensional ℝ E]
    {C : Set E} (hC : IsClosedPolyhedral C) (hCne : C.Nonempty) :
    IsFinitelyGeneratedCone (raySpaceCone C (horizonCone C)) := by
  obtain ⟨s, t, hs, hrep⟩ := hC.exists_nonempty_generators_of_nonempty hCne
  have htclosed : IsClosed (conicHull (↑t : Set E)) :=
    isClosed_conicHull_finset (E := E) t
  have hCeq : C = extendedConvexHull (↑s : Set E) (↑t : Set E) := by
    simpa [extendedConvexHull, htclosed.closure_eq] using hrep
  have hhor :
      horizonCone C = conicHull (↑t : Set E) := by
    rw [hCeq]
    exact horizonCone_extendedConvexHull_finset_eq_conicHull s t hs htclosed
  refine
    ⟨(s.image fun x => (x, (-1 : ℝ))) ∪ (t.image fun x => (x, (0 : ℝ))), ?_⟩
  calc
    raySpaceCone C (horizonCone C)
        = raySpaceCone (extendedConvexHull (↑s : Set E) (↑t : Set E))
            (conicHull (↑t : Set E)) := by
              rw [hhor, hCeq]
    _ = conicHull
          (↑((s.image fun x => (x, (-1 : ℝ))) ∪ (t.image fun x => (x, (0 : ℝ)))) :
            Set (E × ℝ)) :=
          raySpaceCone_extendedConvexHull_eq_conicHull_rayGenerators s t

theorem IsClosedPolyhedral.raySpaceCone_isClosedPolyhedral
    [FiniteDimensional ℝ E]
    {C : Set E} (hC : IsClosedPolyhedral C) (hCne : C.Nonempty) :
    IsClosedPolyhedral (raySpaceCone C (horizonCone C)) :=
  (hC.isFinitelyGeneratedCone_raySpaceCone hCne).isClosedPolyhedral

theorem IsClosedPolyhedral.raySpaceCone_isClosedPolyhedral_of_isCone
    [FiniteDimensional ℝ E]
    {K : Set E} (hK : IsClosedPolyhedral K) (hKcone : IsCone K) :
    IsClosedPolyhedral (raySpaceCone K K) := by
  rw [raySpaceCone_eq_prod_Iic_zero_of_isCone hKcone]
  exact hK.prod IsClosedPolyhedral.Iic_zero

open Classical in
/-- A finitely generated ray-space cone has an extended-convex-hull ordinary
slice. This is the converse direction of the ray-space representation used in
Corollary 3.53. -/
theorem IsFinitelyGeneratedCone.isExtendedFinitelyGenerated_of_eq_raySpaceCone
    {C K : Set E} (hCK : IsFinitelyGeneratedCone (raySpaceCone C K)) :
    IsExtendedFinitelyGenerated C := by
  rcases hCK with ⟨u, hu⟩
  let s : Finset E :=
    (u.filter fun p : E × ℝ => p.2 < 0).image fun p => ((-p.2)⁻¹ • p.1)
  let t : Finset E :=
    (u.filter fun p : E × ℝ => p.2 = 0).image Prod.fst
  have hconeEq :
      raySpaceCone C K = raySpaceCone (extendedConvexHull (↑s : Set E) (↑t : Set E))
        (conicHull (↑t : Set E)) := by
    rw [hu]
    have hconvTarget :
        Convex ℝ (raySpaceCone (extendedConvexHull (↑s : Set E) (↑t : Set E))
          (conicHull (↑t : Set E))) := by
      rw [← convexHull_raySpaceCone_eq_raySpaceCone_extendedConvexHull
        (A := (↑s : Set E)) (B := (↑t : Set E))]
      exact convex_convexHull ℝ _
    apply le_antisymm
    · refine conicHull_minimal
        (K := raySpaceCone (extendedConvexHull (↑s : Set E) (↑t : Set E)) (conicHull (↑t : Set E)))
        hconvTarget
        (isCone_raySpaceCone (isCone_conicHull (↑t : Set E)))
        ?_
      intro p hp
      have hpRay : p ∈ raySpaceCone C K := by
        rw [hu]
        exact subset_conicHull hp
      rcases hpRay with hpOrd | hpHor
      · rcases hpOrd with ⟨x, hx, a, ha, hpEq⟩
        have hpOrd' : p ∈ ordinaryRayCone C := by
          exact ⟨x, hx, a, ha, hpEq⟩
        have hxS : x ∈ (↑s : Set E) := by
          apply Finset.mem_image.mpr
          refine ⟨p, ?_, ?_⟩
          · refine Finset.mem_filter.mpr ⟨hp, ?_⟩
            simpa [hpEq] using (show p.2 < 0 from snd_lt_zero_of_mem_ordinaryRayCone hpOrd')
          · have hp1 : p.1 = a • x := by
              simpa [hpEq] using congrArg Prod.fst hpEq
            have hp2 : p.2 = -a := by
              simpa [hpEq] using congrArg Prod.snd hpEq
            rw [hp1, hp2]
            simp [smul_smul, ha.ne', inv_mul_cancel₀]
        have hxExt : x ∈ extendedConvexHull (↑s : Set E) (↑t : Set E) := by
          exact Set.mem_add.2
            ⟨x, subset_convexHull (𝕜 := ℝ) (s := (↑s : Set E)) hxS,
              0, zero_mem_conicHull (↑t : Set E), by simp⟩
        exact Or.inl ⟨x, hxExt, a, ha, hpEq⟩
      · have hpZero : p.2 = 0 := by simpa using hpHor.2
        have hpT : p.1 ∈ (↑t : Set E) := by
          apply Finset.mem_image.mpr
          refine ⟨p, ?_, rfl⟩
          exact Finset.mem_filter.mpr ⟨hp, hpZero⟩
        exact Or.inr ⟨subset_conicHull hpT, hpZero⟩
    · have hsub :
          ↑((s.image fun x => (x, (-1 : ℝ))) ∪ (t.image fun x => (x, (0 : ℝ)))) ⊆
            conicHull (↑u : Set (E × ℝ)) := by
          intro p hp
          rcases Finset.mem_union.mp hp with hp | hp
          · rcases Finset.mem_image.mp hp with ⟨x, hxS, rfl⟩
            rcases Finset.mem_image.mp hxS with ⟨q, hq, hqx⟩
            rcases Finset.mem_filter.mp hq with ⟨hqU, hqNeg⟩
            have hqRay : q ∈ raySpaceCone C K := by
              rw [hu]
              exact subset_conicHull hqU
            rcases hqRay with hqOrd | hqHor
            · let a : ℝ := -q.2
              have ha : 0 < a := by
                dsimp [a]
                linarith
              have hqCone : q ∈ conicHull (↑u : Set (E × ℝ)) := subset_conicHull hqU
              have hscaled : a⁻¹ • q ∈ conicHull (↑u : Set (E × ℝ)) :=
                (isCone_conicHull (↑u : Set (E × ℝ))).smul_mem hqCone <| by
                  exact inv_nonneg.mpr ha.le
              have hqsec : (a⁻¹ : ℝ) * q.2 = -1 := by
                have hqa : q.2 = -a := by simp [a]
                rw [hqa]
                simp [ha.ne']
              have hqpair : a⁻¹ • q = ((x, (-1 : ℝ)) : E × ℝ) := by
                ext
                · simpa [a, Prod.smul_mk] using hqx
                · simpa [Prod.smul_mk] using hqsec
              simpa [hqpair] using hscaled
            · have : q.2 = 0 := by simpa using hqHor.2
              linarith
          · rcases Finset.mem_image.mp hp with ⟨x, hxT, rfl⟩
            rcases Finset.mem_image.mp hxT with ⟨q, hq, hq1⟩
            rcases Finset.mem_filter.mp hq with ⟨hqU, hqZero⟩
            have hqCone : q ∈ conicHull (↑u : Set (E × ℝ)) := subset_conicHull hqU
            have hqpair : q = ((x, (0 : ℝ)) : E × ℝ) := by
              ext
              · simpa using hq1
              · simpa using hqZero
            simpa [hqpair] using hqCone
      rw [raySpaceCone_extendedConvexHull_eq_conicHull_rayGenerators s t]
      exact conicHull_minimal
        (K := conicHull (↑u : Set (E × ℝ)))
        (convex_conicHull _)
        (isCone_conicHull _)
        hsub
  refine ⟨s, t, ?_⟩
  ext x
  constructor
  · intro hx
    have hxRay : ((x, (-1 : ℝ)) : E × ℝ) ∈ raySpaceCone C K :=
      (mem_raySpaceCone_neg_one_iff).2 hx
    have hxRay' :
        ((x, (-1 : ℝ)) : E × ℝ) ∈
          raySpaceCone (extendedConvexHull (↑s : Set E) (↑t : Set E)) (conicHull (↑t : Set E)) := by
      rw [← hconeEq]
      exact hxRay
    exact (mem_raySpaceCone_neg_one_iff).1 hxRay'
  · intro hx
    have hxRay :
        ((x, (-1 : ℝ)) : E × ℝ) ∈
          raySpaceCone (extendedConvexHull (↑s : Set E) (↑t : Set E)) (conicHull (↑t : Set E)) :=
      (mem_raySpaceCone_neg_one_iff).2 hx
    have hxRay' : ((x, (-1 : ℝ)) : E × ℝ) ∈ raySpaceCone C K := by
      rw [hconeEq]
      exact hxRay
    exact (mem_raySpaceCone_neg_one_iff).1 hxRay'

theorem IsFinitelyGeneratedCone.isPolyhedral_of_eq_raySpaceCone
    {C K : Set E} (hCK : IsFinitelyGeneratedCone (raySpaceCone C K)) :
    IsPolyhedral C :=
  hCK.isExtendedFinitelyGenerated_of_eq_raySpaceCone

theorem IsFinitelyGeneratedCone.isClosedPolyhedral_of_eq_raySpaceCone_horizon
    [FiniteDimensional ℝ E]
    {C : Set E} (hCK : IsFinitelyGeneratedCone (raySpaceCone C (horizonCone C))) :
    IsClosedPolyhedral C := by
  have hclosedRay : IsClosed (raySpaceCone C (horizonCone C)) := hCK.isClosed
  have hclosedC : IsClosed C := by
    rcases (isClosed_raySpaceCone_iff (C := C) (K := horizonCone C)
      (isCone_horizonCone C)).1 hclosedRay with ⟨hC, _, _⟩
    exact hC
  exact hCK.isPolyhedral_of_eq_raySpaceCone.isClosedPolyhedral_of_isClosed hclosedC

theorem isClosedPolyhedral_iff_isFinitelyGeneratedCone_raySpaceCone_horizon
    [FiniteDimensional ℝ E]
    {C : Set E} (hCne : C.Nonempty) :
    IsClosedPolyhedral C ↔ IsFinitelyGeneratedCone (raySpaceCone C (horizonCone C)) := by
  constructor
  · intro hC
    exact hC.isFinitelyGeneratedCone_raySpaceCone hCne
  · intro hRay
    exact hRay.isClosedPolyhedral_of_eq_raySpaceCone_horizon

/-- A nonempty intersection of closed polyhedral sets is closed polyhedral as
soon as the corresponding ray-space cone intersection is finitely generated. -/
theorem IsClosedPolyhedral.inter_of_isFinitelyGeneratedCone_raySpaceCone_inter
    [FiniteDimensional ℝ E]
    {C D : Set E} (hC : IsClosedPolyhedral C) (hD : IsClosedPolyhedral D)
    (hCDne : (C ∩ D).Nonempty)
    (hRay :
      IsFinitelyGeneratedCone
        (raySpaceCone C (horizonCone C) ∩ raySpaceCone D (horizonCone D))) :
    IsClosedPolyhedral (C ∩ D) := by
  have hhoriz :
      horizonCone (C ∩ D) = horizonCone C ∩ horizonCone D :=
    horizonCone_inter_eq_inter_horizonCone
      hC.convex hD.convex hC.isClosed hD.isClosed hCDne
  have hRay' : IsFinitelyGeneratedCone (raySpaceCone (C ∩ D) (horizonCone (C ∩ D))) := by
    rw [hhoriz]
    simpa [raySpaceCone_inter] using hRay
  exact
    (isClosedPolyhedral_iff_isFinitelyGeneratedCone_raySpaceCone_horizon
      (C := C ∩ D) hCDne).2 hRay'

theorem isClosedPolyhedral_iff_isFinitelyGeneratedCone_raySpaceCone_of_isCone
    [FiniteDimensional ℝ E]
    {K : Set E} (hKcone : IsCone K) :
    IsClosedPolyhedral K ↔ IsFinitelyGeneratedCone (raySpaceCone K K) := by
  constructor
  · intro hK
    exact (hK.isFinitelyGeneratedCone_of_isCone hKcone).raySpaceCone_of_isCone hKcone
  · intro hRay
    have hclosedRay : IsClosed (raySpaceCone K K) := hRay.isClosed
    rcases (isClosed_raySpaceCone_iff (C := K) (K := K) hKcone).1 hclosedRay with
      ⟨hKclosed, _, hhor⟩
    have hKhorizon : horizonCone K = K := by
      apply le_antisymm hhor
      intro x hx
      exact mem_horizonCone_of_forall_smul_add_mem (C := K) (x := 0) (w := x) <| by
        intro τ hτ
        rcases eq_or_lt_of_le hτ with rfl | hτpos
        · simpa using hKcone.1
        · simpa using hKcone.2 hx hτpos
    have hRay' : IsFinitelyGeneratedCone (raySpaceCone K (horizonCone K)) := by
      simpa [hKhorizon] using hRay
    exact
      (isClosedPolyhedral_iff_isFinitelyGeneratedCone_raySpaceCone_horizon
        (C := K) ⟨0, hKcone.1⟩).2 hRay'

end RW
