/- 
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Chapter 3G*: Generated Cones

This file starts the finite-generation side of Chapter 3's polyhedral cone
material by introducing the conic hull generated by a set and relating it to
the chapter's existing `positiveHull` and `convexHull` formalization.
-/

import RockafellarWets.Chapter3.PositiveHulls
import RockafellarWets.Chapter3.PointedCones
import Mathlib.Analysis.Convex.Cone.InnerDual
import Mathlib.Geometry.Convex.Cone.Pointed

open Set
open scoped Pointwise

namespace RW

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- The pointed conic hull generated by a set. This is the smallest convex cone
containing the set, with the Chapter 3 convention that cones contain `0`. -/
def conicHull (C : Set E) : Set E :=
  (PointedCone.span ℝ C : Set E)

theorem subset_conicHull {C : Set E} : C ⊆ conicHull C := by
  exact PointedCone.subset_span

theorem mem_conicHull_iff_exists_finsupp {C : Set E} {x : E} :
    x ∈ conicHull C ↔
      ∃ c : E →₀ ℝ, ↑c.support ⊆ C ∧ (∀ y, 0 ≤ c y) ∧ c.sum (fun y r => r • y) = x := by
  simpa [conicHull] using (PointedCone.mem_span_set (R := ℝ) (s := C) (x := x))

theorem zero_mem_conicHull (C : Set E) : (0 : E) ∈ conicHull C := by
  simp [conicHull]

theorem convex_conicHull (C : Set E) : Convex ℝ (conicHull C) := by
  simpa [conicHull] using (PointedCone.span ℝ C).convex

theorem isCone_conicHull (C : Set E) : IsCone (conicHull C) := by
  refine ⟨zero_mem_conicHull C, ?_⟩
  intro x hx c hc
  simpa [conicHull] using (PointedCone.span ℝ C).smul_mem hc.le hx

/-- The conic hull is the smallest convex cone containing the generating set. -/
theorem conicHull_minimal {C K : Set E}
    (hKconv : Convex ℝ K) (hKcone : IsCone K) (hCK : C ⊆ K) :
    conicHull C ⊆ K := by
  let Kpc : PointedCone ℝ E :=
    PointedCone.ofConeComb K ⟨0, hKcone.1⟩ <| by
      intro x hx y hy a ha b hb
      exact add_mem_of_convex_isCone hKconv hKcone
        (hKcone.smul_mem hx ha) (hKcone.smul_mem hy hb)
  have hspan : PointedCone.span ℝ C ≤ Kpc := Submodule.span_le.mpr hCK
  exact hspan

/-- The nonnegative ray in `ℝ` is the conic hull generated by `1`. -/
theorem conicHull_singleton_one_eq_Ici_zero :
    conicHull ({(1 : ℝ)} : Set ℝ) = Set.Ici (0 : ℝ) := by
  apply le_antisymm
  · exact
      conicHull_minimal
        (C := ({(1 : ℝ)} : Set ℝ))
        (K := Set.Ici (0 : ℝ))
        (convex_Ici (0 : ℝ))
        (by
          refine ⟨by simp, ?_⟩
          intro x hx c hc
          simpa [smul_eq_mul] using mul_nonneg (le_of_lt hc) hx)
        (by
          intro x hx
          simpa [Set.mem_singleton_iff.mp hx] using (show (0 : ℝ) ≤ (1 : ℝ) by norm_num))
  · intro x hx
    have h1 : (1 : ℝ) ∈ conicHull ({(1 : ℝ)} : Set ℝ) :=
      subset_conicHull (by simp)
    simpa [smul_eq_mul] using
      (isCone_conicHull ({(1 : ℝ)} : Set ℝ)).smul_mem h1 hx

/-- The nonpositive ray in `ℝ` is the conic hull generated by `-1`. -/
theorem conicHull_singleton_neg_one_eq_Iic_zero :
    conicHull ({(-1 : ℝ)} : Set ℝ) = Set.Iic (0 : ℝ) := by
  apply le_antisymm
  · exact
      conicHull_minimal
        (C := ({(-1 : ℝ)} : Set ℝ))
        (K := Set.Iic (0 : ℝ))
        (convex_Iic (0 : ℝ))
        (by
          refine ⟨by simp, ?_⟩
          intro x hx c hc
          have hxle : x ≤ 0 := hx
          have hcx : c * x ≤ 0 := by nlinarith [hxle, hc.le]
          simpa [smul_eq_mul] using hcx)
        (by
          intro x hx
          simpa [Set.mem_singleton_iff.mp hx] using (show (-1 : ℝ) ≤ 0 by norm_num))
  · intro x hx
    rcases eq_or_lt_of_le (show x ≤ 0 from hx) with rfl | hxlt
    · exact zero_mem_conicHull ({(-1 : ℝ)} : Set ℝ)
    · have hnegOne : (-1 : ℝ) ∈ conicHull ({(-1 : ℝ)} : Set ℝ) :=
        subset_conicHull (by simp)
      have hxpos : 0 < -x := by linarith
      simpa [smul_eq_mul] using
        (isCone_conicHull ({(-1 : ℝ)} : Set ℝ)).smul_mem hnegOne hxpos.le

/-- Monotonicity of the conic hull operator. -/
theorem conicHull_mono {C D : Set E} (hCD : C ⊆ D) :
    conicHull C ⊆ conicHull D := by
  exact conicHull_minimal
    (K := conicHull D)
    (convex_conicHull D)
    (isCone_conicHull D)
    (Subset.trans hCD subset_conicHull)

theorem positiveHull_subset_conicHull (C : Set E) :
    positiveHull C ⊆ conicHull C := by
  exact positiveHull_minimal (isCone_conicHull C) subset_conicHull

/-- The conic hull generated by `C` is exactly the convex hull of the ordinary
positive hull of `C`. -/
theorem conicHull_eq_convexHull_positiveHull (C : Set E) :
    conicHull C = convexHull ℝ (positiveHull C) := by
  apply le_antisymm
  · exact conicHull_minimal
      (K := convexHull ℝ (positiveHull C))
      (convex_convexHull ℝ (positiveHull C))
      (isCone_convexHull (isCone_positiveHull (C := C)))
      (Subset.trans subset_positiveHull (subset_convexHull ℝ (positiveHull C)))
  · exact convexHull_minimal
      (positiveHull_subset_conicHull C)
      (convex_conicHull C)

/-- For a convex generating set, the conic hull is the same as the Chapter 3
positive hull. -/
theorem conicHull_eq_positiveHull_of_convex {C : Set E} (hC : Convex ℝ C) :
    conicHull C = positiveHull C := by
  rw [conicHull_eq_convexHull_positiveHull]
  exact (convex_positiveHull hC).convexHull_eq

/-- Conic hull turns unions into Minkowski sums. -/
theorem conicHull_union_eq_add (C D : Set E) :
    conicHull (C ∪ D) = conicHull C + conicHull D := by
  apply le_antisymm
  · exact conicHull_minimal
      (K := conicHull C + conicHull D)
      ((convex_conicHull C).add (convex_conicHull D))
      (isCone_add (isCone_conicHull C) (isCone_conicHull D))
      (by
        intro x hx
        rcases hx with hx | hx
        · exact Set.mem_add.2 ⟨x, subset_conicHull hx, 0, zero_mem_conicHull D, by simp⟩
        · exact Set.mem_add.2 ⟨0, zero_mem_conicHull C, x, subset_conicHull hx, by simp⟩)
  · intro x hx
    rcases hx with ⟨u, hu, v, hv, rfl⟩
    exact add_mem_of_convex_isCone
      (convex_conicHull (C ∪ D))
      (isCone_conicHull (C ∪ D))
      (conicHull_mono (by intro x hx; exact Or.inl hx) hu)
      (conicHull_mono (by intro x hx; exact Or.inr hx) hv)

/-- Linear maps commute with conic hulls. -/
theorem LinearMap.image_conicHull {F : Type*}
    [NormedAddCommGroup F] [NormedSpace ℝ F]
    (L : E →ₗ[ℝ] F) (C : Set E) :
    L '' conicHull C = conicHull (L '' C) := by
  apply le_antisymm
  · rintro y ⟨x, hx, rfl⟩
    have hpre :
        conicHull C ⊆ L ⁻¹' conicHull (L '' C) := by
      exact conicHull_minimal
        (K := L ⁻¹' conicHull (L '' C))
        ((convex_conicHull (L '' C)).linear_preimage L)
        (LinearMap.isCone_preimage L (isCone_conicHull (L '' C)))
        (by
          intro z hz
          exact subset_conicHull ⟨z, hz, rfl⟩)
    exact hpre hx
  · exact conicHull_minimal
      (K := L '' conicHull C)
      ((convex_conicHull C).linear_image L)
      (LinearMap.isCone_image L (isCone_conicHull C))
      (by
        rintro y ⟨x, hx, rfl⟩
        exact ⟨x, subset_conicHull hx, rfl⟩)

/-- If the generating set is closed under negation, then so is its conic hull. -/
theorem neg_mem_conicHull_of_neg_subset {C : Set E} (hneg : -C ⊆ C) {x : E}
    (hx : x ∈ conicHull C) :
    -x ∈ conicHull C := by
  have hx' : -x ∈ (-LinearMap.id : E →ₗ[ℝ] E) '' conicHull C := by
    exact ⟨x, hx, by simp⟩
  rw [RW.LinearMap.image_conicHull (E := E) (F := E) (-LinearMap.id) C] at hx'
  exact conicHull_mono (by simpa using hneg) hx'

/-- A conic hull generated by a negation-stable set is exactly the ordinary
linear span of that set. -/
theorem conicHull_eq_span_of_neg_subset {C : Set E} (hneg : -C ⊆ C) :
    conicHull C = (Submodule.span ℝ C : Set E) := by
  apply le_antisymm
  · exact conicHull_minimal
      (K := (Submodule.span ℝ C : Set E))
      (Submodule.span ℝ C).convex
      ⟨(Submodule.span ℝ C).zero_mem, fun x hx c hc =>
        (Submodule.span ℝ C).smul_mem c hx⟩
      Submodule.subset_span
  · let K : Submodule ℝ E := by
      refine
        { carrier := conicHull C
          zero_mem' := zero_mem_conicHull C
          add_mem' := ?_
          smul_mem' := ?_ }
      · intro x y hx hy
        exact add_mem_of_convex_isCone (convex_conicHull C) (isCone_conicHull C) hx hy
      · intro a x hx
        by_cases ha : 0 ≤ a
        · rcases ha.eq_or_lt with rfl | ha'
          · simpa using zero_mem_conicHull C
          · exact (isCone_conicHull C).2 hx ha'
        · have hna : 0 < -a := by linarith
          have hnegx : -x ∈ conicHull C := neg_mem_conicHull_of_neg_subset hneg hx
          have h' : (-a) • (-x) ∈ conicHull C := (isCone_conicHull C).2 hnegx hna
          simpa using h'
    change (Submodule.span ℝ C) ≤ K
    exact Submodule.span_le.mpr subset_conicHull

/-- The conic hull generated by a set and its negatives is exactly the linear
span of the original set. -/
theorem conicHull_union_neg_eq_span (C : Set E) :
    conicHull (C ∪ -C) = (Submodule.span ℝ C : Set E) := by
  calc
    conicHull (C ∪ -C) = (Submodule.span ℝ (C ∪ -C) : Set E) := by
      refine conicHull_eq_span_of_neg_subset ?_
      intro x hx
      rw [Set.mem_neg] at hx
      rcases hx with hx | hx
      · exact Or.inr (by simpa [Set.mem_neg] using hx)
      · exact Or.inl (by simpa [Set.mem_neg] using hx)
    _ = (Submodule.span ℝ C : Set E) := by
      rw [Submodule.span_union, Submodule.span_neg, sup_idem]

/-- The horizon cone of a conic hull is its closure. -/
theorem horizonCone_conicHull_eq_closure (C : Set E) :
    horizonCone (conicHull C) = closure (conicHull C) := by
  rw [horizonCone_eq_asymptoticCone (show (conicHull C).Nonempty from ⟨0, zero_mem_conicHull C⟩)]
  exact asymptoticCone_eq_closure_of_forall_smul_mem fun c hc x hx =>
    (isCone_conicHull C).2 hx hc

/-- The horizon cone of a convex positive hull is its closure. -/
theorem horizonCone_positiveHull_eq_closure_of_convex {C : Set E} (hC : Convex ℝ C) :
    horizonCone (positiveHull C) = closure (positiveHull C) := by
  rw [← conicHull_eq_positiveHull_of_convex hC, horizonCone_conicHull_eq_closure]

/-- The conic hull of the effective domain of the gauge of a convex set is the
effective domain itself. -/
theorem conicHull_effectiveDomain_gaugeFunction_eq_self_of_convex
    {C : Set E} (hC : Convex ℝ C) :
    conicHull (effectiveDomain (gaugeFunction C)) =
      effectiveDomain (gaugeFunction C) := by
  rw [effectiveDomain_gaugeFunction]
  calc
    conicHull (positiveHull C) = positiveHull (positiveHull C) :=
      conicHull_eq_positiveHull_of_convex (convex_positiveHull hC)
    _ = positiveHull C := positiveHull_eq_self isCone_positiveHull

/-- The horizon cone of the effective domain of the gauge of a convex set is
the closure of that effective domain. -/
theorem horizonCone_effectiveDomain_gaugeFunction_eq_closure_of_convex
    {C : Set E} (hC : Convex ℝ C) :
    horizonCone (effectiveDomain (gaugeFunction C)) =
      closure (effectiveDomain (gaugeFunction C)) := by
  rw [effectiveDomain_gaugeFunction]
  exact horizonCone_positiveHull_eq_closure_of_convex hC

section Products

variable {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]

/-- The product of two conic hulls is the conic hull generated by the two axis
families in the product space. -/
theorem conicHull_prod_eq_conicHull_inl_union_inr (C : Set E) (D : Set F) :
    conicHull C ×ˢ conicHull D =
      conicHull (((LinearMap.inl ℝ E F) '' C) ∪ ((LinearMap.inr ℝ E F) '' D)) := by
  calc
    conicHull C ×ˢ conicHull D
        = (LinearMap.inl ℝ E F '' conicHull C) + (LinearMap.inr ℝ E F '' conicHull D) := by
            ext p
            rcases p with ⟨u, v⟩
            constructor
            · rintro ⟨hu, hv⟩
              exact Set.mem_add.2
                ⟨(u, 0), ⟨u, hu, by simp⟩, (0, v), ⟨v, hv, by simp⟩, by simp⟩
            · rintro ⟨x, hx, y, hy, hxy⟩
              rcases hx with ⟨u', hu', rfl⟩
              rcases hy with ⟨v', hv', rfl⟩
              have hxy' : (u', v') = (u, v) := by
                simpa only [LinearMap.inl_apply, LinearMap.inr_apply, Prod.mk_add_mk,
                  zero_add, add_zero] using hxy
              cases hxy'
              exact ⟨hu', hv'⟩
    _ = conicHull ((LinearMap.inl ℝ E F '' C) ∪ (LinearMap.inr ℝ E F '' D)) := by
          rw [RW.LinearMap.image_conicHull, RW.LinearMap.image_conicHull]
          simpa using
            (conicHull_union_eq_add
              ((LinearMap.inl ℝ E F) '' C)
              ((LinearMap.inr ℝ E F) '' D)).symm

/-- The product of the closures of two conic hulls is again the closure of a
finitely generated conic hull in the product space. -/
theorem closure_conicHull_prod_eq_closure_conicHull_inl_union_inr
    [FiniteDimensional ℝ E] [FiniteDimensional ℝ F]
    (C : Set E) (D : Set F) :
    closure (conicHull C) ×ˢ closure (conicHull D) =
      closure (conicHull (((LinearMap.inl ℝ E F) '' C) ∪ ((LinearMap.inr ℝ E F) '' D))) := by
  calc
    closure (conicHull C) ×ˢ closure (conicHull D)
        = horizonCone (conicHull C) ×ˢ horizonCone (conicHull D) := by
            rw [horizonCone_conicHull_eq_closure, horizonCone_conicHull_eq_closure]
    _ = horizonCone (conicHull C ×ˢ conicHull D) := by
          symm
          exact horizonCone_prod_eq_of_convex_nonempty
            (convex_conicHull C) (convex_conicHull D)
            ⟨0, zero_mem_conicHull C⟩ ⟨0, zero_mem_conicHull D⟩
    _ = horizonCone (conicHull (((LinearMap.inl ℝ E F) '' C) ∪ ((LinearMap.inr ℝ E F) '' D))) := by
          rw [conicHull_prod_eq_conicHull_inl_union_inr]
    _ = closure (conicHull (((LinearMap.inl ℝ E F) '' C) ∪ ((LinearMap.inr ℝ E F) '' D))) := by
          rw [horizonCone_conicHull_eq_closure]

end Products

section InnerDuality

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]

theorem ProperCone.innerDual_conicHull (C : Set H) :
    ProperCone.innerDual (conicHull C) = ProperCone.innerDual C := by
  ext y
  change y ∈ (PointedCone.dual (innerₗ H) (PointedCone.span ℝ C) : Set H) ↔
      y ∈ (PointedCone.dual (innerₗ H) C : Set H)
  rw [PointedCone.dual_span (R := ℝ) (p := innerₗ H) (s := C)]

theorem innerDual_innerDual_eq_closure_conicHull (C : Set H) :
    (ProperCone.innerDual (ProperCone.innerDual C : Set H) : Set H) =
      closure (conicHull C) := by
  let D : ProperCone ℝ H := ProperCone.innerDual (ProperCone.innerDual C : Set H)
  apply le_antisymm
  · intro x hx
    by_contra hxc
    let K : ConvexCone ℝ H :=
      ((PointedCone.span ℝ C : PointedCone ℝ H) : ConvexCone ℝ H).closure
    have hKne : (K : Set H).Nonempty := by
      refine ⟨0, ?_⟩
      change 0 ∈ closure (conicHull C)
      exact subset_closure (zero_mem_conicHull C)
    have hKclosed : IsClosed (K : Set H) := by
      simpa [K, RW.conicHull, ConvexCone.coe_closure] using
        (isClosed_closure : IsClosed (closure (conicHull C)))
    have hxnotK : x ∉ (K : Set H) := by
      simpa [K, RW.conicHull, ConvexCone.coe_closure] using hxc
    obtain ⟨y, hyK, hyx⟩ :=
      ConvexCone.hyperplane_separation_of_nonempty_of_isClosed_of_notMem
        (K := K) (b := x) hKne hKclosed hxnotK
    have hyC : y ∈ ProperCone.innerDual C := by
      intro z hz
      exact hyK z <| by
        change z ∈ closure (conicHull C)
        exact subset_closure (subset_conicHull hz)
    have hyx_nonneg : 0 ≤ inner ℝ y x := (ProperCone.mem_innerDual.mp hx) hyC
    exact not_lt_of_ge hyx_nonneg hyx
  · have hsubset : C ⊆ (D : Set H) := by
      intro x hx
      exact ProperCone.mem_innerDual.mpr fun y hy =>
        by simpa [real_inner_comm] using hy hx
    have hconv : Convex ℝ (D : Set H) := D.convex
    have hcone : IsCone (D : Set H) := by
      refine ⟨by simpa using D.zero_mem, ?_⟩
      intro x hx c hc
      simpa using D.smul_mem hx hc.le
    exact closure_minimal (conicHull_minimal hconv hcone hsubset) D.isClosed

end InnerDuality

/-- A cone is finitely generated if it is the conic hull of a finite set. This
is the generation side of Theorem 3.52. -/
def IsFinitelyGeneratedCone (K : Set E) : Prop :=
  ∃ s : Finset E, K = conicHull (↑s : Set E)

theorem IsFinitelyGeneratedCone.exists_generators {K : Set E}
    (hK : IsFinitelyGeneratedCone K) :
    ∃ s : Finset E, K = conicHull (↑s : Set E) :=
  hK

/-- A finitely generated cone has an explicit finite conic-coefficient
membership formula. -/
theorem IsFinitelyGeneratedCone.exists_generator_formula {K : Set E}
    (hK : IsFinitelyGeneratedCone K) :
    ∃ s : Finset E,
      ∀ {x : E},
        x ∈ K ↔
          ∃ c : E →₀ ℝ,
            ↑c.support ⊆ (↑s : Set E) ∧
            (∀ y, 0 ≤ c y) ∧
            c.sum (fun y r => r • y) = x := by
  rcases hK with ⟨s, hs⟩
  refine ⟨s, ?_⟩
  intro x
  rw [hs]
  exact mem_conicHull_iff_exists_finsupp

theorem IsFinitelyGeneratedCone.Iic_zero : IsFinitelyGeneratedCone (Set.Iic (0 : ℝ)) := by
  refine ⟨{-1}, ?_⟩
  simpa using conicHull_singleton_neg_one_eq_Iic_zero.symm

theorem IsFinitelyGeneratedCone.isCone {K : Set E} (hK : IsFinitelyGeneratedCone K) :
    IsCone K := by
  rcases hK with ⟨s, rfl⟩
  exact isCone_conicHull (↑s : Set E)

theorem IsFinitelyGeneratedCone.convex {K : Set E} (hK : IsFinitelyGeneratedCone K) :
    Convex ℝ K := by
  rcases hK with ⟨s, rfl⟩
  exact convex_conicHull (↑s : Set E)

/-- A finitely generated cone contains the origin. -/
theorem IsFinitelyGeneratedCone.zero_mem {K : Set E} (hK : IsFinitelyGeneratedCone K) :
    (0 : E) ∈ K :=
  hK.isCone.1

/-- A finitely generated cone is nonempty. -/
theorem IsFinitelyGeneratedCone.nonempty {K : Set E} (hK : IsFinitelyGeneratedCone K) :
    K.Nonempty :=
  ⟨0, hK.zero_mem⟩

/-- The horizon cone of a finitely generated cone is its closure. -/
theorem IsFinitelyGeneratedCone.horizonCone_eq_closure {K : Set E}
    (hK : IsFinitelyGeneratedCone K) :
    horizonCone K = closure K := by
  rcases hK with ⟨s, rfl⟩
  exact horizonCone_conicHull_eq_closure (↑s : Set E)

/-- A closed finitely generated cone is its own horizon cone. -/
theorem IsFinitelyGeneratedCone.horizonCone_eq_self_of_isClosed {K : Set E}
    (hK : IsFinitelyGeneratedCone K) (hKclosed : IsClosed K) :
    horizonCone K = K := by
  rw [hK.horizonCone_eq_closure, hKclosed.closure_eq]

theorem IsFinitelyGeneratedCone.subset_convexHull_generators {K : Set E}
    (hK : IsFinitelyGeneratedCone K) :
    ∃ s : Finset E, K ⊆ convexHull ℝ (positiveHull (↑s : Set E)) := by
  rcases hK with ⟨s, rfl⟩
  exact ⟨s, by simp [conicHull_eq_convexHull_positiveHull]⟩

theorem IsFinitelyGeneratedCone.add {K₁ K₂ : Set E}
    (hK₁ : IsFinitelyGeneratedCone K₁) (hK₂ : IsFinitelyGeneratedCone K₂) :
    IsFinitelyGeneratedCone (K₁ + K₂) := by
  classical
  rcases hK₁ with ⟨s₁, rfl⟩
  rcases hK₂ with ⟨s₂, rfl⟩
  refine ⟨s₁ ∪ s₂, ?_⟩
  simp [conicHull_union_eq_add]

theorem IsFinitelyGeneratedCone.linear_image {F : Type*}
    [NormedAddCommGroup F] [NormedSpace ℝ F]
    {K : Set E} (hK : IsFinitelyGeneratedCone K) (L : E →ₗ[ℝ] F) :
    IsFinitelyGeneratedCone (L '' K) := by
  classical
  rcases hK with ⟨s, rfl⟩
  refine ⟨s.image L, ?_⟩
  simpa using (RW.LinearMap.image_conicHull (E := E) (F := F) L (↑s : Set E))

theorem IsFinitelyGeneratedCone.image_linearEquiv {F : Type*}
    [NormedAddCommGroup F] [NormedSpace ℝ F]
    {K : Set E} (hK : IsFinitelyGeneratedCone K) (e : E ≃L[ℝ] F) :
    IsFinitelyGeneratedCone (e '' K) :=
  hK.linear_image (e : E →ₗ[ℝ] F)

theorem IsFinitelyGeneratedCone.prod {F : Type*}
    [NormedAddCommGroup F] [NormedSpace ℝ F]
    {K : Set E} {L : Set F}
    (hK : IsFinitelyGeneratedCone K) (hL : IsFinitelyGeneratedCone L) :
    IsFinitelyGeneratedCone (K ×ˢ L) := by
  classical
  rcases hK with ⟨s, rfl⟩
  rcases hL with ⟨t, rfl⟩
  refine
    ⟨(s.image (LinearMap.inl ℝ E F)) ∪ (t.image (LinearMap.inr ℝ E F)), ?_⟩
  simpa using conicHull_prod_eq_conicHull_inl_union_inr
    (C := (↑s : Set E)) (D := (↑t : Set F))

theorem IsFinitelyGeneratedCone.submodule_span_finset (s : Finset E) :
    IsFinitelyGeneratedCone ((Submodule.span ℝ (↑s : Set E) : Set E)) := by
  classical
  refine ⟨s ∪ s.image fun x => -x, ?_⟩
  have hset : (↑(s ∪ s.image fun x => -x) : Set E) = (↑s : Set E) ∪ -(↑s : Set E) := by
    ext x
    simp
  calc
    (Submodule.span ℝ (↑s : Set E) : Set E)
        = conicHull ((↑s : Set E) ∪ -(↑s : Set E)) := by
            simpa using (conicHull_union_neg_eq_span (↑s : Set E)).symm
    _ = conicHull (↑(s ∪ s.image fun x => -x) : Set E) := by rw [hset]

section FiniteDimensionalSubmodules

variable [FiniteDimensional ℝ E]

theorem IsFinitelyGeneratedCone.range_linearMap {F : Type*}
    [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F]
    (L : F →ₗ[ℝ] E) :
    IsFinitelyGeneratedCone (LinearMap.range L : Set E) := by
  classical
  let b := Module.finBasis ℝ F
  have hgen : (↑(Finset.univ.image b) : Set F) = Set.range b := by
    ext x
    simp
  have htop :
      ((Submodule.span ℝ (↑(Finset.univ.image b) : Set F)) : Set F) =
        (((⊤ : Submodule ℝ F)) : Set F) := by
    calc
      ((Submodule.span ℝ (↑(Finset.univ.image b) : Set F)) : Set F)
          = (Submodule.span ℝ (Set.range b) : Set F) := by rw [hgen]
      _ = (((⊤ : Submodule ℝ F)) : Set F) := by
            simpa using congrArg (fun p : Submodule ℝ F => (p : Set F)) (b.span_eq)
  have himage :
      L '' ((((⊤ : Submodule ℝ F)) : Set F)) = (LinearMap.range L : Set E) := by
    ext y
    constructor
    · rintro ⟨x, hx, rfl⟩
      exact ⟨x, rfl⟩
    · rintro ⟨x, rfl⟩
      exact ⟨x, by simp, rfl⟩
  rw [← himage, ← htop]
  exact
    (IsFinitelyGeneratedCone.submodule_span_finset (E := F) (Finset.univ.image b)).linear_image L

theorem IsFinitelyGeneratedCone.submodule (S : Submodule ℝ E) :
    IsFinitelyGeneratedCone (S : Set E) := by
  have hrange : (LinearMap.range (Submodule.subtype S) : Set E) = S := by
    ext x
    constructor
    · rintro ⟨y, rfl⟩
      exact y.2
    · intro hx
      exact ⟨⟨x, hx⟩, rfl⟩
  rw [← hrange]
  exact IsFinitelyGeneratedCone.range_linearMap (E := E) (Submodule.subtype S)

theorem IsFinitelyGeneratedCone.ker_linearMap {F : Type*}
    [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F]
    (L : F →ₗ[ℝ] E) :
    IsFinitelyGeneratedCone (LinearMap.ker L : Set F) :=
  IsFinitelyGeneratedCone.submodule (LinearMap.ker L)

theorem IsFinitelyGeneratedCone.diagonal :
    IsFinitelyGeneratedCone ({p : E × E | p.1 = p.2} : Set (E × E)) := by
  let Δ : E →ₗ[ℝ] E × E :=
    (LinearMap.id : E →ₗ[ℝ] E).prod (LinearMap.id : E →ₗ[ℝ] E)
  have hdiag : (LinearMap.range Δ : Set (E × E)) = {p : E × E | p.1 = p.2} := by
    ext p
    constructor
    · rintro ⟨x, hx⟩
      cases hx
      simp [Δ]
    · intro hp
      refine ⟨p.1, ?_⟩
      ext <;> simpa [Δ] using hp
  rw [← hdiag]
  exact IsFinitelyGeneratedCone.range_linearMap (E := E × E) Δ

end FiniteDimensionalSubmodules

open Classical in
private theorem positiveHull_finset_eq_positiveHull_erase_zero (s : Finset E) :
    positiveHull (↑s : Set E) = positiveHull (↑(s.erase 0) : Set E) := by
  ext x
  constructor
  · intro hx
    rcases hx with rfl | ⟨a, ha, y, hy, rfl⟩
    · exact zero_mem_positiveHull (↑(s.erase 0) : Set E)
    · by_cases hy0 : y = 0
      · subst hy0
        simpa using zero_mem_positiveHull (↑(s.erase 0) : Set E)
      · right
        refine ⟨a, ha, y, ?_, rfl⟩
        simpa [Finset.mem_coe, hy0] using hy
  · intro hx
    rcases hx with rfl | ⟨a, ha, y, hy, rfl⟩
    · exact zero_mem_positiveHull (↑s : Set E)
    · right
      refine ⟨a, ha, y, ?_, rfl⟩
      exact Finset.mem_of_mem_erase hy

open Classical in
private theorem conicHull_finset_eq_conicHull_erase_zero (s : Finset E) :
    conicHull (↑s : Set E) = conicHull (↑(s.erase 0) : Set E) := by
  rw [conicHull_eq_convexHull_positiveHull, conicHull_eq_convexHull_positiveHull,
    positiveHull_finset_eq_positiveHull_erase_zero]

/-- In finite dimensions, a pointed finitely generated cone is closed. -/
theorem isClosed_conicHull_finset_of_isPointed [FiniteDimensional ℝ E]
    (s : Finset E) (hpointed : IsPointed (conicHull (↑s : Set E))) :
    IsClosed (conicHull (↑s : Set E)) := by
  classical
  let t : Finset E := s.erase 0
  have htclosed : IsClosed (↑t : Set E) := t.finite_toSet.isClosed
  have htbdd : Bornology.IsBounded (↑t : Set E) := by
    simpa using t.finite_toSet.isBounded
  have h0t : (0 : E) ∉ (↑t : Set E) := by
    simp [t]
  have hposClosed : IsClosed (positiveHull (↑t : Set E)) :=
    isClosed_positiveHull_of_isClosed_of_isBounded htclosed h0t htbdd
  have hposSubset : positiveHull (↑t : Set E) ⊆ conicHull (↑s : Set E) := by
    intro x hx
    have hx' : x ∈ conicHull (↑t : Set E) :=
      (positiveHull_subset_conicHull (C := (↑t : Set E))) hx
    simpa [t, conicHull_finset_eq_conicHull_erase_zero] using hx'
  have hposPointed : IsPointed (positiveHull (↑t : Set E)) :=
    hpointed.mono hposSubset
  have hconvClosed : IsClosed (convexHull ℝ (positiveHull (↑t : Set E)) : Set E) :=
    isClosed_convexHull_of_isClosed_isPointed hposClosed
      (isCone_positiveHull (C := (↑t : Set E))) hposPointed
  have hEq :
      conicHull (↑s : Set E) = convexHull ℝ (positiveHull (↑t : Set E)) := by
    calc
      conicHull (↑s : Set E) = conicHull (↑t : Set E) := by
        simpa [t] using conicHull_finset_eq_conicHull_erase_zero (s := s)
      _ = convexHull ℝ (positiveHull (↑t : Set E)) := by
        rw [conicHull_eq_convexHull_positiveHull]
  simpa [hEq] using hconvClosed

/-- In finite dimensions, a pointed finitely generated cone is closed. -/
theorem IsFinitelyGeneratedCone.isClosed_of_isPointed [FiniteDimensional ℝ E]
    {K : Set E} (hK : IsFinitelyGeneratedCone K) (hpointed : IsPointed K) :
    IsClosed K := by
  rcases hK with ⟨s, rfl⟩
  exact isClosed_conicHull_finset_of_isPointed s hpointed

/-- In finite dimensions, every finitely generated cone is closed. -/
theorem isClosed_conicHull_finset [FiniteDimensional ℝ E] (s : Finset E) :
    IsClosed (conicHull (↑s : Set E)) := by
  let K : Set E := conicHull (↑s : Set E)
  let L : Submodule ℝ E :=
    { carrier := K ∩ -K
      zero_mem' := by
        constructor
        · exact zero_mem_conicHull (↑s : Set E)
        · simpa using zero_mem_conicHull (↑s : Set E)
      add_mem' := by
        intro x y hx hy
        constructor
        · exact add_mem_of_convex_isCone (convex_conicHull _) (isCone_conicHull _) hx.1 hy.1
        · have hnegx : -x ∈ K := by simpa using hx.2
          have hnegy : -y ∈ K := by simpa using hy.2
          have hsum : -x + -y ∈ K :=
            add_mem_of_convex_isCone (convex_conicHull _) (isCone_conicHull _) hnegx hnegy
          simpa [K, neg_add, add_comm] using hsum
      smul_mem' := by
        intro a x hx
        constructor
        · by_cases ha : 0 ≤ a
          · exact (isCone_conicHull _).smul_mem hx.1 ha
          · have hna : 0 ≤ -a := by linarith
            have hnegx : -x ∈ K := by simpa using hx.2
            simpa [smul_neg, neg_smul, K] using (isCone_conicHull _).smul_mem hnegx hna
        · by_cases ha : 0 ≤ a
          · have hnegx : -x ∈ K := by simpa using hx.2
            have hscaled : a • (-x) ∈ K := (isCone_conicHull _).smul_mem hnegx ha
            simpa [smul_neg, neg_smul, K] using hscaled
          · have hna : 0 ≤ -a := by linarith
            have hscaled : (-a) • x ∈ K := (isCone_conicHull _).smul_mem hx.1 hna
            simpa [smul_neg, neg_smul, K] using hscaled }
  letI : IsClosed (L : Set E) := L.closed_of_finiteDimensional
  let q : E →ₗ[ℝ] E ⧸ L := L.mkQ
  have hqfg : IsFinitelyGeneratedCone (q '' K) :=
    (show IsFinitelyGeneratedCone K from ⟨s, rfl⟩).linear_image q
  have hqconv : Convex ℝ (q '' K) := hqfg.convex
  have hqcone : IsCone (q '' K) := hqfg.isCone
  have hqpointed : IsPointed (q '' K) := by
    apply (isPointed_iff_inter_neg_eq_singleton_zero hqconv hqcone).2
    apply le_antisymm
    · intro z hz
      rcases hz.1 with ⟨u, hu, rfl⟩
      have hzneg : -(q u) ∈ q '' K := by simpa using hz.2
      rcases hzneg with ⟨v, hv, hvq⟩
      have huvq : q (u + v) = 0 := by
        simpa [map_add] using congrArg (fun w => q u + w) hvq
      have huvL : u + v ∈ L := by
        have hker : u + v ∈ LinearMap.ker q := by
          simpa [LinearMap.mem_ker] using huvq
        simpa [q, Submodule.ker_mkQ] using hker
      have huvneg : -(u + v) ∈ K := by simpa [L, K] using huvL.2
      have huneg : -u ∈ K := by
        have : v + -(u + v) ∈ K :=
          add_mem_of_convex_isCone (convex_conicHull _) (isCone_conicHull _) hv huvneg
        simpa [sub_eq_add_neg, add_assoc, add_left_comm, add_comm, K] using this
      have huL : u ∈ L := by
        constructor
        · exact hu
        · simpa [K] using huneg
      have huq : q u = 0 := by
        have hker : u ∈ LinearMap.ker q := by
          simpa [q, Submodule.ker_mkQ] using huL
        simpa [LinearMap.mem_ker] using hker
      simpa [huq]
    · intro z hz
      have hz0 : z = 0 := by simpa using hz
      subst hz0
      constructor
      · exact hqcone.1
      · simpa using hqcone.1
  have hqclosed : IsClosed (q '' K) := hqfg.isClosed_of_isPointed hqpointed
  have hpre : q ⁻¹' (q '' K) = K := by
    ext x
    constructor
    · intro hx
      rcases hx with ⟨u, hu, hxu⟩
      have hdiffq : q (x - u) = 0 := by simpa [map_sub, hxu]
      have hdiffL : x - u ∈ L := by
        have hker : x - u ∈ LinearMap.ker q := by
          simpa [LinearMap.mem_ker] using hdiffq
        simpa [q, Submodule.ker_mkQ] using hker
      have hdiffK : x - u ∈ K := hdiffL.1
      have hx' : (x - u) + u = x := by
        simp [sub_eq_add_neg, add_assoc]
      rw [← hx']
      exact add_mem_of_convex_isCone (convex_conicHull _) (isCone_conicHull _) hdiffK hu
    · intro hx
      exact ⟨x, hx, rfl⟩
  have hqcont : Continuous q := LinearMap.continuous_of_finiteDimensional q
  simpa [K, hpre] using hqclosed.preimage hqcont

/-- In finite dimensions, the conic hull of a finite set is already closed. -/
theorem closure_conicHull_finset [FiniteDimensional ℝ E] (s : Finset E) :
    closure (conicHull (↑s : Set E)) = conicHull (↑s : Set E) :=
  (isClosed_conicHull_finset (E := E) s).closure_eq

/-- In finite dimensions, the horizon cone of a finitely generated conic hull
is the conic hull itself. -/
theorem horizonCone_conicHull_finset_eq_self [FiniteDimensional ℝ E] (s : Finset E) :
    horizonCone (conicHull (↑s : Set E)) = conicHull (↑s : Set E) := by
  rw [horizonCone_conicHull_eq_closure, closure_conicHull_finset]

/-- In finite dimensions, every finitely generated cone is closed. -/
theorem IsFinitelyGeneratedCone.isClosed [FiniteDimensional ℝ E]
    {K : Set E} (hK : IsFinitelyGeneratedCone K) :
    IsClosed K := by
  rcases hK with ⟨s, rfl⟩
  exact isClosed_conicHull_finset s

/-- In finite dimensions, a finitely generated cone equals its closure. -/
theorem IsFinitelyGeneratedCone.closure_eq_self [FiniteDimensional ℝ E]
    {K : Set E} (hK : IsFinitelyGeneratedCone K) :
    closure K = K :=
  hK.isClosed.closure_eq

/-- In finite dimensions, a finitely generated cone equals its horizon cone. -/
theorem IsFinitelyGeneratedCone.horizonCone_eq_self [FiniteDimensional ℝ E]
    {K : Set E} (hK : IsFinitelyGeneratedCone K) :
    horizonCone K = K := by
  rw [hK.horizonCone_eq_closure, hK.closure_eq_self]

end RW
